// compose / build / check — the load-bearing engine.
import { test } from "node:test";
import assert from "node:assert/strict";
import { run } from "../src/compose.mjs";
import { makeRoot, read, readRaw, has, outFile, recipe, brick, cleanup, write } from "./helpers.mjs";

test("build: simple include inlines the brick body", () => {
  const root = makeRoot({
    bricks: { greeting: "Hello from the brick." },
    recipes: { hi: "---\nname: hi\n---\n# hi\n\n<!-- include: greeting -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    assert.equal(r.written, 1);
    const txt = read(outFile(root, "hi"));
    assert.match(txt, /Hello from the brick\./);
  } finally { cleanup(root); }
});

test("build: include with params (`;` separator, spaces in value) and {{var}} substitution", () => {
  const root = makeRoot({
    bricks: { "run-dir": "Run {{skill}} with flags {{flags}}." },
    recipes: { fix: "---\nname: fix\n---\n# fix\n\n<!-- include: run-dir | skill=fix; flags=--prefix fix --track -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    const txt = read(outFile(root, "fix"));
    assert.match(txt, /Run fix with flags --prefix fix --track\./);
  } finally { cleanup(root); }
});

test("build: a literal `;` in a value survives via backslash escape (\\;)", () => {
  const root = makeRoot({
    bricks: { rule: "Rule: {{expr}}. Skill: {{skill}}." },
    recipes: { esc: "---\nname: esc\n---\n# esc\n\n<!-- include: rule | expr=a\\; b\\; c; skill=fix -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    const txt = read(outFile(root, "esc"));
    // `;` stays inside the value; the unescaped `;` still separates expr from skill.
    assert.match(txt, /Rule: a; b; c\. Skill: fix\./);
  } finally { cleanup(root); }
});

test("build: a literal backslash is written via `\\\\`", () => {
  const root = makeRoot({
    bricks: { p: "Path {{p}}." },
    recipes: { bs: "---\nname: bs\n---\n# bs\n\n<!-- include: p | p=a\\\\b -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    assert.match(read(outFile(root, "bs")), /Path a\\b\./);
  } finally { cleanup(root); }
});

test("build: missing brick → build error and NOTHING written", () => {
  const root = makeRoot({
    recipes: { x: "---\nname: x\n---\n# x\n\n<!-- include: nope -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.ok(r.errors.some((e) => e.startsWith("build error:") && /missing brick: nope/.test(e)));
    assert.equal(has(outFile(root, "x")), false, "no output file should exist on build error");
  } finally { cleanup(root); }
});

test("build: missing param → build error and nothing written", () => {
  const root = makeRoot({
    bricks: { needs: "Value is {{missing}}." },
    recipes: { y: "---\nname: y\n---\n# y\n\n<!-- include: needs -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.ok(r.errors.some((e) => e.startsWith("build error:") && /requires \{\{missing\}\}/.test(e)));
    assert.equal(has(outFile(root, "y")), false);
  } finally { cleanup(root); }
});

test("build: recipe WITHOUT frontmatter → banner at the very top", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { plain: "# plain\n\n<!-- include: b -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    const txt = read(outFile(root, "plain"));
    assert.match(txt.split("\n")[0], /^<!-- GENERATED by nbp-forge/);
  } finally { cleanup(root); }
});

test("build: recipe WITH frontmatter → banner after the closing ---", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { fm: "---\nname: fm\ndescription: d\n---\n# fm\n\n<!-- include: b -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    const lines = read(outFile(root, "fm")).split("\n");
    assert.equal(lines[0], "---");
    const close = lines.indexOf("---", 1);
    assert.ok(close > 0, "frontmatter must close");
    assert.match(lines[close + 1], /^<!-- GENERATED by nbp-forge/);
  } finally { cleanup(root); }
});

test("build: output EOL is always LF (no CR bytes), even on Windows", () => {
  const root = makeRoot({
    bricks: { b: "line one\nline two" },
    recipes: { eol: "---\nname: eol\n---\n# eol\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    const buf = readRaw(outFile(root, "eol"));
    assert.equal(buf.includes(0x0d), false, "generated file must contain no CR (0x0d) bytes");
  } finally { cleanup(root); }
});

test("build: CRLF in recipe/brick sources is normalized to LF in output", () => {
  const root = makeRoot({
    bricks: { b: "alpha\r\nbeta" },
    recipes: { crlf: "---\r\nname: crlf\r\n---\r\n# crlf\r\n\r\n<!-- include: b -->\r\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    const buf = readRaw(outFile(root, "crlf"));
    assert.equal(buf.includes(0x0d), false, "CRLF sources must produce LF-only output");
  } finally { cleanup(root); }
});

// ── conformance gate (agentskills SKILL.md standard) ─────────────────────────
const confRecipe = (name, desc) => `---\nname: ${name}\ndescription: ${desc}\n---\n# x\n\nbody\n`;

for (const [label, name] of [
  ["uppercase", "Feature"],
  ["doubled hyphen", "a--b"],
  ["leading hyphen", "-a"],
  ["trailing hyphen", "a-"],
  ["space", "a b"],
  ["65 chars", "a".repeat(65)],
]) {
  test(`conformance: invalid name (${label}) → build error, nothing written`, () => {
    const root = makeRoot({ recipes: { x: confRecipe(name, "ok desc") } });
    try {
      const r = run({ root, mode: "build" });
      assert.equal(r.ok, false, `expected failure for name "${name}"`);
      assert.equal(r.written, 0);
      assert.ok(r.errors.some((e) => e.startsWith("conformance:") && /name/.test(e)));
      assert.equal(has(outFile(root, "x")), false);
    } finally { cleanup(root); }
  });
}

test("conformance: empty and over-long description → error", () => {
  const empty = makeRoot({ recipes: { x: "---\nname: ok\ndescription:\n---\n# x\nbody\n" } });
  const long = makeRoot({ recipes: { x: confRecipe("ok", "d".repeat(1025)) } });
  try {
    const r1 = run({ root: empty, mode: "build" });
    assert.equal(r1.ok, false);
    assert.ok(r1.errors.some((e) => /description must not be empty/.test(e)));
    const r2 = run({ root: long, mode: "build" });
    assert.equal(r2.ok, false);
    assert.ok(r2.errors.some((e) => /description must be ≤1024/.test(e)));
  } finally { cleanup(empty); cleanup(long); }
});

test("conformance: valid name/description build cleanly", () => {
  const root = makeRoot({ recipes: { "my-skill": confRecipe("my-skill", "A fine description.") } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    assert.equal(r.written, 1);
  } finally { cleanup(root); }
});

test("conformance: quoted values are accepted (name: \"my-skill\")", () => {
  const root = makeRoot({ recipes: { x: `---\nname: "my-skill"\ndescription: 'A quoted description.'\n---\n# x\nbody\n` } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    assert.equal(r.written, 1);
  } finally { cleanup(root); }
});

test("conformance: CRLF recipe with empty description is still flagged (fm normalized first)", () => {
  const root = makeRoot({ recipes: { x: "---\r\nname: ok\r\ndescription:\r\n---\r\n# x\r\nbody\r\n" } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.ok(r.errors.some((e) => /description must not be empty/.test(e)), "CR must not smuggle past the empty check");
  } finally { cleanup(root); }
});

test("conformance: a recipe WITHOUT frontmatter is not flagged (slash-command case)", () => {
  const root = makeRoot({ recipes: { plain: "# plain\n\nno frontmatter here\n" } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    assert.ok(!r.errors.some((e) => e.startsWith("conformance:")));
  } finally { cleanup(root); }
});

test("conformance: can be disabled via config (conformance:false)", () => {
  const root = makeRoot({ config: { conformance: false }, recipes: { x: confRecipe("BadName", "d") } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, "disabled gate must not flag");
    assert.equal(r.written, 1);
  } finally { cleanup(root); }
});

test("build: an include that escapes bricks/ is a build error (nothing written)", () => {
  const root = makeRoot({
    bricks: { ok: "fine" },
    recipes: { x: "---\nname: x\ndescription: d.\n---\n# x\n\n<!-- include: ../../secret -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.ok(r.errors.some((e) => /escapes bricks\//.test(e)));
    assert.equal(has(outFile(root, "x")), false);
  } finally { cleanup(root); }
});

test("build: refuses a config where out == recipes (would overwrite source)", () => {
  const root = makeRoot({ config: { out: "recipes" }, recipes: { a: "---\nname: a\ndescription: d.\n---\n# a\nbody\n" } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.ok(r.errors.some((e) => /must not be inside or equal to/.test(e)));
  } finally { cleanup(root); }
});

test("build: refuses a config where a role dir is NESTED inside another (out under bricks)", () => {
  const root = makeRoot({ config: { out: "bricks/out" }, recipes: { a: "---\nname: a\ndescription: d.\n---\n# a\nbody\n" } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.ok(r.errors.some((e) => /must not be inside or equal to/.test(e)));
  } finally { cleanup(root); }
});

test("check: detects drift when the generated file is hand-edited", () => {
  const root = makeRoot({
    bricks: { b: "canonical body" },
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });          // in sync
    let ok = run({ root, mode: "check" });
    assert.equal(ok.ok, true);
    assert.equal(ok.drift, 0);

    // Tamper with the generated output by hand.
    const f = outFile(root, "d");
    write(f, read(f) + "\nhand-edited line\n");
    const drifted = run({ root, mode: "check" });
    assert.equal(drifted.ok, false);
    assert.equal(drifted.drift, 1);
    assert.ok(drifted.errors.some((e) => e.startsWith("drift:")));
  } finally { cleanup(root); }
});

test("check: CRLF in the generated file is NOT a false drift positive", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { c: "---\nname: c\n---\n# c\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    // Simulate a checkout that rewrote LF → CRLF (e.g. git autocrlf on Windows).
    const f = outFile(root, "c");
    write(f, read(f).replace(/\n/g, "\r\n"));
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, true, "CRLF must not register as drift");
    assert.equal(r.drift, 0);
  } finally { cleanup(root); }
});

test("build: skip-if-unchanged — a re-build writes nothing and leaves `written` honest", () => {
  const root = makeRoot({
    bricks: { b: "stable body" },
    recipes: { s: "---\nname: s\n---\n# s\n\n<!-- include: b -->\n" },
  });
  try {
    const first = run({ root, mode: "build" });
    assert.equal(first.written, 1);
    assert.equal(first.unchanged, 0);
    assert.deepEqual(first.plan, [{ name: "s", status: "create" }]);

    // Second build of identical inputs: nothing on disk changes.
    const before = readRaw(outFile(root, "s"));
    const second = run({ root, mode: "build" });
    assert.equal(second.written, 0, "unchanged output must not be rewritten");
    assert.equal(second.unchanged, 1);
    assert.deepEqual(second.plan, [{ name: "s", status: "same" }]);
    assert.deepEqual(readRaw(outFile(root, "s")), before, "bytes must be byte-identical");
  } finally { cleanup(root); }
});

test("build: only the changed skill is rewritten when one recipe edits", () => {
  const root = makeRoot({
    bricks: { b: "shared" },
    recipes: {
      a: "---\nname: a\n---\n# a\n\n<!-- include: b -->\n",
      c: "---\nname: c\n---\n# c\n\n<!-- include: b -->\n",
    },
  });
  try {
    run({ root, mode: "build" });
    // Edit one recipe; the other is untouched.
    write(recipe(root, "c"), "---\nname: c\n---\n# c changed\n\n<!-- include: b -->\n");
    const r = run({ root, mode: "build" });
    assert.equal(r.written, 1);
    assert.equal(r.unchanged, 1);
    assert.equal(r.plan.find((p) => p.name === "a").status, "same");
    assert.equal(r.plan.find((p) => p.name === "c").status, "change");
  } finally { cleanup(root); }
});

test("build: a CRLF-on-disk output is HEALED to LF (not skipped as unchanged)", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { h: "---\nname: h\n---\n# h\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    // An editor / git autocrlf rewrites the generated output to CRLF.
    const f = outFile(root, "h");
    const lf = read(f);
    write(f, lf.replace(/\n/g, "\r\n"));
    // check stays CR-insensitive (no false drift) ...
    assert.equal(run({ root, mode: "check" }).drift, 0, "check must tolerate CRLF");
    // ... but build restores the LF-only guarantee by rewriting the file.
    const r = run({ root, mode: "build" });
    assert.equal(r.written, 1, "CRLF output must be rewritten, not skipped");
    assert.equal(r.plan.find((p) => p.name === "h").status, "change");
    assert.equal(read(f), lf, "output is healed back to byte-identical LF");
    assert.equal(readRaw(f).includes(0x0d), false, "no CR bytes remain");
  } finally { cleanup(root); }
});

test("build --dry-run: classifies without writing anything", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: b -->\n" },
  });
  try {
    const r = run({ root, mode: "build", dryRun: true });
    assert.equal(r.ok, true, r.errors?.join("; "));
    assert.equal(r.written, 0, "dry-run must never write");
    assert.equal(has(outFile(root, "d")), false, "no output file is created");
    assert.deepEqual(r.plan, [{ name: "d", status: "create" }]);
  } finally { cleanup(root); }
});

test("build --dry-run: reports `change` and leaves the existing output untouched", () => {
  const root = makeRoot({
    bricks: { b: "v1" },
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    const before = readRaw(outFile(root, "d"));
    // Change the brick so the next build would differ — but only preview it.
    write(brick(root, "b"), "v2");
    const r = run({ root, mode: "build", dryRun: true });
    assert.equal(r.plan[0].status, "change");
    assert.equal(r.written, 0);
    assert.deepEqual(readRaw(outFile(root, "d")), before, "dry-run must not touch the output");
  } finally { cleanup(root); }
});

test("build --dry-run: a blocking error fails (not ok), still writes nothing", () => {
  const root = makeRoot({
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: missing -->\n" },
  });
  try {
    const r = run({ root, mode: "build", dryRun: true });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.equal(has(outFile(root, "d")), false);
  } finally { cleanup(root); }
});

test("check: enforceGenerated flags an orphan command (no recipe)", () => {
  const root = makeRoot({
    config: { enforceGenerated: true },
    bricks: { b: "body" },
    recipes: { real: "---\nname: real\n---\n# real\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    // Drop an output file that has no backing recipe.
    write(outFile(root, "stray"), "<!-- not generated by anything -->\n");
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, false);
    assert.equal(r.orphans, 1);
    assert.ok(r.errors.some((e) => e.startsWith("orphan:") && /stray/.test(e)));
  } finally { cleanup(root); }
});
