// compose / build / check — the load-bearing engine.
import { test } from "node:test";
import assert from "node:assert/strict";
import { run } from "../src/compose.mjs";
import { makeRoot, read, readRaw, has, outFile, cleanup, write } from "./helpers.mjs";

test("build: simple include inlines the brick body", () => {
  const root = makeRoot({
    bricks: { greeting: "Hello from the brick." },
    recipes: { hi: "---\nname: hi\n---\n# hi\n\n<!-- include: greeting -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    assert.equal(r.written, 1);
    const txt = read(outFile(root, "hi"));
    assert.match(txt, /Hello from the brick\./);
  } finally { cleanup(root); }
});

test("build: include with params (`;` separator, spaces in value) and {{var}} substitution", () => {
  const root = makeRoot({
    bricks: { "run-dir": "Run {{skill}} with flags {{flags}}." },
    recipes: { fix: "---\nname: fix\n---\n# fix\n\n<!-- include: run-dir | skill=fix; flags=--prefix fix --track -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    const txt = read(outFile(root, "fix"));
    assert.match(txt, /Run fix with flags --prefix fix --track\./);
  } finally { cleanup(root); }
});

test("build: missing brick → build error and NOTHING written", () => {
  const root = makeRoot({
    recipes: { x: "---\nname: x\n---\n# x\n\n<!-- include: nope -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.ok(r.errors.some((e) => e.startsWith("build error:") && /missing brick: nope/.test(e)));
    assert.equal(has(outFile(root, "x")), false, "no output file should exist on build error");
  } finally { cleanup(root); }
});

test("build: missing param → build error and nothing written", () => {
  const root = makeRoot({
    bricks: { needs: "Value is {{missing}}." },
    recipes: { y: "---\nname: y\n---\n# y\n\n<!-- include: needs -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.ok(r.errors.some((e) => e.startsWith("build error:") && /requires \{\{missing\}\}/.test(e)));
    assert.equal(has(outFile(root, "y")), false);
  } finally { cleanup(root); }
});

test("build: recipe WITHOUT frontmatter → banner at the very top", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { plain: "# plain\n\n<!-- include: b -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    const txt = read(outFile(root, "plain"));
    assert.match(txt.split("\n")[0], /^<!-- GENERATED by nbp-forge/);
  } finally { cleanup(root); }
});

test("build: recipe WITH frontmatter → banner after the closing ---", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { fm: "---\nname: fm\ndescription: d\n---\n# fm\n\n<!-- include: b -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    const lines = read(outFile(root, "fm")).split("\n");
    assert.equal(lines[0], "---");
    const close = lines.indexOf("---", 1);
    assert.ok(close > 0, "frontmatter must close");
    assert.match(lines[close + 1], /^<!-- GENERATED by nbp-forge/);
  } finally { cleanup(root); }
});

test("build: output EOL is always LF (no CR bytes), even on Windows", () => {
  const root = makeRoot({
    bricks: { b: "line one\nline two" },
    recipes: { eol: "---\nname: eol\n---\n# eol\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    const buf = readRaw(outFile(root, "eol"));
    assert.equal(buf.includes(0x0d), false, "generated file must contain no CR (0x0d) bytes");
  } finally { cleanup(root); }
});

test("build: CRLF in recipe/brick sources is normalized to LF in output", () => {
  const root = makeRoot({
    bricks: { b: "alpha\r\nbeta" },
    recipes: { crlf: "---\r\nname: crlf\r\n---\r\n# crlf\r\n\r\n<!-- include: b -->\r\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.join("; "));
    const buf = readRaw(outFile(root, "crlf"));
    assert.equal(buf.includes(0x0d), false, "CRLF sources must produce LF-only output");
  } finally { cleanup(root); }
});

test("check: detects drift when the generated file is hand-edited", () => {
  const root = makeRoot({
    bricks: { b: "canonical body" },
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });          // in sync
    let ok = run({ root, mode: "check" });
    assert.equal(ok.ok, true);
    assert.equal(ok.drift, 0);

    // Tamper with the generated output by hand.
    const f = outFile(root, "d");
    write(f, read(f) + "\nhand-edited line\n");
    const drifted = run({ root, mode: "check" });
    assert.equal(drifted.ok, false);
    assert.equal(drifted.drift, 1);
    assert.ok(drifted.errors.some((e) => e.startsWith("drift:")));
  } finally { cleanup(root); }
});

test("check: CRLF in the generated file is NOT a false drift positive", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { c: "---\nname: c\n---\n# c\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    // Simulate a checkout that rewrote LF → CRLF (e.g. git autocrlf on Windows).
    const f = outFile(root, "c");
    write(f, read(f).replace(/\n/g, "\r\n"));
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, true, "CRLF must not register as drift");
    assert.equal(r.drift, 0);
  } finally { cleanup(root); }
});

test("check: enforceGenerated flags an orphan command (no recipe)", () => {
  const root = makeRoot({
    config: { enforceGenerated: true },
    bricks: { b: "body" },
    recipes: { real: "---\nname: real\n---\n# real\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    // Drop an output file that has no backing recipe.
    write(outFile(root, "stray"), "<!-- not generated by anything -->\n");
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, false);
    assert.equal(r.orphans, 1);
    assert.ok(r.errors.some((e) => e.startsWith("orphan:") && /stray/.test(e)));
  } finally { cleanup(root); }
});
