// compose / build / check — the load-bearing engine.
import { test } from "node:test";
import assert from "node:assert/strict";
import { join, dirname } from "node:path";
import { sep } from "node:path";
import { symlinkSync, writeFileSync, mkdtempSync, mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { run, loadConfig, includesOf, splitFm, relFromBase, hasForgeRole, FORGE_ROLE_VALUE } from "../src/compose.mjs";
import { gc } from "../src/lifecycle.mjs";
import { makeRoot, read, readRaw, has, outFile, recipe, brick, cleanup, write } from "./helpers.mjs";

test("build: simple include inlines the brick body", () => {
  const root = makeRoot({
    bricks: { greeting: "Hello from the brick." },
    recipes: { hi: "---\nname: hi\n---\n# hi\n\n<!-- include: greeting -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.equal(r.written, 1);
    const txt = read(outFile(root, "hi"));
    assert.match(txt, /Hello from the brick\./);
  } finally { cleanup(root); }
});

test("build: include with params (`;` separator, spaces in value) and {{var}} substitution", () => {
  const root = makeRoot({
    bricks: { "run-dir": "Run {{skill}} with flags {{flags}}." },
    recipes: { fix: "---\nname: fix\n---\n# fix\n\n<!-- include: run-dir | skill=fix; flags=--prefix fix --track -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    const txt = read(outFile(root, "fix"));
    assert.match(txt, /Run fix with flags --prefix fix --track\./);
  } finally { cleanup(root); }
});

test("build: a literal `;` in a value survives via backslash escape (\\;)", () => {
  const root = makeRoot({
    bricks: { rule: "Rule: {{expr}}. Skill: {{skill}}." },
    recipes: { esc: "---\nname: esc\n---\n# esc\n\n<!-- include: rule | expr=a\\; b\\; c; skill=fix -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    const txt = read(outFile(root, "esc"));
    // `;` stays inside the value; the unescaped `;` still separates expr from skill.
    assert.match(txt, /Rule: a; b; c\. Skill: fix\./);
  } finally { cleanup(root); }
});

test("build: a literal backslash is written via `\\\\`", () => {
  const root = makeRoot({
    bricks: { p: "Path {{p}}." },
    recipes: { bs: "---\nname: bs\n---\n# bs\n\n<!-- include: p | p=a\\\\b -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.match(read(outFile(root, "bs")), /Path a\\b\./);
  } finally { cleanup(root); }
});

test("build: missing brick → build error and NOTHING written", () => {
  const root = makeRoot({
    recipes: { x: "---\nname: x\n---\n# x\n\n<!-- include: nope -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.ok(r.errors.some((e) => e.kind === "build" && /missing brick: nope/.test(e.msg)));
    assert.equal(has(outFile(root, "x")), false, "no output file should exist on build error");
  } finally { cleanup(root); }
});

test("build: missing param → build error and nothing written", () => {
  const root = makeRoot({
    bricks: { needs: "Value is {{missing}}." },
    recipes: { y: "---\nname: y\n---\n# y\n\n<!-- include: needs -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.ok(r.errors.some((e) => e.kind === "build" && /requires \{\{missing\}\}/.test(e.msg)));
    assert.equal(has(outFile(root, "y")), false);
  } finally { cleanup(root); }
});

test("build: recipe WITHOUT frontmatter → banner at the very top", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { plain: "# plain\n\n<!-- include: b -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    const txt = read(outFile(root, "plain"));
    assert.match(txt.split("\n")[0], /^<!-- GENERATED by nbp-skillforge/);
  } finally { cleanup(root); }
});

test("build: recipe WITH frontmatter → banner after the closing ---", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { fm: "---\nname: fm\ndescription: d\n---\n# fm\n\n<!-- include: b -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    const lines = read(outFile(root, "fm")).split("\n");
    assert.equal(lines[0], "---");
    const close = lines.indexOf("---", 1);
    assert.ok(close > 0, "frontmatter must close");
    assert.match(lines[close + 1], /^<!-- GENERATED by nbp-skillforge/);
  } finally { cleanup(root); }
});

test("build: output EOL is always LF (no CR bytes), even on Windows", () => {
  const root = makeRoot({
    bricks: { b: "line one\nline two" },
    recipes: { eol: "---\nname: eol\n---\n# eol\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    const buf = readRaw(outFile(root, "eol"));
    assert.equal(buf.includes(0x0d), false, "generated file must contain no CR (0x0d) bytes");
  } finally { cleanup(root); }
});

test("build: CRLF in recipe/brick sources is normalized to LF in output", () => {
  const root = makeRoot({
    bricks: { b: "alpha\r\nbeta" },
    recipes: { crlf: "---\r\nname: crlf\r\n---\r\n# crlf\r\n\r\n<!-- include: b -->\r\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    const buf = readRaw(outFile(root, "crlf"));
    assert.equal(buf.includes(0x0d), false, "CRLF sources must produce LF-only output");
  } finally { cleanup(root); }
});

// ── conformance gate (agentskills SKILL.md standard) ─────────────────────────
const confRecipe = (name, desc) => `---\nname: ${name}\ndescription: ${desc}\n---\n# x\n\nbody\n`;

for (const [label, name] of [
  ["uppercase", "Feature"],
  ["doubled hyphen", "a--b"],
  ["leading hyphen", "-a"],
  ["trailing hyphen", "a-"],
  ["space", "a b"],
  ["65 chars", "a".repeat(65)],
]) {
  test(`conformance: invalid name (${label}) → build error, nothing written`, () => {
    const root = makeRoot({ recipes: { x: confRecipe(name, "ok desc") } });
    try {
      const r = run({ root, mode: "build" });
      assert.equal(r.ok, false, `expected failure for name "${name}"`);
      assert.equal(r.written, 0);
      assert.ok(r.errors.some((e) => e.kind === "conformance" && /name/.test(e.msg)));
      assert.equal(has(outFile(root, "x")), false);
    } finally { cleanup(root); }
  });
}

test("conformance: empty and over-long description → error", () => {
  const empty = makeRoot({ recipes: { x: "---\nname: ok\ndescription:\n---\n# x\nbody\n" } });
  const long = makeRoot({ recipes: { x: confRecipe("ok", "d".repeat(1025)) } });
  try {
    const r1 = run({ root: empty, mode: "build" });
    assert.equal(r1.ok, false);
    assert.ok(r1.errors.some((e) => e.kind === "conformance" && /description must not be empty/.test(e.msg)));
    const r2 = run({ root: long, mode: "build" });
    assert.equal(r2.ok, false);
    assert.ok(r2.errors.some((e) => e.kind === "conformance" && /description must be ≤1024/.test(e.msg)));
  } finally { cleanup(empty); cleanup(long); }
});

test("conformance: valid name/description build cleanly", () => {
  const root = makeRoot({ recipes: { "my-skill": confRecipe("my-skill", "A fine description.") } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.equal(r.written, 1);
  } finally { cleanup(root); }
});

test("conformance: quoted values are accepted (name: \"my-skill\")", () => {
  const root = makeRoot({ recipes: { x: `---\nname: "my-skill"\ndescription: 'A quoted description.'\n---\n# x\nbody\n` } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.equal(r.written, 1);
  } finally { cleanup(root); }
});

test("conformance: CRLF recipe with empty description is still flagged (fm normalized first)", () => {
  const root = makeRoot({ recipes: { x: "---\r\nname: ok\r\ndescription:\r\n---\r\n# x\r\nbody\r\n" } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.ok(r.errors.some((e) => e.kind === "conformance" && /description must not be empty/.test(e.msg)), "CR must not smuggle past the empty check");
  } finally { cleanup(root); }
});

test("conformance: a recipe WITHOUT frontmatter is not flagged (slash-command case)", () => {
  const root = makeRoot({ recipes: { plain: "# plain\n\nno frontmatter here\n" } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.ok(!r.errors.some((e) => e.kind === "conformance"));
  } finally { cleanup(root); }
});

test("conformance: can be disabled via config (conformance:false)", () => {
  const root = makeRoot({ config: { conformance: false }, recipes: { x: confRecipe("BadName", "d") } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, "disabled gate must not flag");
    assert.equal(r.written, 1);
  } finally { cleanup(root); }
});

test("build: an include that escapes bricks/ is a build error (nothing written)", () => {
  const root = makeRoot({
    bricks: { ok: "fine" },
    recipes: { x: "---\nname: x\ndescription: d.\n---\n# x\n\n<!-- include: ../../secret -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.ok(r.errors.some((e) => e.kind === "build" && /escapes bricks\//.test(e.msg)));
    assert.equal(has(outFile(root, "x")), false);
  } finally { cleanup(root); }
});

test("build: refuses a config where out == recipes (would overwrite source)", () => {
  const root = makeRoot({ config: { out: "recipes" }, recipes: { a: "---\nname: a\ndescription: d.\n---\n# a\nbody\n" } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.ok(r.errors.some((e) => e.kind === "config" && /must not be inside or equal to/.test(e.msg)));
  } finally { cleanup(root); }
});

test("build: refuses a config where a role dir is NESTED inside another (out under bricks)", () => {
  const root = makeRoot({ config: { out: "bricks/out" }, recipes: { a: "---\nname: a\ndescription: d.\n---\n# a\nbody\n" } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.ok(r.errors.some((e) => e.kind === "config" && /must not be inside or equal to/.test(e.msg)));
  } finally { cleanup(root); }
});

// F-13: the role-overlap check must fold case on a case-insensitive FS EVEN WHEN neither of the
// two colliding dirs exists yet (pre-first-build) — that's exactly when realpath can't do the
// folding for us, so the check needs canonFold (not plain canon) here specifically. Only
// meaningful on win32/darwin; on a case-sensitive FS "Shared" and "shared" are genuinely distinct.
test("build: refuses a config where two role dirs differ ONLY by case, neither created yet", { skip: !(process.platform === "win32" || process.platform === "darwin") }, () => {
  const root = makeRoot({ config: { bricks: "Shared", out: "shared" }, recipes: { a: "---\nname: a\ndescription: d.\n---\n# a\nbody\n" } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.ok(r.errors.some((e) => e.kind === "config" && /must not be inside or equal to/.test(e.msg)));
  } finally { cleanup(root); }
});

test("check: detects drift when the generated file is hand-edited", () => {
  const root = makeRoot({
    bricks: { b: "canonical body" },
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });          // in sync
    let ok = run({ root, mode: "check" });
    assert.equal(ok.ok, true);
    assert.equal(ok.drift, 0);

    // Tamper with the generated output by hand (append a line after EOF).
    const f = outFile(root, "d");
    write(f, read(f) + "\nhand-edited line\n");
    const drifted = run({ root, mode: "check" });
    assert.equal(drifted.ok, false);
    assert.equal(drifted.drift, 1);
    const e = drifted.errors.find((e) => e.kind === "drift");
    assert.ok(e);
    // F-18: the message now points at the first diverging line with expected/found excerpts.
    assert.match(e.msg, /is out of sync with its recipe \(first difference at line \d+: expected .+, found "hand-edited line"\)/);
  } finally { cleanup(root); }
});

// F-18: a divergence in the MIDDLE of the file (not just an append-at-EOF) must point at the
// exact line number and quote both sides' content (truncated to 60 chars).
test("check: drift message points at the first diverging line, mid-file", () => {
  const root = makeRoot({
    bricks: { b: "line one\nline two\nline three" },
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    const f = outFile(root, "d");
    const built = read(f);
    const lineNo = built.split("\n").findIndex((l) => l === "line two") + 1;
    write(f, built.replace("line two", "LINE TWO CHANGED"));
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, false);
    const e = r.errors.find((e) => e.kind === "drift");
    assert.equal(e.msg, `drift: out/d.md is out of sync with its recipe (first difference at line ${lineNo}: expected "line two", found "LINE TWO CHANGED")`);
  } finally { cleanup(root); }
});

// F-18: a long line is truncated to 60 chars (with an ellipsis) so the message stays terse.
test("check: drift message excerpts are truncated to 60 chars", () => {
  const root = makeRoot({
    bricks: { b: "short line" },
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    const f = outFile(root, "d");
    write(f, read(f).replace("short line", "x".repeat(80)));
    const r = run({ root, mode: "check" });
    const e = r.errors.find((e) => e.kind === "drift");
    assert.match(e.msg, /found "x{60}…"/);
    assert.ok(!e.msg.includes("x".repeat(61)));
  } finally { cleanup(root); }
});

// F-18: the symmetric case — the on-disk file is SHORTER than the built content (a hand-edit
// truncated/removed trailing lines) — must report "found end-of-file", not crash or mis-point.
test("check: drift message reports 'found end-of-file' when the on-disk file was truncated", () => {
  const root = makeRoot({
    bricks: { b: "line one\nline two\nline three" },
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    const f = outFile(root, "d");
    const builtLines = read(f).split("\n");
    // Keep every line up to (and including) "line two" verbatim, but drop the final "line three"
    // line AND the trailing newline itself (not just its content) — so the on-disk array is
    // genuinely SHORTER than the built array (no trailing "" element to mask the truncation).
    const cutAt = builtLines.indexOf("line two") + 1;
    write(f, builtLines.slice(0, cutAt).join("\n"));
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, false);
    const e = r.errors.find((e) => e.kind === "drift");
    assert.match(e.msg, /found end-of-file/);
    assert.match(e.msg, /expected "line three"/);
  } finally { cleanup(root); }
});

test("check: an output that was never built is reported as missing, not out of sync", () => {
  const root = makeRoot({
    bricks: { b: "canonical body" },
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: b -->\n" },
  });
  try {
    const r = run({ root, mode: "check" }); // never built
    assert.equal(r.ok, false);
    assert.equal(r.drift, 1);
    assert.ok(r.errors.some((e) => e.kind === "drift" && /is missing \(run `npx nbp-skillforge build`\)/.test(e.msg)));
    assert.ok(!r.errors.some((e) => /out of sync/.test(e.msg)));
  } finally { cleanup(root); }
});

test("check: CRLF in the generated file is NOT a false drift positive", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { c: "---\nname: c\n---\n# c\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    // Simulate a checkout that rewrote LF → CRLF (e.g. git autocrlf on Windows).
    const f = outFile(root, "c");
    write(f, read(f).replace(/\n/g, "\r\n"));
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, true, "CRLF must not register as drift");
    assert.equal(r.drift, 0);
  } finally { cleanup(root); }
});

// F-18: a genuinely-diverged CRLF checkout must still compute the line-diff on the
// LF-normalized text (correct line number/excerpt), not on raw CRLF byte offsets.
test("check: drift on a CRLF checkout reports a line-diff computed on LF-normalized text", () => {
  const root = makeRoot({
    bricks: { b: "line one\nline two\nline three" },
    recipes: { c: "---\nname: c\n---\n# c\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    const f = outFile(root, "c");
    const built = read(f);
    const lineNo = built.split("\n").findIndex((l) => l === "line two") + 1;
    // CRLF checkout AND a genuine hand-edit on the same file.
    const tampered = built.replace("line two", "CHANGED").replace(/\n/g, "\r\n");
    write(f, tampered);
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, false);
    const e = r.errors.find((e) => e.kind === "drift");
    assert.equal(e.msg, `drift: out/c.md is out of sync with its recipe (first difference at line ${lineNo}: expected "line two", found "CHANGED")`);
  } finally { cleanup(root); }
});

test("build: skip-if-unchanged — a re-build writes nothing and leaves `written` honest", () => {
  const root = makeRoot({
    bricks: { b: "stable body" },
    recipes: { s: "---\nname: s\n---\n# s\n\n<!-- include: b -->\n" },
  });
  try {
    const first = run({ root, mode: "build" });
    assert.equal(first.written, 1);
    assert.equal(first.unchanged, 0);
    // F-26 (DECISION 2): plan entries carry `out` ALWAYS, even for N=1 — one shape, no branching.
    assert.deepEqual(first.plan, [{ name: "s", out: "out", status: "create" }]);

    // Second build of identical inputs: nothing on disk changes.
    const before = readRaw(outFile(root, "s"));
    const second = run({ root, mode: "build" });
    assert.equal(second.written, 0, "unchanged output must not be rewritten");
    assert.equal(second.unchanged, 1);
    assert.deepEqual(second.plan, [{ name: "s", out: "out", status: "same" }]);
    assert.deepEqual(readRaw(outFile(root, "s")), before, "bytes must be byte-identical");
  } finally { cleanup(root); }
});

test("build: only the changed skill is rewritten when one recipe edits", () => {
  const root = makeRoot({
    bricks: { b: "shared" },
    recipes: {
      a: "---\nname: a\n---\n# a\n\n<!-- include: b -->\n",
      c: "---\nname: c\n---\n# c\n\n<!-- include: b -->\n",
    },
  });
  try {
    run({ root, mode: "build" });
    // Edit one recipe; the other is untouched.
    write(recipe(root, "c"), "---\nname: c\n---\n# c changed\n\n<!-- include: b -->\n");
    const r = run({ root, mode: "build" });
    assert.equal(r.written, 1);
    assert.equal(r.unchanged, 1);
    assert.equal(r.plan.find((p) => p.name === "a").status, "same");
    assert.equal(r.plan.find((p) => p.name === "c").status, "change");
  } finally { cleanup(root); }
});

test("build: a CRLF-on-disk output is HEALED to LF (not skipped as unchanged)", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { h: "---\nname: h\n---\n# h\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    // An editor / git autocrlf rewrites the generated output to CRLF.
    const f = outFile(root, "h");
    const lf = read(f);
    write(f, lf.replace(/\n/g, "\r\n"));
    // check stays CR-insensitive (no false drift) ...
    assert.equal(run({ root, mode: "check" }).drift, 0, "check must tolerate CRLF");
    // ... but build restores the LF-only guarantee by rewriting the file.
    const r = run({ root, mode: "build" });
    assert.equal(r.written, 1, "CRLF output must be rewritten, not skipped");
    assert.equal(r.plan.find((p) => p.name === "h").status, "change");
    assert.equal(read(f), lf, "output is healed back to byte-identical LF");
    assert.equal(readRaw(f).includes(0x0d), false, "no CR bytes remain");
  } finally { cleanup(root); }
});

test("build --dry-run: classifies without writing anything", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: b -->\n" },
  });
  try {
    const r = run({ root, mode: "build", dryRun: true });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.equal(r.written, 0, "dry-run must never write");
    assert.equal(has(outFile(root, "d")), false, "no output file is created");
    assert.deepEqual(r.plan, [{ name: "d", out: "out", status: "create" }]); // F-26: `out` always present
  } finally { cleanup(root); }
});

test("build --dry-run: reports `change` and leaves the existing output untouched", () => {
  const root = makeRoot({
    bricks: { b: "v1" },
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    const before = readRaw(outFile(root, "d"));
    // Change the brick so the next build would differ — but only preview it.
    write(brick(root, "b"), "v2");
    const r = run({ root, mode: "build", dryRun: true });
    assert.equal(r.plan[0].status, "change");
    assert.equal(r.written, 0);
    assert.deepEqual(readRaw(outFile(root, "d")), before, "dry-run must not touch the output");
  } finally { cleanup(root); }
});

test("build --dry-run: a blocking error fails (not ok), still writes nothing", () => {
  const root = makeRoot({
    recipes: { d: "---\nname: d\n---\n# d\n\n<!-- include: missing -->\n" },
  });
  try {
    const r = run({ root, mode: "build", dryRun: true });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.equal(has(outFile(root, "d")), false);
  } finally { cleanup(root); }
});

test("check: enforceGenerated flags an orphan command (no recipe)", () => {
  const root = makeRoot({
    config: { enforceGenerated: true },
    bricks: { b: "body" },
    recipes: { real: "---\nname: real\n---\n# real\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    // Drop an output file that has no backing recipe.
    write(outFile(root, "stray"), "<!-- not generated by anything -->\n");
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, false);
    assert.equal(r.orphans, 1);
    assert.ok(r.errors.some((e) => e.kind === "orphan" && /stray/.test(e.msg)));
  } finally { cleanup(root); }
});

test("config: invalid forge.config.json throws a clean, user-facing error (no raw SyntaxError)", () => {
  const root = makeRoot({ recipes: { a: "---\nname: a\n---\n# a\nbody\n" } });
  try {
    write(join(root, "forge.config.json"), "{ not valid json");
    assert.throws(() => loadConfig(root), /forge\.config\.json: invalid JSON/);
    // The engine surfaces it through run() (which loads config) rather than crashing opaquely.
    assert.throws(() => run({ root, mode: "check" }), /forge\.config\.json: invalid JSON/);
  } finally { cleanup(root); }
});

test("build/check: a missing recipes directory is a clean error, not a crash", () => {
  const root = makeRoot({ config: { recipes: "nope" } }); // no recipes fixture → dir never created
  try {
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, false);
    assert.ok(r.errors.some((e) => e.kind === "config" && /no recipes directory: nope/.test(e.msg)));
    assert.ok(r.errors.some((e) => /run `npx nbp-skillforge init` to scaffold a forge project/.test(e.msg)), "hostile first-contact hint");
  } finally { cleanup(root); }
});

// Release-readiness fix (2026-07-07): the SPEC's --json contract says every result field is
// ALWAYS present (consumers never branch on absence) — the two config-error early returns used
// to emit a partial shape missing warnings/count/written/unchanged (and plan on build).
test("run: config-error early returns carry the FULL result shape (role overlap + missing recipes, both modes)", () => {
  const overlapRoot = makeRoot({ config: { out: "bricks" } });   // out === bricks role
  const noRecipesRoot = makeRoot({ config: { recipes: "nope" } });
  try {
    for (const root of [overlapRoot, noRecipesRoot]) {
      for (const mode of ["build", "check"]) {
        const r = run({ root, mode });
        assert.equal(r.ok, false);
        assert.equal(r.errors[0].kind, "config");
        // Aggregates present and zeroed/empty (nothing was composed or written).
        assert.deepEqual(r.warnings, [], `${mode}: warnings always present`);
        assert.equal(r.count, 0, `${mode}: count always present`);
        assert.equal(r.written, 0, `${mode}: written always present`);
        assert.equal(r.unchanged, 0, `${mode}: unchanged always present`);
        assert.equal(r.drift, 0);
        assert.equal(r.orphans, 0);
        assert.equal(typeof r.destinations, "number");
        // plan mirrors the happy path: an (empty) array on build, absent on check.
        if (mode === "build") assert.deepEqual(r.plan, [], "build: plan always present (empty)");
        else assert.equal(r.plan, undefined, "check: plan stays a build-only field");
      }
    }
  } finally { cleanup(overlapRoot); cleanup(noRecipesRoot); }
});

// Release-readiness fix (2026-07-07): a DIRECTORY squatting a brick's name (bricks/foo.md/)
// passes existsSync + realpath + the case-match, then readFileSync used to throw a raw EISDIR
// that crashed the whole command — an environment problem must be a structured, blocking build
// error, symmetric with the destination-side EISDIR handling (Fable B9).
test("build: a brick that is a DIRECTORY is a structured build error (blocking), not an EISDIR crash", () => {
  const root = makeRoot({ recipes: { demo: "---\nname: demo\ndescription: d.\n---\n# demo\n\n<!-- include: foo -->\n" } });
  mkdirSync(join(root, "bricks", "foo.md"), { recursive: true }); // dir squatting the brick path
  try {
    const r = run({ root, mode: "build" }); // must NOT throw
    assert.equal(r.ok, false);
    assert.equal(r.written, 0, "blocking: nothing written project-wide");
    assert.ok(r.errors.some((e) =>
      e.kind === "build" && /cannot read brick foo \(\w+\) — is it a directory\?/.test(e.msg)),
      `structured error expected, got: ${r.errors.map((e) => e.msg).join("; ")}`);
    assert.equal(has(outFile(root, "demo")), false);
    // check mode takes the same path (compose runs in both modes) — still no crash.
    assert.equal(run({ root, mode: "check" }).ok, false);
  } finally { cleanup(root); }
});

test("params: a bare key without `=` substitutes to an empty string (builds ok)", () => {
  const root = makeRoot({
    bricks: { b: "before[{{k}}]after" },
    recipes: { r: "---\nname: r\n---\n# r\n\n<!-- include: b | k -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.match(read(outFile(root, "r")), /before\[\]after/, "{{k}} → empty string for a valueless key");
  } finally { cleanup(root); }
});

// ── F-01: a brick body must not contain an include directive (no nesting) ───────
test("build: a brick body containing an include directive is a build error (no nesting), nothing written", () => {
  const root = makeRoot({
    bricks: { inner: "This is the inner brick content.", outer: "Outer top.\n<!-- include: inner -->\nOuter bottom." },
    recipes: { demo: "---\nname: demo\n---\n# demo\n\n<!-- include: outer -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.ok(r.errors.some((e) =>
      e.kind === "build" &&
      e.msg === "build error: [demo] brick outer contains a nested include (inner) — bricks must not include bricks (inline the content or include both from the recipe)"));
    assert.equal(has(outFile(root, "demo")), false);
  } finally { cleanup(root); }
});

// ── T2: pin the matchAll (not .test()/.exec()) invariant for the nested-include gate ───────────
// The gate must use `[...b.matchAll(INCLUDE)]`, never `INCLUDE.test(b)`, on the shared MODULE-
// LEVEL `INCLUDE` regex — `.test()`/`.exec()` with the `g` flag mutate `INCLUDE.lastIndex` as a
// side effect; `.matchAll()`'s spec-mandated clone SEEDS its copy's lastIndex from the original's
// (still-dirty) lastIndex, so a later, UNRELATED `includesOf()`/`matchAll()` call in the same
// process can silently start scanning past a real include near the start of a short text and miss
// it. A simple "does the nested-include case still work" test would NOT catch a regression back
// to `.test()` — it passes either way. This test needs a SEPARATE, later matchAll consumer
// (includesOf) in the SAME process to actually exercise the shared-regex leak.
test("F-01: the nested-include gate does not dirty the shared INCLUDE regex for a LATER includesOf() call", () => {
  const root = makeRoot({
    bricks: {
      wrapper: "<!-- include: inner -->\n", // brick-in-brick: triggers the nested-include gate
      inner: "inner content",
    },
    recipes: { broken: "---\nname: broken\n---\n# broken\n\n<!-- include: wrapper -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false, "the nested include must still be a build error");
    assert.ok(r.errors.some((e) => /nested include/.test(e.msg)));
  } finally { cleanup(root); }
  // A SEPARATE, short text with a real include at the very start (offset 0), processed AFTER the
  // nested-include build above, in the same process (same shared module-level INCLUDE regex).
  assert.deepEqual(includesOf("<!-- include: real -->\n"), ["real"],
    "a real include right at the start of a later, unrelated text must still be found — the shared INCLUDE regex's lastIndex must not have leaked");
});

test("build: an include directive inside a BRICK's own frontmatter is NOT a nested-include error", () => {
  const root = makeRoot({
    bricks: {
      inner: "inner content",
      outer: "---\npiece: outer\n<!-- include: inner -->\n---\nOuter body, no include here.",
    },
    recipes: { demo: "---\nname: demo\n---\n# demo\n\n<!-- include: outer -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.match(read(outFile(root, "demo")), /Outer body, no include here\./);
  } finally { cleanup(root); }
});

test("build --dry-run: a nested include in a brick body still fails, writes nothing", () => {
  const root = makeRoot({
    bricks: { inner: "inner", outer: "<!-- include: inner -->" },
    recipes: { demo: "---\nname: demo\n---\n# demo\n\n<!-- include: outer -->\n" },
  });
  try {
    const r = run({ root, mode: "build", dryRun: true });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.equal(has(outFile(root, "demo")), false);
  } finally { cleanup(root); }
});

// ── F-02: include path must match the on-disk brick's case exactly ──────────────
// Only meaningful on a case-insensitive filesystem (win32/darwin); on a case-sensitive FS the
// existsSync() check earlier in compose() already rejects the mismatch, so skip there.
const skipCaseTest = !(process.platform === "win32" || process.platform === "darwin");

test("build: include path case mismatch is a build error, even on a case-insensitive FS", { skip: skipCaseTest }, () => {
  const root = makeRoot({
    bricks: { "core/run": "Run instructions here." },
    recipes: { mismatch: "---\nname: mismatch\n---\n# mismatch\n\n<!-- include: Core/Run -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.ok(r.errors.some((e) =>
      e.kind === "build" && /case mismatch: Core\/Run/.test(e.msg) && /on-disk: core\/run\.md/.test(e.msg)));
    assert.equal(has(outFile(root, "mismatch")), false);
  } finally { cleanup(root); }
});

test("build: an include whose case matches the on-disk brick exactly still builds", { skip: skipCaseTest }, () => {
  const root = makeRoot({
    bricks: { "core/run": "Run instructions here." },
    recipes: { ok: "---\nname: ok\n---\n# ok\n\n<!-- include: core/run -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.match(read(outFile(root, "ok")), /Run instructions here\./);
  } finally { cleanup(root); }
});

// A-1: a brick symlink whose target resolves OUTSIDE bricks/ was silently followed until 0.5.0;
// the F-02 on-disk identity check now rejects it — with a symlink-specific message, NOT the
// nonsensical "case mismatch (on-disk: <suffix>)". Skips when the OS won't let us create a symlink
// (Windows without the privilege → EPERM); the code path is unambiguous and runs on POSIX/CI.
test("build: an include resolving outside bricks/ via symlink is rejected as a symlink escape, not a case mismatch", () => {
  const root = makeRoot({ recipes: { s: "---\nname: s\n---\n# s\n\n<!-- include: evil -->\n" } });
  const outside = mkdtempSync(join(tmpdir(), "forge-outside-"));
  writeFileSync(join(outside, "target.md"), "content that lives outside bricks/");
  const link = join(root, "bricks", "evil.md");
  mkdirSync(dirname(link), { recursive: true });
  let made = true;
  try { symlinkSync(join(outside, "target.md"), link); } catch { made = false; }
  if (!made) { cleanup(root); rmSync(outside, { recursive: true, force: true }); return; } // no symlink privilege — skip
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.equal(r.written, 0);
    assert.ok(r.errors.some((e) => e.kind === "build" && /resolves outside bricks\/ \(symlink\?\): evil/.test(e.msg)),
      "expected a symlink-outside message, got: " + r.errors.map((e) => e.msg).join("; "));
    assert.ok(!r.errors.some((e) => /case mismatch/.test(e.msg)), "must NOT be labelled a case mismatch");
    assert.equal(has(outFile(root, "s")), false);
  } finally { cleanup(root); rmSync(outside, { recursive: true, force: true }); }
});

// A symlink pointing INSIDE bricks/ (to a differently-named real brick) is NOT a symlink-escape —
// it stays a case/identity mismatch (the resolved name differs from the include). Guards against
// the A-1 fix over-reporting every symlink as "outside".
test("build: a bricks-internal symlink is a case/identity mismatch, NOT a symlink-escape", () => {
  const root = makeRoot({
    bricks: { real: "the real brick body" },
    recipes: { s: "---\nname: s\n---\n# s\n\n<!-- include: alias -->\n" },
  });
  const link = join(root, "bricks", "alias.md");
  let made = true;
  try { symlinkSync(join(root, "bricks", "real.md"), link); } catch { made = false; }
  if (!made) { cleanup(root); return; } // no symlink privilege — skip
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.ok(!r.errors.some((e) => /resolves outside bricks/.test(e.msg)), "an in-tree symlink is not an escape");
    assert.ok(r.errors.some((e) => /case mismatch/.test(e.msg)), "resolved name differs from the include → mismatch");
  } finally { cleanup(root); }
});

// ── C4 regression: relFromBase (the F-02 case-check's slice helper) must not eat the first
// char of the relative path when `base` IS a filesystem/drive root (already ends with `sep`) ──
// Pure-string unit test — no real drive-root filesystem access needed/wanted.
test("relFromBase: base is a drive/fs root (C4) — does not eat the first char of the relative path", () => {
  const root = sep === "\\" ? "C:\\" : "/";
  assert.equal(relFromBase(root, root + "core" + sep + "run.md"), "core" + sep + "run.md");
});
test("relFromBase: a normal (non-root) base still strips base + one separator", () => {
  const base = sep === "\\" ? "C:\\bricks" : "/bricks";
  assert.equal(relFromBase(base, base + sep + "core" + sep + "run.md"), "core" + sep + "run.md");
});

// ── F-03: include directives inside a fenced code block are ignored ─────────────
test("build: an include directive inside a ``` fence is preserved verbatim, not expanded", () => {
  const root = makeRoot({
    bricks: { inner: "Inner brick content." },
    recipes: {
      outer: "---\nname: outer\n---\n# outer\n\nExample:\n```md\n<!-- include: inner -->\n```\n",
    },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    const txt = read(outFile(root, "outer"));
    assert.match(txt, /```md\n<!-- include: inner -->\n```/, "the directive must survive verbatim inside the fence");
    assert.doesNotMatch(txt, /Inner brick content\./, "the fenced directive must NOT expand");
  } finally { cleanup(root); }
});

// T3: this test's title has always said "gc", but it never actually called gc() — it only
// checked includesOf() directly, which would miss a regression in gc/list's OWN wiring (e.g. if
// gc stopped calling includesOf/brickConsumers correctly, or filtered differently). Actually call
// gc (dry, no --apply) and assert the fenced-only brick is reported as an orphan.
test("gc: a brick cited ONLY inside a fence is an orphan (ref-count ignores fenced includes)", () => {
  const root = makeRoot({
    bricks: { docsonly: "Never really used." },
    recipes: {
      outer: "---\nname: outer\n---\n# outer\n\n```md\n<!-- include: docsonly -->\n```\n",
    },
  });
  try {
    assert.deepEqual(includesOf(read(recipe(root, "outer"))), [], "a fenced directive must not be ref-counted");
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    const g = gc(root); // dry (no --apply): must report, not archive
    assert.deepEqual(g.orphans, ["docsonly"], "gc itself must list the fenced-only brick as an orphan");
    assert.equal(g.applied, false);
    assert.equal(has(brick(root, "docsonly")), true, "dry gc must not have moved/archived anything");
  } finally { cleanup(root); }
});

test("build: an unterminated fence (opened, never closed) masks everything after it to EOF", () => {
  const root = makeRoot({
    bricks: { inner: "Inner brick content." },
    recipes: {
      outer: "---\nname: outer\n---\n# outer\n\n```md\nunterminated fence\n<!-- include: inner -->\n",
    },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    const txt = read(outFile(root, "outer"));
    assert.match(txt, /<!-- include: inner -->/, "the directive after an unclosed fence must NOT expand");
    assert.doesNotMatch(txt, /Inner brick content\./);
  } finally { cleanup(root); }
});

// ── C2 regression: a closing fence must have ONLY the fence run (+ trailing whitespace) on its
// line — a longer/equal fence run followed by more text does NOT close it (f03repro) ──────────
test("build: a fence-like line with trailing text (````not-a-close) does NOT close the fence — a later include stays masked", () => {
  const root = makeRoot({
    bricks: { b: "SHOULD_NOT_APPEAR" },
    recipes: {
      r: "before\n````\n````not-a-close\n<!-- include: b -->\n````\nafter\n",
    },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    const txt = read(outFile(root, "r"));
    assert.doesNotMatch(txt, /SHOULD_NOT_APPEAR/, "the include must stay unexpanded — the fence never actually closed");
    assert.match(txt, /<!-- include: b -->/, "the directive itself must survive verbatim");
  } finally { cleanup(root); }
});
test("build: a real closing fence (bare, or with trailing spaces) still closes — include after it expands normally", () => {
  const root = makeRoot({
    bricks: { inner: "Inner brick content." },
    recipes: {
      bare: "```md\nfenced\n```\n<!-- include: inner -->\n",
      trailingSpace: "```md\nfenced\n```   \n<!-- include: inner -->\n",
    },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    assert.match(read(outFile(root, "bare")), /Inner brick content\./, "a bare closing fence must still close");
    assert.match(read(outFile(root, "trailingSpace")), /Inner brick content\./, "trailing whitespace-only text must still close the fence");
  } finally { cleanup(root); }
});

test("build: an include OUTSIDE any fence in the same file still expands normally", () => {
  const root = makeRoot({
    bricks: { inner: "Inner brick content." },
    recipes: {
      outer: "---\nname: outer\n---\n# outer\n\n```md\n<!-- include: inner -->\n```\n\nReal one: <!-- include: inner -->\n",
    },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    const txt = read(outFile(root, "outer"));
    assert.match(txt, /```md\n<!-- include: inner -->\n```/, "fenced copy stays verbatim");
    assert.match(txt, /Real one: Inner brick content\./, "the include outside the fence still expands");
  } finally { cleanup(root); }
});

test("build: a ~~~ (tilde) fence is treated the same as a ``` (backtick) fence", () => {
  const root = makeRoot({
    bricks: { inner: "Inner brick content." },
    recipes: {
      outer: "---\nname: outer\n---\n# outer\n\n~~~md\n<!-- include: inner -->\n~~~\n",
    },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    const txt = read(outFile(root, "outer"));
    assert.match(txt, /~~~md\n<!-- include: inner -->\n~~~/);
    assert.doesNotMatch(txt, /Inner brick content\./);
  } finally { cleanup(root); }
});

// Explicit non-goal (per the work order): an inline single-backtick code span does NOT suppress
// an include — only block fences (``` / ~~~) do. Guards against scope creep.
test("build: an inline single-backtick code span does NOT suppress an include (out of scope)", () => {
  const root = makeRoot({
    bricks: { inner: "Inner brick content." },
    recipes: {
      outer: "---\nname: outer\n---\n# outer\n\nUse `<!-- include: inner -->` inline.\n",
    },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    const txt = read(outFile(root, "outer"));
    assert.match(txt, /Inner brick content\./, "an inline code span must NOT mask the include (explicit non-goal)");
  } finally { cleanup(root); }
});

// Cross-finding regression (F-01 x F-03): a brick documenting the include syntax inside its OWN
// fenced example must not trip F-01's nested-include gate now that both consult the same mask.
test("build: a brick showing include syntax inside its own fence is NOT a nested-include error", () => {
  const root = makeRoot({
    bricks: {
      inner: "inner content",
      outer: "Outer body.\n\nExample usage:\n```md\n<!-- include: inner -->\n```\n",
    },
    recipes: { demo: "---\nname: demo\n---\n# demo\n\n<!-- include: outer -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    const txt = read(outFile(root, "demo"));
    assert.match(txt, /```md\n<!-- include: inner -->\n```/, "the brick's own fenced example must survive verbatim");
  } finally { cleanup(root); }
});

// ── F-33: bang directive (`include!:`) opts a single include back into expansion INSIDE a
// fence — the escape hatch for factoring duplicated fence content (subagent prompts etc.).
// Plain `include:` keeps the F-03 verbatim-in-fence semantics untouched (regression-pinned). ──
test("F-33: a bang include inside a ``` fence expands, with params/{{k}} substitution", () => {
  const root = makeRoot({
    bricks: { "sub-prompt": "You are the {{role}} subagent. Do the task." },
    recipes: {
      // Both forms in the SAME fence: the bang one expands, the plain one stays verbatim —
      // proving the opt-in is per-directive (at the point of use), never per-fence.
      outer: "---\nname: outer\n---\n# outer\n\n```md\n<!-- include!: sub-prompt | role=reviewer -->\n<!-- include: sub-prompt | role=ignored -->\n```\n",
    },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    const txt = read(outFile(root, "outer"));
    assert.match(txt, /```md\nYou are the reviewer subagent\. Do the task\./, "the bang directive must expand inside the fence, params applied");
    assert.match(txt, /<!-- include: sub-prompt \| role=ignored -->\n```/, "the bang-less directive in the SAME fence must stay verbatim (F-03 regression)");
  } finally { cleanup(root); }
});

test("F-33: a bang include inside a ~~~ (tilde) fence expands the same way", () => {
  const root = makeRoot({
    bricks: { inner: "Inner brick content." },
    recipes: { outer: "---\nname: outer\n---\n# outer\n\n~~~md\n<!-- include!: inner -->\n~~~\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    assert.match(read(outFile(root, "outer")), /~~~md\nInner brick content\.\n~~~/);
  } finally { cleanup(root); }
});

test("F-33: a bang include OUTSIDE any fence behaves exactly like a plain include", () => {
  const root = makeRoot({
    bricks: { "run-dir": "Run {{skill}} now." },
    recipes: {
      bang: "---\nname: bang\n---\n# bang\n\n<!-- include!: run-dir | skill=fix -->\n",
      plain: "---\nname: plain\n---\n# plain\n\n<!-- include: run-dir | skill=fix -->\n",
    },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    // Outside a fence the bang is inert: byte-identical BODY output for both spellings (the
    // banner names each recipe, so compare everything after the banner line).
    const afterBanner = (t) => t.split("\n").filter((l) => !/^<!-- GENERATED /.test(l) && !/^name:/.test(l)).join("\n").replace(/^# \w+/m, "# X");
    assert.equal(afterBanner(read(outFile(root, "bang"))), afterBanner(read(outFile(root, "plain"))));
    assert.match(read(outFile(root, "bang")), /Run fix now\./);
  } finally { cleanup(root); }
});

// Ref-count parity (F-33 x F-03): compose() really inlines a bang-in-fence brick, so includesOf/
// gc MUST count it — otherwise gc would archive a brick a live recipe depends on.
test("F-33: a brick used ONLY via bang-in-fence is ref-counted — gc must NOT report it as orphan", () => {
  const root = makeRoot({
    bricks: { "fenced-dep": "Line 1.\nLine 2." },
    recipes: {
      outer: "---\nname: outer\n---\n# outer\n\n```md\n<!-- include!: fenced-dep -->\n```\n",
    },
  });
  try {
    assert.deepEqual(includesOf(read(recipe(root, "outer"))), ["fenced-dep"], "a bang directive in a fence must be ref-counted");
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map((e) => e.msg).join("; "));
    const g = gc(root); // dry: report only
    assert.deepEqual(g.orphans, [], "gc must see the bang-in-fence consumer and keep the brick");
    assert.equal(has(brick(root, "fenced-dep")), true);
  } finally { cleanup(root); }
});

// Nested-include parity (F-33 x F-01): a bang directive inside a BRICK's fence would really be
// expanded, so it is a REAL nested include → the same build error, nothing written. (A bang-less
// fenced directive in a brick stays allowed — that's documentation, pinned above.)
test("F-33: a bang include inside a fence in a BRICK body is a nested-include build error", () => {
  const root = makeRoot({
    bricks: { inner: "inner content", outer: "Outer.\n```md\n<!-- include!: inner -->\n```\n" },
    recipes: { demo: "---\nname: demo\n---\n# demo\n\n<!-- include: outer -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false, "a bang-in-fence inside a brick must fail the build");
    assert.equal(r.written, 0);
    assert.ok(r.errors.some((e) => e.kind === "build" &&
      e.msg === "build error: [demo] brick outer contains a nested include (inner) — bricks must not include bricks (inline the content or include both from the recipe)"),
      "same nested-include message as the unfenced case");
    assert.equal(has(outFile(root, "demo")), false, "nothing written on the nested-include error");
  } finally { cleanup(root); }
});

// ── F-04: empty frontmatter (`---\n---\n`) is recognized, not treated as absent ─
test("build: recipe with EMPTY frontmatter → banner directly after the closing ---, no blank line", () => {
  const root = makeRoot({ recipes: { emptyfm: "---\n---\n# x\nbody\n" } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    const txt = read(outFile(root, "emptyfm"));
    assert.ok(txt.startsWith("---\n---\n<!-- GENERATED by nbp-skillforge"), `expected banner right after empty fm, got:\n${txt}`);
    // Idempotent: a check right after must not report drift (guards the head-template regression).
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("build: a brick with EMPTY frontmatter has its (empty) fm stripped, not leaked as body text", () => {
  const root = makeRoot({
    bricks: { b: "---\n---\nbrick body content" },
    recipes: { r: "---\nname: r\n---\n# r\n\n<!-- include: b -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    const txt = read(outFile(root, "r"));
    assert.match(txt, /brick body content/);
    // The brick's own empty fm must be recognized (and stripped) — a splitFm regression would
    // leave the whole "---\n---\n..." unsplit and leak the fence markers into the composed body.
    assert.doesNotMatch(txt, /---\s*---\s*brick body content/, "brick's own empty fm must not leak into the composed body");
  } finally { cleanup(root); }
});

// ── C1 regression: a closing fence must be followed by a newline or EOF, never swallow the
// body's own leading `---` when trailing text sits on the same line (data-loss repro: f04repro) ─
test("splitFm: `---literal…` right after the opening fence is NOT a closing fence — no fm recognized, body untouched", () => {
  const { fm, body } = splitFm("---\n---literal body line\n");
  // The second `---` is immediately followed by more text on the SAME line (no `\n`/EOF right
  // after it), so it must NOT count as a valid closing fence — the whole text has no recognized
  // frontmatter block at all (distinct from the genuine-empty-fm case below): fm is null and body
  // is the raw text, byte-for-byte, including the leading `---` that the old regex used to eat.
  assert.equal(fm, null);
  assert.equal(body, "---\n---literal body line\n");
});
test("splitFm: the genuine empty-fm case (`---\\n---\\n...`) is still recognized (not a regression)", () => {
  const { fm, body } = splitFm("---\n---\n#x");
  assert.equal(fm, "");
  assert.equal(body, "#x");
});
test("splitFm: a normal frontmatter block still splits fm/body correctly", () => {
  const { fm, body } = splitFm("---\nname: a\ndescription: d\n---\n# a\nbody\n");
  assert.equal(fm, "name: a\ndescription: d");
  assert.equal(body, "# a\nbody\n");
});
test("splitFm: frontmatter with no trailing body (EOF right after the closing fence) still splits", () => {
  assert.deepEqual(splitFm("---\nname: a\n---"), { fm: "name: a", body: "" });
  assert.deepEqual(splitFm("---\nname: a\n---\n"), { fm: "name: a", body: "" });
});
test("build: a recipe body starting with `---literal…` right after an empty-looking fm is preserved verbatim (f04repro)", () => {
  const root = makeRoot({ recipes: { r: "---\n---literal body line\n" } });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    const txt = read(outFile(root, "r"));
    // No frontmatter is recognized at all — the whole raw text is the body, banner prepended.
    assert.match(txt, /GENERATED by nbp-skillforge[\s\S]*-->\n---\n---literal body line/,
      "the body's leading `---` must survive the round-trip, not be swallowed as a bogus closing fence");
  } finally { cleanup(root); }
});

// ── F-05: ref-count (includesOf) only scans the BODY, matching what compose() expands ─
test("includesOf: an include directive inside the recipe's own frontmatter is not ref-counted", () => {
  const fmOnly = "---\nname: a\ndescription: d\n<!-- include: b -->\n---\n# a\nbody, no include here.\n";
  assert.deepEqual(includesOf(fmOnly), [], "an fm-only directive must not be counted");
  const bodyOnly = "---\nname: a\ndescription: d\n---\n# a\n<!-- include: b -->\n";
  assert.deepEqual(includesOf(bodyOnly), ["b"], "a body directive must still be counted");
});

test("includesOf: CRLF recipe text is normalized before splitting fm/body", () => {
  const fmOnly = "---\r\nname: a\r\ndescription: d\r\n<!-- include: b -->\r\n---\r\n# a\r\nbody.\r\n";
  assert.deepEqual(includesOf(fmOnly), [], "CRLF must not defeat the fm/body split");
});

// ── F-06: an unused include param is a non-blocking warning ─────────────────────
test("build: an unused include param produces a warning, exit 0, file still written", () => {
  const root = makeRoot({
    bricks: { "run-dir": "Run: static text, no placeholders" },
    recipes: { demo: "---\nname: demo\n---\n# demo\n\n<!-- include: run-dir | skil=typo; naousado=abc -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.equal(r.written, 1);
    assert.ok(r.warnings.some((w) =>
      w === "warning: [demo] include run-dir: unused param(s): skil, naousado"));
    assert.equal(has(outFile(root, "demo")), true);
  } finally { cleanup(root); }
});

test("build: no warning when every param is consumed by the brick", () => {
  const root = makeRoot({
    bricks: { b: "Run {{skill}}." },
    recipes: { demo: "---\nname: demo\n---\n# demo\n\n<!-- include: b | skill=fix -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.deepEqual(r.warnings, []);
  } finally { cleanup(root); }
});

test("build: a param referenced twice ({{k}} used twice in the brick) is not flagged unused", () => {
  const root = makeRoot({
    bricks: { b: "{{skill}} ... {{skill}}" },
    recipes: { demo: "---\nname: demo\n---\n# demo\n\n<!-- include: b | skill=fix -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.deepEqual(r.warnings, []);
  } finally { cleanup(root); }
});

test("build: two separate includes with unused params each get their own warning", () => {
  const root = makeRoot({
    bricks: { a: "static a", b: "static b" },
    recipes: { demo: "---\nname: demo\n---\n# demo\n\n<!-- include: a | x=1 -->\n<!-- include: b | y=2 -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.equal(r.warnings.length, 2);
    assert.ok(r.warnings.some((w) => w.includes("include a: unused param(s): x")));
    assert.ok(r.warnings.some((w) => w.includes("include b: unused param(s): y")));
  } finally { cleanup(root); }
});

// ── F-23: {{param}} key charset is [\w-] — a key outside that charset is a silent no-op ────
test("build: a {{param}} key with a non-[\\w-] char (a dot) is left VERBATIM, not substituted, no build error", () => {
  const root = makeRoot({
    bricks: { b: "Value: {{my.key}}." },
    recipes: { demo: "---\nname: demo\n---\n# demo\n\n<!-- include: b | my.key=hello -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; ")); // no build error — SPEC's "Known limitations" documents this as a silent no-op
    const txt = read(outFile(root, "demo"));
    assert.match(txt, /Value: \{\{my\.key\}\}\./); // literal placeholder survives unexpanded
    // the un-recognized key is also (correctly) reported as "unused", since the regex never
    // matched it to mark it consumed — this is the one observable signal an author gets.
    assert.ok(r.warnings.some((w) => w.includes("unused param(s): my.key")));
  } finally { cleanup(root); }
});

// ── F-31 Fase 1: forge-role marker detection (fm-scoped by contract) ─────────────────────────
test("hasForgeRole: detects the namespaced value in a split fm block; ignores other namespaces", () => {
  assert.equal(hasForgeRole(`name: forge-onboard\nforge-role: ${FORGE_ROLE_VALUE}`), true);
  assert.equal(hasForgeRole(`forge-role: "${FORGE_ROLE_VALUE}"`), true, "quoted value accepted");
  assert.equal(hasForgeRole(`forge-role: '${FORGE_ROLE_VALUE}'`), true, "single-quoted value accepted");
  assert.equal(hasForgeRole("forge-role: someone-else/tool"), false, "foreign namespace ignored");
  assert.equal(hasForgeRole(`x-forge-role: ${FORGE_ROLE_VALUE}`), false, "line-anchored: prefixed key ignored");
  assert.equal(hasForgeRole(""), false, "empty fm block");
  assert.equal(hasForgeRole(null), false, "no fm at all (splitFm returns null)");
});

test("hasForgeRole: a forge-role-shaped line in a BODY never reaches it via splitFm", () => {
  // The contract is fm-scoped: callers pass splitFm(...).fm. A body that merely documents the
  // marker (even outside a fence) is structurally out of reach — prove the composition.
  const txt = `---\nname: doc\ndescription: documents the marker.\n---\nExample marker:\n\nforge-role: ${FORGE_ROLE_VALUE}\n`;
  const { fm } = splitFm(txt);
  assert.equal(hasForgeRole(fm), false, "marker in body only → fm block clean → no detection");
});

test("hasForgeRole: mismatched quotes are rejected (backreference); CR-tolerant", () => {
  assert.equal(hasForgeRole(`forge-role: "${FORGE_ROLE_VALUE}`), false, "opening quote without closing rejected");
  assert.equal(hasForgeRole(`forge-role: ${FORGE_ROLE_VALUE}"`), false, "closing quote without opening rejected");
  assert.equal(hasForgeRole(`forge-role: "${FORGE_ROLE_VALUE}'`), false, "mixed quotes rejected");
  assert.equal(hasForgeRole(`forge-role: ${FORGE_ROLE_VALUE}\r`), true, "stray CR (un-normalized CRLF split) tolerated");
});

// ── F-31: the exported global INCLUDE regex must never let a consumer's stray .test()/.exec()
// corrupt ref-counting — matchAll clones the regex but INHERITS a dirty lastIndex ─────────────
test("includesOf: immune to a dirty lastIndex on the exported INCLUDE regex", async () => {
  const { INCLUDE } = await import("../src/compose.mjs");
  const text = "---\nname: x\n---\n<!-- include: first -->\nmid\n<!-- include: second -->\n";
  INCLUDE.lastIndex = 30; // simulate an external consumer that ran .exec()/.test() and stopped midway
  assert.deepEqual(includesOf(text), ["first", "second"], "ref-count must see ALL includes despite dirty state");
});

// ═══ F-26: multi-out (`out` as string | string[]) ═══════════════════════════════════════════
test("F-26 config: out as an ARRAY no longer crashes — builds to every destination", () => {
  const root = makeRoot({
    config: { out: ["out", "second-out"] },
    bricks: { b: "shared body" },
    recipes: { s: "---\nname: s\n---\n# s\n\n<!-- include: b -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, true, r.errors?.map(e => e.msg).join("; "));
    assert.equal(r.written, 2, "one write per destination");
    assert.equal(r.destinations, 2);
    const a = read(join(root, "out", "s.md"));
    const b = read(join(root, "second-out", "s.md"));
    assert.equal(a, b, "both destinations carry byte-identical content");
    assert.deepEqual(r.plan, [
      { name: "s", out: "out", status: "create" },
      { name: "s", out: "second-out", status: "create" },
    ]);
  } finally { cleanup(root); }
});

test("F-26 config: invalid out shapes are clean user-facing errors (the old TypeError crash)", () => {
  for (const bad of [[], [""], ["a", 42], "", 7, { x: 1 }]) {
    const root = makeRoot({ config: { out: bad } });
    try {
      assert.throws(() => run({ root, mode: "build" }),
        (e) => e.userFacing === true && /"out" must be a non-empty string or a non-empty array/.test(e.message),
        `expected a clean userFacing error for out=${JSON.stringify(bad)}`);
    } finally { cleanup(root); }
  }
});

test("F-26 config: an exact-duplicate out entry is rejected with a precise message", () => {
  const root = makeRoot({ config: { out: ["x", "x"] } });
  try {
    assert.throws(() => run({ root, mode: "build" }),
      (e) => e.userFacing === true && /duplicate "out" entry: x/.test(e.message));
  } finally { cleanup(root); }
});

test("F-26 config: two out entries that only differ by nesting are a config error", () => {
  const root = makeRoot({
    config: { out: ["out", "out/nested"] },
    recipes: { s: "---\nname: s\n---\n# s\nbody\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.ok, false);
    assert.ok(r.errors.some((e) => e.kind === "config" && /must not be inside or equal to/.test(e.msg)));
  } finally { cleanup(root); }
});

test("F-26 build: skip-if-unchanged is PER DESTINATION (stale out[1] alone rewrites only out[1])", () => {
  const root = makeRoot({
    config: { out: ["out", "second-out"] },
    bricks: { b: "body" },
    recipes: { s: "---\nname: s\n---\n# s\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    write(join(root, "second-out", "s.md"), "hand-tampered\n"); // out[0] stays correct
    const r = run({ root, mode: "build" });
    assert.equal(r.written, 1, "only the stale destination is rewritten");
    assert.equal(r.unchanged, 1);
    assert.equal(r.plan.find((p) => p.out === "out").status, "same");
    assert.equal(r.plan.find((p) => p.out === "second-out").status, "change");
  } finally { cleanup(root); }
});

test("F-26 check: drift in ANY destination fails, naming exactly the drifted one", () => {
  const root = makeRoot({
    config: { out: ["out", "second-out"] },
    bricks: { b: "body" },
    recipes: { s: "---\nname: s\n---\n# s\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    write(join(root, "second-out", "s.md"), "tampered\n");
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, false);
    assert.equal(r.drift, 1, "exactly one drifted (name × out) pair");
    assert.ok(r.errors.some((e) => e.kind === "drift" && e.msg.includes("second-out/s.md")), "message names the drifted destination");
    assert.ok(!r.errors.some((e) => e.msg.includes("out/s.md is out of sync") && !e.msg.includes("second-out")), "the in-sync destination is not reported");
  } finally { cleanup(root); }
});

test("F-26 enforceGenerated: an orphan in out[1] alone is still reported (per-destination scan)", () => {
  const root = makeRoot({
    config: { out: ["out", "second-out"], enforceGenerated: true },
    bricks: { b: "body" },
    recipes: { s: "---\nname: s\n---\n# s\n\n<!-- include: b -->\n" },
  });
  try {
    run({ root, mode: "build" });
    write(join(root, "second-out", "rogue.md"), "hand-made\n");
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, false);
    assert.equal(r.orphans, 1);
    assert.ok(r.errors.some((e) => e.kind === "orphan" && e.msg.includes("second-out/rogue.md")));
  } finally { cleanup(root); }
});

test("F-26 retrocompat: a single-string out keeps destinations=1 and the exact plan/counters", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { s: "---\nname: s\n---\n# s\n\n<!-- include: b -->\n" },
  });
  try {
    const r = run({ root, mode: "build" });
    assert.equal(r.destinations, 1);
    assert.equal(r.written, 1);
    assert.equal(r.count, 1);
  } finally { cleanup(root); }
});

// ═══ Fable bug-hunt regression fixes (session 2026-07-06, post-0.7.0) ═══════════════════════
test("Fable B5: a lone CR (partially converted CR-mac file) converges — build heals, check green", () => {
  const root = makeRoot({
    recipes: { s: "---\nname: s\ndescription: d.\n---\n# s\nline one\r\rmore\nend\n" },
  });
  try {
    assert.equal(run({ root, mode: "build" }).ok, true);
    const chk1 = run({ root, mode: "check" });
    assert.equal(chk1.ok, true, chk1.errors?.map((e) => e.msg).join("; "));
    // idempotent: a second build writes nothing, check still green (the old bug looped forever)
    const b2 = run({ root, mode: "build" });
    assert.equal(b2.written, 0, "second build is a no-op");
    assert.equal(run({ root, mode: "check" }).ok, true);
    assert.equal(readRaw(outFile(root, "s")).includes(0x0d), false, "no CR bytes in output");
  } finally { cleanup(root); }
});

test("Fable B9b: a directory squatting out/<name>.md is a structured build error, not EISDIR", () => {
  const root = makeRoot({ recipes: { dirsquat: "---\nname: dirsquat\ndescription: d.\n---\nbody\n" } });
  mkdirSync(join(root, "out", "dirsquat.md"), { recursive: true });
  try {
    const r = run({ root, mode: "check" });
    assert.equal(r.ok, false);
    assert.ok(r.errors.some((e) => e.kind === "build" && /cannot read destination/.test(e.msg)), "clean structured error");
  } finally { cleanup(root); }
});
