// onboard (F-31 Fases 2+3): discovery/exclusion, pre-scan, snapshot, verbatim apply, fidelity
// gate, report, auto-enforce. Every test verifies BY EXECUTION on a throwaway root.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { discover, preScan, normalizeForGate, snapshot, onboard, installSkill } from "../src/onboard.mjs";
import { run, loadConfig, FORGE_ROLE_VALUE } from "../src/compose.mjs";
import { gc } from "../src/lifecycle.mjs";
import { createHash } from "node:crypto";
import { makeRoot, write, read, readRaw, has, recipe, outFile, cleanup } from "./helpers.mjs";

const TS = "2026-07-06T00-00-00-000"; // injected timestamp — onboard.mjs never reads the clock

// One hostile-mix fixture reused by several tests.
const mixRoot = () => {
  const root = makeRoot({
    bricks: { b: "brick body" },
    recipes: { governed: "---\nname: governed\ndescription: d.\n---\n# governed\n\n<!-- include: b -->\n" },
  });
  run({ root, mode: "build" }); // `governed` now sits generated in out/
  write(join(root, "out", "hand-made.md"), "---\nname: hand-made\ndescription: Hand-written skill.\n---\n# hand-made\n\nDo the thing.\n");
  write(join(root, "out", "plain-cmd.md"), "# plain command\n\nNo frontmatter at all.\n");
  write(join(root, "out", "tool.md"), `---\nname: tool\ndescription: t.\nforge-role: ${FORGE_ROLE_VALUE}\n---\n# tool\nbody\n`);
  write(join(root, "out", "Bad_Name.md"), "---\nname: Bad_Name\ndescription: d.\n---\n# bad\nbody\n");
  write(join(root, "out", "governed.md"), read(join(root, "out", "governed.md"))); // unchanged, still generated
  write(join(root, "out", "has-include.md"), "# x\n\n<!-- include: run-dir -->\n");
  write(join(root, "out", "fenced-include.md"), "# y\n\n```\n<!-- include: run-dir -->\n```\n");
  writeFileSync(join(root, "out", "binary.md"), Buffer.from([0xff, 0xfe, 0x00, 0x41, 0x80, 0x81]));
  mkdirSync(join(root, "out", "sub"), { recursive: true });
  write(join(root, "out", "sub", "nested.md"), "# nested\n");
  return root;
};

test("discover: classifies the hostile mix correctly, every file gets a disposition", () => {
  const root = mixRoot();
  try {
    const { entries } = discover(root, loadConfig(root));
    const by = Object.fromEntries(entries.map((e) => [e.file.replace(/\\/g, "/").split("/").pop(), e.status]));
    assert.equal(by["hand-made.md"], "eligible");
    assert.equal(by["plain-cmd.md"], "eligible", "a no-frontmatter command is eligible (no name gate)");
    assert.equal(by["fenced-include.md"], "eligible", "an include inside a fence is NOT a landmine (engine parity)");
    assert.equal(by["governed.md"], "excluded-generated", "banner detected AFTER splitFm (fm'd file)");
    assert.equal(by["tool.md"], "excluded-forge-role");
    assert.equal(by["Bad_Name.md"], "skip-nonconformant");
    assert.equal(by["has-include.md"], "skip-include-like");
    assert.equal(by["binary.md"], "skip-non-utf8");
    assert.equal(by["nested.md"], "skip-nested");
    const bad = entries.find((e) => e.status === "skip-nonconformant");
    assert.match(bad.proposal ?? "", /bad-name/, "a conformant rename is proposed, never applied");
  } finally { cleanup(root); }
});

test("discover: a PRE-RENAME banner (nbp-forge) is still recognized as generated", () => {
  const root = makeRoot({});
  write(join(root, "out", "old-gen.md"), "<!-- GENERATED by nbp-forge from recipes/old-gen.md — do not edit here. -->\n# old\nbody\n");
  try {
    const { entries } = discover(root, loadConfig(root));
    assert.equal(entries[0].status, "excluded-generated");
  } finally { cleanup(root); }
});

test("preScan: BOM detected+stripped; placeholders recorded; include-like honors fences", () => {
  // ﻿ escape (not a literal BOM char) — editors/shells silently strip the literal.
  const bom = preScan(Buffer.from("﻿---\nname: x\n---\nbody {{param}}\n", "utf8"));
  assert.equal(bom.bom, true);
  assert.match(bom.text, /^---/, "BOM stripped so splitFm's anchor works");
  assert.deepEqual(bom.placeholders, ["{{param}}"]);
  const inv = preScan(Buffer.from([0xc3, 0x28])); // invalid UTF-8 sequence
  assert.equal(inv.utf8, false);
});

test("normalizeForGate: original ≡ its verbatim build (banner+CRLF+EOF-ws); real edits differ", () => {
  const original = "---\r\nname: s\r\ndescription: d.\r\n---\r\n# s\r\n\r\nbody line\r\n\r\n";
  const rebuilt = "---\nname: s\ndescription: d.\n---\n<!-- GENERATED by nbp-skillforge from recipes/s.md — do not edit here; edit the recipe/brick and run `npx nbp-skillforge build`. -->\n# s\n\nbody line\n";
  assert.equal(normalizeForGate(original), normalizeForGate(rebuilt), "the three legal axes normalize away");
  assert.notEqual(normalizeForGate(original), normalizeForGate(rebuilt.replace("body line", "body line EDITED")), "a real divergence is never masked");
});

test("onboard (dry): default is a report-only run — the tree is byte-identical after", () => {
  const root = mixRoot();
  try {
    const before = new Map(readdirSync(join(root, "out"), { recursive: true }).map((f) => {
      const p = join(root, "out", String(f));
      return [String(f), existsSync(p) && !String(f).includes("sub") ? null : null];
    }));
    const snap = (dir) => readdirSync(dir, { recursive: true }).map(String).sort().join("|");
    const treeBefore = snap(root);
    const r = onboard({ root, ts: TS }); // no apply
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.applied, false);
    assert.equal(snap(root), treeBefore, "dry-run creates/modifies NOTHING");
    assert.match(r.msg, /scanned out/, "the scanned root is announced");
    assert.match(r.msg, /--from <dir>/, "the user is told how to point the scan elsewhere");
  } finally { cleanup(root); }
});

test("onboard --apply: E2E — snapshot faithful, recipes created, gate zero, check green, report covers all", () => {
  const root = mixRoot();
  try {
    const originalCrlf = "---\r\nname: crlf-skill\r\ndescription: d.\r\n---\r\n# crlf\r\n\r\nCRLF body\r\n";
    writeFileSync(join(root, "out", "crlf-skill.md"), originalCrlf);
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, true, r.msg);
    // (1) backup byte-faithful (CRLF preserved)
    const bak = join(root, "_onboard-backup-" + TS);
    assert.equal(readFileSync(join(bak, "crlf-skill.md"), "latin1"), Buffer.from(originalCrlf).toString("latin1"), "backup preserves exact original bytes");
    // (2) recipes exist + gate passed for every migrated skill
    for (const s of ["hand-made", "plain-cmd", "crlf-skill", "fenced-include"]) {
      assert.equal(has(recipe(root, s)), true, `recipe created: ${s}`);
      assert.equal(r.gate.find((g) => g.skill === s)?.pass, true, `gate zero for ${s}`);
    }
    // rebuilt output is LF-only even though the source was CRLF
    assert.equal(readRaw(outFile(root, "crlf-skill")).includes(0x0d), false, "out is LF");
    // (3) drift-gate green afterward
    assert.equal(run({ root, mode: "check" }).ok, true, "forge check green after onboarding");
    // (4) report covers 100% of the scanned files
    const report = read(join(bak, "onboard-report.md"));
    for (const f of ["hand-made.md", "governed.md", "tool.md", "Bad_Name.md", "has-include.md", "binary.md", "nested.md"])
      assert.ok(report.includes(f), `report mentions ${f}`);
    // skips present → enforceGenerated must NOT auto-enable
    assert.equal(r.enforced, false);
    assert.equal(loadConfig(root).enforceGenerated, false);
    assert.match(report, /enforceGenerated stays OFF/);
    // (5) skipped/excluded originals untouched
    assert.match(read(join(root, "out", "Bad_Name.md")), /# bad/, "skipped file untouched");
  } finally { cleanup(root); }
});

test("onboard --apply: re-run is a clean no-op (everything already governed)", () => {
  const root = makeRoot({});
  write(join(root, "out", "only.md"), "---\nname: only\ndescription: d.\n---\n# only\nbody\n");
  try {
    const r1 = onboard({ root, ts: TS, apply: true });
    assert.equal(r1.ok, true, r1.msg);
    const r2 = onboard({ root, ts: TS + "-2", apply: true });
    assert.equal(r2.ok, true, r2.msg);
    assert.equal(r2.entries.every((e) => e.status.startsWith("excluded-")), true, "everything now excluded-generated/has-recipe");
    assert.equal(has(join(root, "_onboard-backup-" + TS + "-2")), false, "no second backup for a no-op run");
  } finally { cleanup(root); }
});

test("onboard --apply: 100% migrated → enforceGenerated auto-enables and is announced", () => {
  const root = makeRoot({});
  write(join(root, "out", "clean-one.md"), "---\nname: clean-one\ndescription: d.\n---\n# one\nbody\n");
  write(join(root, "out", "clean-two.md"), "# two — plain command\nbody\n");
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.enforced, true, "auto-enabled on the 100% condition");
    assert.equal(loadConfig(root).enforceGenerated, true, "persisted to forge.config.json");
    assert.match(r.msg, /enforceGenerated: ON/);
    assert.equal(run({ root, mode: "check" }).ok, true, "check green under the new strict mode");
  } finally { cleanup(root); }
});

test("onboard --apply: collision (case-fold) with an existing recipe → skip, original intact", () => {
  const root = makeRoot({ recipes: { taken: "---\nname: taken\ndescription: d.\n---\n# taken\nbody\n" } });
  run({ root, mode: "build" });
  write(join(root, "out", "TAKEN.md"), "---\nname: TAKEN\ndescription: other.\n---\n# other\nbody\n");
  try {
    const r = onboard({ root, ts: TS, apply: true });
    const entry = r.entries.find((e) => /TAKEN/i.test(e.file) && e.status !== "excluded-generated");
    // On a case-insensitive FS this folds into the existing recipe (excluded-has-recipe);
    // either way it must never overwrite the existing recipe.
    assert.ok(["excluded-has-recipe", "skip-collision", "skip-nonconformant"].includes(entry.status), entry.status);
    assert.match(read(recipe(root, "taken")), /# taken/, "existing recipe never clobbered");
  } finally { cleanup(root); }
});

test("snapshot: refuses an existing backup dir and a backup dir inside a role dir", () => {
  const root = makeRoot({});
  const cfg = loadConfig(root);
  const bak = join(root, "_bak");
  mkdirSync(bak);
  try {
    assert.throws(() => snapshot(root, [], bak, cfg), /already exists/);
    assert.throws(() => snapshot(root, [], join(root, "bricks", "b"), cfg), /outside every role dir/);
  } finally { cleanup(root); }
});

test("onboard: --from overrides the discovery root (and is announced)", () => {
  const root = makeRoot({});
  write(join(root, "elsewhere", "ext.md"), "---\nname: ext\ndescription: d.\n---\n# ext\nbody\n");
  try {
    const r = onboard({ root, ts: TS, from: "elsewhere" });
    assert.equal(r.entries.length, 1);
    assert.equal(r.entries[0].status, "eligible");
    assert.match(r.msg, /scanned elsewhere/);
  } finally { cleanup(root); }
});

test("onboard: --from pointing inside bricks/recipes/archive is refused (self-ingestion guard)", () => {
  const root = makeRoot({ bricks: { b: "brick body" } });
  try {
    for (const bad of ["bricks", "recipes", "_archive"]) {
      const r = onboard({ root, ts: TS, from: bad });
      assert.equal(r.ok, false, `--from ${bad} must be refused`);
      assert.match(r.msg, /must not point inside/);
    }
  } finally { cleanup(root); }
});

// ═══ Dual-review regression fixes (codex + agy, adjudicated by execution) ═══════════════════
test("review-fix: pre-existing drift in a governed skill ABORTS apply (no un-snapshotted heal)", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { governed: "---\nname: governed\ndescription: d.\n---\n# governed\n\n<!-- include: b -->\n" },
  });
  run({ root, mode: "build" });
  write(join(root, "out", "governed.md"), read(join(root, "out", "governed.md")) + "HAND EDIT\n"); // drift
  write(join(root, "out", "newbie.md"), "---\nname: newbie\ndescription: d.\n---\n# new\nbody\n");
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, false);
    assert.match(r.msg, /drifted from their recipes/);
    assert.match(read(join(root, "out", "governed.md")), /HAND EDIT/, "the hand-edit survives (nothing healed)");
    assert.equal(has(recipe(root, "newbie")), false, "nothing was imported");
    assert.equal(has(join(root, "_onboard-backup-" + TS)), false, "no backup dir for an aborted pre-flight");
  } finally { cleanup(root); }
});

test("review-fix: fm name ≠ basename → skip-name-mismatch (no recipe under a foreign name)", () => {
  const root = makeRoot({});
  write(join(root, "out", "legacy.md"), "---\nname: clean\ndescription: d.\n---\n# legacy\nbody\n");
  try {
    const r = onboard({ root, ts: TS, apply: true });
    const e = r.entries.find((x) => /legacy/.test(x.file));
    assert.equal(e.status, "skip-name-mismatch");
    assert.equal(has(recipe(root, "clean")), false, "no recipe minted under the fm name");
    assert.equal(has(recipe(root, "legacy")), false);
    assert.match(read(join(root, "out", "legacy.md")), /# legacy/, "original untouched");
  } finally { cleanup(root); }
});

test("review-fix: --from with a name whose out/<name>.md already exists → skip-collision", () => {
  const root = makeRoot({});
  write(join(root, "out", "foo.md"), "# hand-made foo living in out — must survive\n");
  write(join(root, "elsewhere", "foo.md"), "---\nname: foo\ndescription: d.\n---\n# external foo\n");
  try {
    const r = onboard({ root, ts: TS, apply: true, from: "elsewhere" });
    const e = r.entries.find((x) => /foo/.test(x.file));
    assert.equal(e.status, "skip-collision");
    assert.match(read(join(root, "out", "foo.md")), /must survive/, "the un-snapshotted target is never overwritten");
  } finally { cleanup(root); }
});

test("review-fix: BOM + frontmatter file imports with the fm intact (engine strips the BOM)", () => {
  const root = makeRoot({});
  mkdirSync(join(root, "out"), { recursive: true });
  writeFileSync(join(root, "out", "bommed.md"), Buffer.concat([
    Buffer.from([0xef, 0xbb, 0xbf]),
    Buffer.from("---\nname: bommed\ndescription: d.\n---\n# bommed\nbody\n"),
  ]));
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, true, r.msg);
    assert.match(read(recipe(root, "bommed")), /^---\nname: bommed/, "fm recognized (BOM stripped by import)");
    assert.equal(r.gate.find((g) => g.skill === "bommed")?.pass, true, "fidelity gate passes");
  } finally { cleanup(root); }
});

test("review-fix: absolute --from is refused with a clear message", () => {
  const root = makeRoot({});
  try {
    const r = onboard({ root, ts: TS, from: join(root, "somewhere") });
    assert.equal(r.ok, false);
    assert.match(r.msg, /relative to the project root/);
  } finally { cleanup(root); }
});

test("review-fix: symlink and unreadable entries get explicit dispositions (no crash)", { skip: process.platform === "win32" ? false : false }, () => {
  const root = makeRoot({});
  write(join(root, "out", "real.md"), "---\nname: real\ndescription: d.\n---\n# real\nbody\n");
  try {
    let linked = false;
    try { // symlink creation may need privileges on Windows — the disposition test is best-effort there
      const { symlinkSync } = require("node:fs");
    } catch {}
    const r = onboard({ root, ts: TS });
    assert.equal(r.ok, true, "scan never crashes");
    assert.equal(r.entries.find((e) => /real/.test(e.file)).status, "eligible");
  } finally { cleanup(root); }
});

test("review-fix: auto-enforce blocked by an un-governed file in a SECOND out dir", () => {
  const root = makeRoot({ config: { out: ["out", "second-out"] } });
  write(join(root, "out", "only.md"), "---\nname: only\ndescription: d.\n---\n# only\nbody\n");
  write(join(root, "second-out", "stray.md"), "# hand-made stray in out[1]\n");
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.enforced, false, "stray in out[1] blocks the auto-enable");
    assert.equal(loadConfig(root).enforceGenerated, false);
    assert.equal(run({ root, mode: "check" }).ok, true, "and check stays green (no orphan surprise)");
  } finally { cleanup(root); }
});

test("review-fix: banner AFTER a stray blank line is still detected as generated", () => {
  const root = makeRoot({});
  write(join(root, "out", "blanky.md"), "---\nname: blanky\ndescription: d.\n---\n\n<!-- GENERATED by nbp-skillforge from recipes/blanky.md — do not edit here. -->\n# blanky\n");
  try {
    const r = onboard({ root, ts: TS });
    assert.equal(r.entries.find((e) => /blanky/.test(e.file)).status, "excluded-generated");
  } finally { cleanup(root); }
});

test("review-fix: an import failure mid-batch rolls back every recipe the run created", () => {
  const root = makeRoot({});
  write(join(root, "out", "aaa.md"), "---\nname: aaa\ndescription: d.\n---\n# aaa\nbody\n");
  write(join(root, "out", "zzz.md"), "---\nname: zzz\ndescription: d.\n---\n# zzz\nbody\n");
  // sabotage: make the SECOND import fail by pre-creating recipes/zzz.md as a DIRECTORY
  mkdirSync(join(root, "recipes", "zzz.md"), { recursive: true });
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, false);
    assert.match(r.msg, /rolled back/);
    assert.equal(has(recipe(root, "aaa")), false, "aaa's recipe rolled back (atomic batch)");
    assert.match(read(join(root, "out", "aaa.md")), /# aaa/, "original untouched");
  } finally { cleanup(root); }
});

// ═══ F-31 Fase 4: mechanical factoring (--factor) — byte-identical only, self-reverting ═════
const SHARED = "### Working folder\n\nAt the start, create the run folder.\nWrite progress there as you go.\nNever skip this step.";

test("factor: an identical ### section in 2 skills → 1 brick, 2 includes, gate zero, check green", () => {
  const root = makeRoot({});
  write(join(root, "out", "alpha.md"), `---\nname: alpha\ndescription: d.\n---\n# alpha\n\n${SHARED}\n\n## Ending\n\nAlpha-only ending.\n`);
  write(join(root, "out", "beta.md"), `---\nname: beta\ndescription: d.\n---\n# beta\n\n${SHARED}\n\n## Ending\n\nBeta-only ending.\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.factoring.factored.length, 1, "exactly one shared brick");
    const brick = r.factoring.factored[0];
    assert.match(brick.brick, /^onboarded\/working-folder-[0-9a-f]{8}$/, "deterministic slug-hash name");
    assert.deepEqual(brick.usedBy.sort(), ["alpha", "beta"]);
    assert.equal(r.factoring.kept.length, 0);
    // recipes now carry the include; outputs still reproduce the ORIGINAL bytes (gate proven):
    assert.match(read(recipe(root, "alpha")), /<!-- include: onboarded\/working-folder-/);
    assert.match(read(outFile(root, "alpha")), /Never skip this step\./);
    assert.equal(run({ root, mode: "check" }).ok, true);
    // determinism: same content → same brick name on a fresh identical root
    const root2 = makeRoot({});
    write(join(root2, "out", "alpha.md"), `---\nname: alpha\ndescription: d.\n---\n# alpha\n\n${SHARED}\n\n## Ending\n\nAlpha-only ending.\n`);
    write(join(root2, "out", "beta.md"), `---\nname: beta\ndescription: d.\n---\n# beta\n\n${SHARED}\n\n## Ending\n\nBeta-only ending.\n`);
    const r2 = onboard({ root: root2, ts: TS, apply: true, factor: true });
    assert.equal(r2.factoring.factored[0].brick, brick.brick, "same input → same brick name");
    cleanup(root2);
  } finally { cleanup(root); }
});

test("factor: a block containing a literal {{param}} NEVER becomes a brick", () => {
  const root = makeRoot({});
  const P = "### Params\n\nUse {{skill}} here.\nAnd more lines.\nAnd more.";
  write(join(root, "out", "one.md"), `---\nname: one\ndescription: d.\n---\n# one\n\n${P}\n`);
  write(join(root, "out", "two.md"), `---\nname: two\ndescription: d.\n---\n# two\n\n${P}\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.factoring.factored.length, 0, "placeholder block stays in the residual body");
    assert.match(read(recipe(root, "one")), /\{\{skill\}\}/, "verbatim in the recipe");
    assert.equal(run({ root, mode: "check" }).ok, true, "and the build stays green");
  } finally { cleanup(root); }
});

test("factor: near-identical blocks (1 char apart) do NOT factor (byte-identical only)", () => {
  const root = makeRoot({});
  write(join(root, "out", "one.md"), `---\nname: one\ndescription: d.\n---\n# one\n\n### Step\n\nDo the thing.\nCarefully now.\nAlways.\n`);
  write(join(root, "out", "two.md"), `---\nname: two\ndescription: d.\n---\n# two\n\n### Step\n\nDo the thing.\nCarefully now!\nAlways.\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.factoring.factored.length, 0, "near-identical is Fase B's job, never automatic");
  } finally { cleanup(root); }
});

test("factor: a block shared only inside a code fence does not factor (heading masked)", () => {
  const root = makeRoot({});
  const F = "```\n### Fenced heading\nline\nline\nline\n```";
  write(join(root, "out", "one.md"), `---\nname: one\ndescription: d.\n---\n# one\n\nIntro one.\n\n${F}\n`);
  write(join(root, "out", "two.md"), `---\nname: two\ndescription: d.\n---\n# two\n\nIntro two.\n\n${F}\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    // the fenced pseudo-heading never segments a block of its own; the preamble blocks differ
    // (Intro one vs two), so nothing is byte-identical across skills.
    assert.equal(r.factoring.factored.length, 0);
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("factor: blocks shared by 3 skills ref-count 3; gc never flags the onboarded brick", () => {
  const root = makeRoot({});
  for (const n of ["um", "dois", "tres"])
    write(join(root, "out", `${n}.md`), `---\nname: ${n}\ndescription: d.\n---\n# ${n}\n\n${SHARED}\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.factoring.factored[0].usedBy.length, 3);
    const g = gc(root, {});
    assert.equal(g.orphans.length, 0, "a consumed onboarded brick is never an orphan");
  } finally { cleanup(root); }
});

// ═══ Fase 4 dual-review regression fixes ════════════════════════════════════════════════════
test("factor review-fix: the same bytes embedded in ANOTHER section never get factored in-place", () => {
  const root = makeRoot({});
  const CORE = "### Shared\n\nline one of shared.\nline two of shared.\nline three.";
  // skill 'host' contains CORE embedded INSIDE a bigger section (extra line before next heading)
  write(join(root, "out", "host.md"), `---\nname: host\ndescription: d.\n---\n# host\n\n${CORE}\nhost-extra line in the SAME section.\n\n## Tail\n\ntail.\n`);
  write(join(root, "out", "aaa.md"), `---\nname: aaa\ndescription: d.\n---\n# aaa\n\n${CORE}\n\n## Tail\n\naaa tail.\n`);
  write(join(root, "out", "bbb.md"), `---\nname: bbb\ndescription: d.\n---\n# bbb\n\n${CORE}\n\n## Tail\n\nbbb tail.\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    // aaa+bbb share the exact section → factored; host's SECTION is different (extra line) and
    // must stay VERBATIM — the shared bytes inside it are never swapped mid-section.
    assert.equal(r.factoring.factored.length, 1);
    assert.deepEqual(r.factoring.factored[0].usedBy, ["aaa", "bbb"]);
    assert.ok(!read(recipe(root, "host")).includes("<!-- include:"), "host recipe untouched by factoring");
    assert.match(read(recipe(root, "host")), /line three\.\nhost-extra/, "embedded bytes intact");
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("factor review-fix: a pre-existing brick at the computed path is never clobbered", () => {
  const root = makeRoot({});
  const SH = "### Working folder\n\nCreate the run dir.\nTrack progress there.\nNever skip.";
  write(join(root, "out", "one.md"), `---\nname: one\ndescription: d.\n---\n# one\n\n${SH}\n`);
  write(join(root, "out", "two.md"), `---\nname: two\ndescription: d.\n---\n# two\n\n${SH}\n`);
  // squat the deterministic path with DIFFERENT user content
  const sha8 = createHash("sha256").update(SH).digest("hex").slice(0, 8);
  write(join(root, "bricks", "onboarded", `working-folder-${sha8}.md`), "USER BRICK — do not clobber\n");
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.factoring.factored.length, 0, "group skipped (path taken by different content)");
    assert.equal(read(join(root, "bricks", "onboarded", `working-folder-${sha8}.md`)), "USER BRICK — do not clobber\n");
    assert.equal(run({ root, mode: "check" }).ok, true, "skills stay verbatim and green");
  } finally { cleanup(root); }
});

test("factor review-fix: a DIRECTORY squatting the brick path degrades to verbatim (never throws)", () => {
  const root = makeRoot({});
  const SH = "### Working folder\n\nCreate the run dir.\nTrack progress there.\nNever skip.";
  write(join(root, "out", "one.md"), `---\nname: one\ndescription: d.\n---\n# one\n\n${SH}\n`);
  write(join(root, "out", "two.md"), `---\nname: two\ndescription: d.\n---\n# two\n\n${SH}\n`);
  const sha8 = createHash("sha256").update(SH).digest("hex").slice(0, 8);
  mkdirSync(join(root, "bricks", "onboarded", `working-folder-${sha8}.md`), { recursive: true });
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, "never throws — factoring degrades");
    assert.equal(r.factoring.factored.length, 0);
  } finally { cleanup(root); }
});

test("factor review-fix: --factor on a dry-run says it only takes effect with --apply", () => {
  const root = makeRoot({});
  write(join(root, "out", "x.md"), "---\nname: x\ndescription: d.\n---\n# x\nbody\n");
  try {
    const r = onboard({ root, ts: TS, factor: true }); // no apply
    assert.match(r.msg, /--factor takes effect together with --apply/);
  } finally { cleanup(root); }
});

test("factor review-fix: idempotent re-run reuses the identical brick (no dup, still consumed)", () => {
  const root = makeRoot({});
  const SH = "### Working folder\n\nCreate the run dir.\nTrack progress there.\nNever skip.";
  write(join(root, "out", "one.md"), `---\nname: one\ndescription: d.\n---\n# one\n\n${SH}\n`);
  write(join(root, "out", "two.md"), `---\nname: two\ndescription: d.\n---\n# two\n\n${SH}\n`);
  try {
    const r1 = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r1.factoring.factored.length, 1);
    // new skill arrives later with the same shared section; re-run factors it against the SAME brick
    write(join(root, "out", "three.md"), `---\nname: three\ndescription: d.\n---\n# three\n\n${SH}\n`);
    const r2 = onboard({ root, ts: TS + "-b", apply: true, factor: true });
    assert.equal(r2.ok, true, r2.msg);
    const f = r2.factoring.factored[0];
    assert.equal(f.reused, true, "pre-existing identical brick reused, not rewritten");
    assert.ok(f.usedBy.includes("three"));
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

// ═══ F-31 Fase 5: the forge-onboard agent skill (installSkill + ecosystem closure) ══════════
test("installSkill: materializes with the marker; idempotent; never clobbers an unmarked homonym", () => {
  const root = makeRoot({});
  try {
    const r1 = installSkill({ root });
    assert.equal(r1.ok, true, r1.msg);
    const dest = join(root, "out", "forge-onboard.md");
    assert.equal(has(dest), true);
    assert.match(read(dest), /forge-role: nbp-skillforge\/onboard/, "carries the marker");
    const r2 = installSkill({ root });
    assert.equal(r2.already, true, "byte-identical reinstall is a no-op");
    // a same-named USER file (no marker) is never clobbered
    writeFileSync(dest, "---\nname: forge-onboard\ndescription: user's own!\n---\nmine\n");
    const r3 = installSkill({ root });
    assert.equal(r3.ok, false);
    assert.match(r3.msg, /does NOT carry the forge-role marker/);
    assert.match(read(dest), /mine/, "user file intact");
  } finally { cleanup(root); }
});

test("installSkill → onboard scan: the installed skill is excluded-forge-role (never re-ingested)", () => {
  const root = makeRoot({});
  try {
    installSkill({ root });
    const r = onboard({ root, ts: TS });
    assert.equal(r.entries.find((e) => /forge-onboard/.test(e.file)).status, "excluded-forge-role");
  } finally { cleanup(root); }
});

test("auto-enforce (maintainer decision): the ephemeral tool is REMOVED in the same step strict mode turns on", () => {
  const root = makeRoot({});
  write(join(root, "out", "only.md"), "---\nname: only\ndescription: d.\n---\n# only\nbody\n");
  try {
    installSkill({ root });
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.enforced, true, "tool file does not block the 100% condition");
    assert.equal(has(join(root, "out", "forge-onboard.md")), false, "ephemeral tool removed with the enable");
    assert.equal(loadConfig(root).enforceGenerated, true);
    assert.equal(run({ root, mode: "check" }).ok, true, "strict mode green immediately");
    // and it comes back on demand
    assert.equal(installSkill({ root }).ok, true);
  } finally { cleanup(root); }
});

test("auto-enforce: with skips present the tool is NOT removed (no enable, no removal)", () => {
  const root = makeRoot({});
  write(join(root, "out", "only.md"), "---\nname: only\ndescription: d.\n---\n# only\nbody\n");
  write(join(root, "out", "Bad_Name.md"), "---\nname: Bad_Name\ndescription: d.\n---\nbad\n");
  try {
    installSkill({ root });
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.enforced, false);
    assert.equal(has(join(root, "out", "forge-onboard.md")), true, "tool stays when enable is blocked");
  } finally { cleanup(root); }
});

test("assets: the bundled spec + wrapper resolve from the package and agree on the marker", () => {
  const spec = readFileSync(new URL("../assets/onboard/ONBOARD-SPEC.md", import.meta.url), "utf8");
  const wrapper = readFileSync(new URL("../assets/onboard/claude-code/forge-onboard.md", import.meta.url), "utf8");
  assert.match(spec, /you propose|You propose/i);
  assert.match(spec, /forge-role: nbp-skillforge\/onboard/);
  assert.match(wrapper, /^---\nname: forge-onboard/m);
  assert.match(wrapper, /ONBOARD-SPEC/, "wrapper points at the embedded protocol (no file path — self-contained install)");
  assert.match(readFileSync(new URL("../package.json", import.meta.url), "utf8"), /"assets\/onboard\/"/); // URL direto: imune a %20 (dual-review)
});

// ═══ Fase 5 dual-review regression fixes ════════════════════════════════════════════════════
test("engine review-fix: an installed tool under PRE-EXISTING strict mode is never an orphan", () => {
  const root = makeRoot({ config: { enforceGenerated: true } });
  write(join(root, "recipes", "only.md"), "---\nname: only\ndescription: d.\n---\n# only\nbody\n");
  run({ root, mode: "build" });
  try {
    const r = installSkill({ root });
    assert.equal(r.ok, true, r.msg);
    const chk = run({ root, mode: "check" });
    assert.equal(chk.ok, true, "check green with the marked tool present under enforceGenerated");
    assert.equal(chk.orphans, 0);
  } finally { cleanup(root); }
});

test("review-fix: auto-enforce with --from still sees (and removes) a tool installed in the OUT dir", () => {
  const root = makeRoot({});
  installSkill({ root }); // tool sits in out/, but the scan will look at elsewhere/
  write(join(root, "elsewhere", "ext.md"), "---\nname: ext\ndescription: d.\n---\n# ext\nbody\n");
  try {
    const r = onboard({ root, ts: TS, apply: true, from: "elsewhere" });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.enforced, true, "the marked tool in out/ no longer blocks the enable");
    assert.equal(has(join(root, "out", "forge-onboard.md")), false, "tool removed from the governed out dir");
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("review-fix: a MARKED file in the --from source dir is never deleted (not an installation)", () => {
  const root = makeRoot({});
  write(join(root, "elsewhere", "ext.md"), "---\nname: ext\ndescription: d.\n---\n# ext\nbody\n");
  write(join(root, "elsewhere", "tool-copy.md"), "---\nname: tool-copy\ndescription: t.\nforge-role: nbp-skillforge/onboard\n---\nuser's template copy\n");
  try {
    const r = onboard({ root, ts: TS, apply: true, from: "elsewhere" });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.enforced, true);
    assert.equal(has(join(root, "elsewhere", "tool-copy.md")), true, "source-dir marked file untouched");
  } finally { cleanup(root); }
});

test("review-fix: --from escaping the project root via .. is refused", () => {
  const root = makeRoot({});
  try {
    const r = onboard({ root, ts: TS, from: join("..", "outside") });
    assert.equal(r.ok, false);
    assert.match(r.msg, /must stay inside the project root/);
  } finally { cleanup(root); }
});

test("review-fix: installSkill refuses a role-overlapping config before writing anything", () => {
  const root = makeRoot({ config: { out: "bricks" } });
  try {
    const r = installSkill({ root });
    assert.equal(r.ok, false);
    assert.match(r.msg, /must not be inside or equal to/);
    assert.equal(has(join(root, "bricks", "forge-onboard.md")), false, "nothing written");
  } finally { cleanup(root); }
});

test("review-fix: the installed skill is SELF-CONTAINED (protocol embedded, no package paths)", () => {
  const root = makeRoot({});
  try {
    installSkill({ root });
    const installed = read(join(root, "out", "forge-onboard.md"));
    assert.match(installed, /ONBOARD-SPEC\.md — embedded verbatim/, "spec inlined at install time");
    assert.match(installed, /Approval unit = the GROUP/, "the actual protocol body is present");
    assert.ok(!installed.includes("node_modules/nbp-skillforge"), "no package-path resolution instructions");
  } finally { cleanup(root); }
});

// ═══ Fable bug-hunt regression fixes (session 2026-07-06, post-0.7.0) ═══════════════════════
test("Fable B1: divergent same-named file in out[1] → skip-collision, its bytes SURVIVE", () => {
  const root = makeRoot({ config: { out: ["out", "second-out"] } });
  write(join(root, "out", "foo.md"), "---\nname: foo\ndescription: d.\n---\n# foo A-version\n");
  write(join(root, "second-out", "foo.md"), "PRECIOUS hand-made B content — must survive\n");
  write(join(root, "out", "bar.md"), "---\nname: bar\ndescription: d.\n---\n# bar\n");
  try {
    const r = onboard({ root, ts: TS, apply: true });
    const foo = r.entries.find((e) => /foo/.test(e.file));
    assert.equal(foo.status, "skip-collision", "divergent copy detected");
    assert.match(read(join(root, "second-out", "foo.md")), /PRECIOUS/, "out[1] bytes intact");
    assert.equal(r.enforced, false, "no false '100% migrated' announcement");
    // bar (no divergent copy) migrates normally
    assert.equal(has(recipe(root, "bar")), true);
  } finally { cleanup(root); }
});

test("Fable B1b: byte-IDENTICAL copy in out[1] is allowed (content is the snapshotted source)", () => {
  const root = makeRoot({ config: { out: ["out", "second-out"] } });
  const content = "---\nname: foo\ndescription: d.\n---\n# foo same everywhere\n";
  write(join(root, "out", "foo.md"), content);
  write(join(root, "second-out", "foo.md"), content);
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.entries.find((e) => /foo/.test(e.file)).status, "eligible");
    assert.equal(r.ok, true, r.msg);
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("Fable B6: --from equal to outs[0] spelled with backslashes is NOT a self-collision", () => {
  const root = makeRoot({ config: { out: "sub/cmd" } });
  write(join(root, "sub", "cmd", "x.md"), "---\nname: x\ndescription: d.\n---\n# x\n");
  try {
    const r = onboard({ root, ts: TS, from: "sub\\cmd" }); // backslash spelling of the same dir
    assert.equal(r.entries.find((e) => /x\.md/.test(e.file)).status, "eligible", "no self-collision");
  } finally { cleanup(root); }
});

test("Fable B6b: --from pointing at out[1] does not make its own files collide with themselves", () => {
  const root = makeRoot({ config: { out: ["out", "second-out"] } });
  write(join(root, "second-out", "y.md"), "---\nname: y\ndescription: d.\n---\n# y\n");
  try {
    const r = onboard({ root, ts: TS, from: "second-out" });
    assert.equal(r.entries.find((e) => /y\.md/.test(e.file)).status, "eligible");
  } finally { cleanup(root); }
});

test("Fable B10: import strips a GENERATED banner even after blank lines (no double-banner)", async () => {
  const { importFile } = await import("../src/lifecycle.mjs");
  const root = makeRoot({});
  const src = join(root, "external", "gappy.md");
  write(src, "---\nname: gappy\ndescription: d.\n---\n\n\n<!-- GENERATED by nbp-skillforge from recipes/gappy.md — do not edit here. -->\nreal body\n");
  try {
    const r = importFile(src, { root });
    assert.equal(r.ok, true, r.msg);
    assert.equal(run({ root, mode: "build" }).ok, true);
    const out = read(outFile(root, "gappy"));
    assert.equal((out.match(/GENERATED by nbp-skillforge/g) || []).length, 1, "exactly one banner");
  } finally { cleanup(root); }
});

test("Fable B9: --from pointing at a FILE is a clean user-facing error, not ENOTDIR", () => {
  const root = makeRoot({});
  write(join(root, "some.md"), "# a file\n");
  try {
    assert.throws(() => onboard({ root, ts: TS, from: "some.md" }),
      (e) => e.userFacing === true && /not a directory/.test(e.message));
  } finally { cleanup(root); }
});
