// onboard (F-31 Fases 2+3): discovery/exclusion, pre-scan, snapshot, verbatim apply, fidelity
// gate, report, auto-enforce. Every test verifies BY EXECUTION on a throwaway root.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { discover, preScan, normalizeForGate, snapshot, onboard, installSkill } from "../src/onboard.mjs";
import { run, loadConfig, FORGE_ROLE_VALUE } from "../src/compose.mjs";
import { gc } from "../src/lifecycle.mjs";
import { createHash } from "node:crypto";
import { makeRoot, write, read, readRaw, has, recipe, outFile, cleanup } from "./helpers.mjs";

const TS = "2026-07-06T00-00-00-000"; // injected timestamp — onboard.mjs never reads the clock

// One hostile-mix fixture reused by several tests.
const mixRoot = () => {
  const root = makeRoot({
    bricks: { b: "brick body" },
    recipes: { governed: "---\nname: governed\ndescription: d.\n---\n# governed\n\n<!-- include: b -->\n" },
  });
  run({ root, mode: "build" }); // `governed` now sits generated in out/
  write(join(root, "out", "hand-made.md"), "---\nname: hand-made\ndescription: Hand-written skill.\n---\n# hand-made\n\nDo the thing.\n");
  write(join(root, "out", "plain-cmd.md"), "# plain command\n\nNo frontmatter at all.\n");
  write(join(root, "out", "tool.md"), `---\nname: tool\ndescription: t.\nforge-role: ${FORGE_ROLE_VALUE}\n---\n# tool\nbody\n`);
  write(join(root, "out", "Bad_Name.md"), "---\nname: Bad_Name\ndescription: d.\n---\n# bad\nbody\n");
  write(join(root, "out", "governed.md"), read(join(root, "out", "governed.md"))); // unchanged, still generated
  write(join(root, "out", "has-include.md"), "# x\n\n<!-- include: run-dir -->\n");
  write(join(root, "out", "fenced-include.md"), "# y\n\n```\n<!-- include: run-dir -->\n```\n");
  writeFileSync(join(root, "out", "binary.md"), Buffer.from([0xff, 0xfe, 0x00, 0x41, 0x80, 0x81]));
  mkdirSync(join(root, "out", "sub"), { recursive: true });
  write(join(root, "out", "sub", "nested.md"), "# nested\n");
  return root;
};

test("discover: classifies the hostile mix correctly, every file gets a disposition", () => {
  const root = mixRoot();
  try {
    const { entries } = discover(root, loadConfig(root));
    const by = Object.fromEntries(entries.map((e) => [e.file.replace(/\\/g, "/").split("/").pop(), e.status]));
    assert.equal(by["hand-made.md"], "eligible");
    assert.equal(by["plain-cmd.md"], "eligible", "a no-frontmatter command is eligible (no name gate)");
    assert.equal(by["fenced-include.md"], "eligible", "an include inside a fence is NOT a landmine (engine parity)");
    assert.equal(by["governed.md"], "excluded-generated", "banner detected AFTER splitFm (fm'd file)");
    assert.equal(by["tool.md"], "excluded-forge-role");
    assert.equal(by["Bad_Name.md"], "skip-nonconformant");
    assert.equal(by["has-include.md"], "skip-include-like");
    assert.equal(by["binary.md"], "skip-non-utf8");
    assert.equal(by["nested.md"], "skip-nested");
    const bad = entries.find((e) => e.status === "skip-nonconformant");
    assert.match(bad.proposal ?? "", /bad-name/, "a conformant rename is proposed, never applied");
  } finally { cleanup(root); }
});

test("discover: a PRE-RENAME banner (nbp-forge) is still recognized as generated", () => {
  const root = makeRoot({});
  write(join(root, "out", "old-gen.md"), "<!-- GENERATED by nbp-forge from recipes/old-gen.md — do not edit here. -->\n# old\nbody\n");
  try {
    const { entries } = discover(root, loadConfig(root));
    assert.equal(entries[0].status, "excluded-generated");
    // Release-readiness fix (2026-07-07): this fixture is EXACTLY the orphan-output case — the
    // banner is there but no recipe exists — so the reason must not claim "has a recipe"; it
    // states only what the banner proves.
    assert.match(entries[0].reason, /carries the GENERATED banner/, "reason states the evidence");
    assert.doesNotMatch(entries[0].reason, /has a recipe/, "never asserts a recipe that may be gone");
  } finally { cleanup(root); }
});

test("preScan: BOM detected+stripped; placeholders recorded; include-like honors fences", () => {
  // ﻿ escape (not a literal BOM char) — editors/shells silently strip the literal.
  const bom = preScan(Buffer.from("﻿---\nname: x\n---\nbody {{param}}\n", "utf8"));
  assert.equal(bom.bom, true);
  assert.match(bom.text, /^---/, "BOM stripped so splitFm's anchor works");
  assert.deepEqual(bom.placeholders, ["{{param}}"]);
  const inv = preScan(Buffer.from([0xc3, 0x28])); // invalid UTF-8 sequence
  assert.equal(inv.utf8, false);
});

// F-33 parity: a bang directive (`include!:`) is expanded by the engine even INSIDE a fence, so
// the pre-scan must flag it as include-like wherever it sits — a fence no longer proves safety.
// Athena triage (proven by execution): the OLD single reason told the fenced-bang author to
// "fence it" — advice already satisfied, a permanent dead end. The KIND now travels with the
// scan ("bang" | "unfenced") and the reason must name the actual case and a remedy that works.
test("discover: a bang include inside a fence is skip-include-like with a BANG-specific reason", () => {
  const root = makeRoot({});
  write(join(root, "out", "bang-fenced.md"), "# z\n\n```\n<!-- include!: run-dir -->\n```\n");
  try {
    const scan = preScan(readRaw(join(root, "out", "bang-fenced.md")));
    assert.equal(scan.includeLike, "bang", "preScan must flag a fenced BANG directive as include-like, KIND = bang");
    const { entries } = discover(root, loadConfig(root));
    const e = entries.find((x) => x.file.replace(/\\/g, "/").endsWith("bang-fenced.md"));
    assert.equal(e.status, "skip-include-like");
    assert.match(e.reason, /bang include directive/, "the reason names the bang case");
    assert.match(e.reason, /expands it even inside a code fence/, "the reason states the fence is no protection");
    assert.match(e.reason, /remove the `!`/, "the advice is actionable for a bang");
    assert.ok(!e.reason.includes("fence it"), "the dead-end 'fence it' advice must never reach a bang author");
    assert.ok(!e.reason.includes("outside a code fence"), "the factually-wrong 'outside a fence' claim is gone");
  } finally { cleanup(root); }
});

// The bang wins even when BOTH kinds are present: fencing alone can never fix such a file.
test("preScan: bang + unfenced in the same body → KIND is bang (fencing can never fix the file)", () => {
  const scan = preScan(Buffer.from("# z\n\n<!-- include: other -->\n\n```\n<!-- include!: run-dir -->\n```\n", "utf8"));
  assert.equal(scan.includeLike, "bang");
});

// Regression pin for the ORIGINAL case: an unfenced plain directive keeps the original reason —
// there, "fence it" is true advice (F-03 keeps a fenced plain directive verbatim).
test("discover: an UNFENCED plain include keeps the 'fence it' reason (still true advice there)", () => {
  const root = makeRoot({});
  write(join(root, "out", "unfenced.md"), "# z\n\n<!-- include: run-dir -->\n");
  try {
    const scan = preScan(readRaw(join(root, "out", "unfenced.md")));
    assert.equal(scan.includeLike, "unfenced", "KIND = unfenced for a plain directive outside any fence");
    const { entries } = discover(root, loadConfig(root));
    const e = entries.find((x) => x.file.replace(/\\/g, "/").endsWith("unfenced.md"));
    assert.equal(e.status, "skip-include-like");
    assert.match(e.reason, /outside a code fence/);
    assert.match(e.reason, /fence it or onboard by hand/);
  } finally { cleanup(root); }
});

test("normalizeForGate: original ≡ its verbatim build (banner+CRLF+EOF-ws); real edits differ", () => {
  const original = "---\r\nname: s\r\ndescription: d.\r\n---\r\n# s\r\n\r\nbody line\r\n\r\n";
  const rebuilt = "---\nname: s\ndescription: d.\n---\n<!-- GENERATED by nbp-skillforge from recipes/s.md — do not edit here; edit the recipe/brick and run `npx nbp-skillforge build`. -->\n# s\n\nbody line\n";
  assert.equal(normalizeForGate(original), normalizeForGate(rebuilt), "the three legal axes normalize away");
  assert.notEqual(normalizeForGate(original), normalizeForGate(rebuilt.replace("body line", "body line EDITED")), "a real divergence is never masked");
});

test("onboard (dry): default is a report-only run — the tree is byte-identical after", () => {
  const root = mixRoot();
  try {
    const before = new Map(readdirSync(join(root, "out"), { recursive: true }).map((f) => {
      const p = join(root, "out", String(f));
      return [String(f), existsSync(p) && !String(f).includes("sub") ? null : null];
    }));
    const snap = (dir) => readdirSync(dir, { recursive: true }).map(String).sort().join("|");
    const treeBefore = snap(root);
    const r = onboard({ root, ts: TS }); // no apply
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.applied, false);
    assert.equal(snap(root), treeBefore, "dry-run creates/modifies NOTHING");
    assert.match(r.msg, /scanned out/, "the scanned root is announced");
    assert.match(r.msg, /--from <dir>/, "the user is told how to point the scan elsewhere");
  } finally { cleanup(root); }
});

test("onboard --apply: E2E — snapshot faithful, recipes created, gate zero, check green, report covers all", () => {
  const root = mixRoot();
  try {
    const originalCrlf = "---\r\nname: crlf-skill\r\ndescription: d.\r\n---\r\n# crlf\r\n\r\nCRLF body\r\n";
    writeFileSync(join(root, "out", "crlf-skill.md"), originalCrlf);
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, true, r.msg);
    // (1) backup byte-faithful (CRLF preserved)
    const bak = join(root, "_onboard-backup-" + TS);
    assert.equal(readFileSync(join(bak, "crlf-skill.md"), "latin1"), Buffer.from(originalCrlf).toString("latin1"), "backup preserves exact original bytes");
    // (2) recipes exist + gate passed for every migrated skill
    for (const s of ["hand-made", "plain-cmd", "crlf-skill", "fenced-include"]) {
      assert.equal(has(recipe(root, s)), true, `recipe created: ${s}`);
      assert.equal(r.gate.find((g) => g.skill === s)?.pass, true, `gate zero for ${s}`);
    }
    // rebuilt output is LF-only even though the source was CRLF
    assert.equal(readRaw(outFile(root, "crlf-skill")).includes(0x0d), false, "out is LF");
    // (3) drift-gate green afterward
    assert.equal(run({ root, mode: "check" }).ok, true, "forge check green after onboarding");
    // (4) report covers 100% of the scanned files
    const report = read(join(bak, "onboard-report.md"));
    for (const f of ["hand-made.md", "governed.md", "tool.md", "Bad_Name.md", "has-include.md", "binary.md", "nested.md"])
      assert.ok(report.includes(f), `report mentions ${f}`);
    // Release-readiness fix (2026-07-07): the fidelity-gate verdict cell is EN like every other
    // artifact of this repo — the old PT cell ("✔ fiel (diff normalizado zero)") must never return.
    assert.match(report, /✔ faithful \(normalized diff zero\)/, "gate verdict rendered in EN");
    assert.doesNotMatch(report, /fiel \(diff normalizado zero\)/, "no PT leftover in the report");
    // skips present → enforceGenerated must NOT auto-enable
    assert.equal(r.enforced, false);
    assert.equal(loadConfig(root).enforceGenerated, false);
    assert.match(report, /enforceGenerated stays OFF/);
    // (5) skipped/excluded originals untouched
    assert.match(read(join(root, "out", "Bad_Name.md")), /# bad/, "skipped file untouched");
  } finally { cleanup(root); }
});

// Athena triage F2 (proven by execution): a user skill literally named `onboard-report.md` lands
// in the backup dir as a byte-faithful snapshot BEFORE writeReport() runs — the report used to
// overwrite it, silently destroying the only byte-exact copy of the original, and the report's own
// rollback instruction would then restore the REPORT TEXT over the user's skill. The guard must
// keep the snapshot intact and divert the report to the first free `onboard-report-<n>.md`.
test("onboard --apply: a user skill named 'onboard-report' never loses its snapshot to the report", () => {
  const root = makeRoot({});
  // Distinctive bytes: CRLF + trailing spaces — exactly what the recipe normalizes away, so the
  // snapshot is the ONLY byte-exact copy (the execution repro's fidelity-loss scenario).
  const originalBytes = "---\r\nname: onboard-report\r\ndescription: user skill, unlucky name.\r\n---\r\n# onboard-report\r\n\r\nline1  \r\nline2\r\n";
  mkdirSync(join(root, "out"), { recursive: true }); // raw writeFileSync (exact bytes) — no helper mkdir
  writeFileSync(join(root, "out", "onboard-report.md"), originalBytes);
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, true, r.msg);
    const bak = join(root, "_onboard-backup-" + TS);
    // (1) the snapshot survives byte-for-byte — never overwritten by the report
    assert.equal(readRaw(join(bak, "onboard-report.md")).equals(Buffer.from(originalBytes)), true,
      "the byte-faithful snapshot of the user's skill must survive writeReport()");
    // (2) the report itself was diverted to the first free suffixed name, content intact
    assert.equal(has(join(bak, "onboard-report-2.md")), true, "the report falls back to onboard-report-2.md");
    assert.match(read(join(bak, "onboard-report-2.md")), /^# onboard report/, "the diverted file IS the report");
    // (3) the skill was genuinely onboarded (recipe exists, gate passed)
    assert.equal(has(recipe(root, "onboard-report")), true);
    assert.equal(r.gate.find((g) => g.skill === "onboard-report")?.pass, true);
  } finally { cleanup(root); }
});

test("onboard --apply: re-run is a clean no-op (everything already governed)", () => {
  const root = makeRoot({});
  write(join(root, "out", "only.md"), "---\nname: only\ndescription: d.\n---\n# only\nbody\n");
  try {
    const r1 = onboard({ root, ts: TS, apply: true });
    assert.equal(r1.ok, true, r1.msg);
    const r2 = onboard({ root, ts: TS + "-2", apply: true });
    assert.equal(r2.ok, true, r2.msg);
    assert.equal(r2.entries.every((e) => e.status.startsWith("excluded-")), true, "everything now excluded-generated/has-recipe");
    assert.equal(has(join(root, "_onboard-backup-" + TS + "-2")), false, "no second backup for a no-op run");
  } finally { cleanup(root); }
});

test("onboard --apply: 100% migrated → enforceGenerated auto-enables and is announced", () => {
  const root = makeRoot({});
  write(join(root, "out", "clean-one.md"), "---\nname: clean-one\ndescription: d.\n---\n# one\nbody\n");
  write(join(root, "out", "clean-two.md"), "# two — plain command\nbody\n");
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.enforced, true, "auto-enabled on the 100% condition");
    assert.equal(loadConfig(root).enforceGenerated, true, "persisted to forge.config.json");
    assert.match(r.msg, /enforceGenerated: ON/);
    assert.equal(run({ root, mode: "check" }).ok, true, "check green under the new strict mode");
  } finally { cleanup(root); }
});

test("onboard --apply: collision (case-fold) with an existing recipe → skip, original intact", () => {
  const root = makeRoot({ recipes: { taken: "---\nname: taken\ndescription: d.\n---\n# taken\nbody\n" } });
  run({ root, mode: "build" });
  write(join(root, "out", "TAKEN.md"), "---\nname: TAKEN\ndescription: other.\n---\n# other\nbody\n");
  try {
    const r = onboard({ root, ts: TS, apply: true });
    const entry = r.entries.find((e) => /TAKEN/i.test(e.file) && e.status !== "excluded-generated");
    // On a case-insensitive FS this folds into the existing recipe (excluded-has-recipe);
    // either way it must never overwrite the existing recipe.
    assert.ok(["excluded-has-recipe", "skip-collision", "skip-nonconformant"].includes(entry.status), entry.status);
    assert.match(read(recipe(root, "taken")), /# taken/, "existing recipe never clobbered");
  } finally { cleanup(root); }
});

test("snapshot: refuses an existing backup dir and a backup dir inside a role dir", () => {
  const root = makeRoot({});
  const cfg = loadConfig(root);
  const bak = join(root, "_bak");
  mkdirSync(bak);
  try {
    assert.throws(() => snapshot(root, [], bak, cfg), /already exists/);
    assert.throws(() => snapshot(root, [], join(root, "bricks", "b"), cfg), /outside every role dir/);
  } finally { cleanup(root); }
});

test("onboard: --from overrides the discovery root (and is announced)", () => {
  const root = makeRoot({});
  write(join(root, "elsewhere", "ext.md"), "---\nname: ext\ndescription: d.\n---\n# ext\nbody\n");
  try {
    const r = onboard({ root, ts: TS, from: "elsewhere" });
    assert.equal(r.entries.length, 1);
    assert.equal(r.entries[0].status, "eligible");
    assert.match(r.msg, /scanned elsewhere/);
  } finally { cleanup(root); }
});

test("onboard: --from pointing inside bricks/recipes/archive is refused (self-ingestion guard)", () => {
  const root = makeRoot({ bricks: { b: "brick body" } });
  try {
    for (const bad of ["bricks", "recipes", "_archive"]) {
      const r = onboard({ root, ts: TS, from: bad });
      assert.equal(r.ok, false, `--from ${bad} must be refused`);
      assert.match(r.msg, /must not point inside/);
    }
  } finally { cleanup(root); }
});

// ═══ Dual-review regression fixes (codex + agy, adjudicated by execution) ═══════════════════
test("review-fix: pre-existing drift in a governed skill ABORTS apply (no un-snapshotted heal)", () => {
  const root = makeRoot({
    bricks: { b: "body" },
    recipes: { governed: "---\nname: governed\ndescription: d.\n---\n# governed\n\n<!-- include: b -->\n" },
  });
  run({ root, mode: "build" });
  write(join(root, "out", "governed.md"), read(join(root, "out", "governed.md")) + "HAND EDIT\n"); // drift
  write(join(root, "out", "newbie.md"), "---\nname: newbie\ndescription: d.\n---\n# new\nbody\n");
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, false);
    assert.match(r.msg, /drifted from their recipes/);
    assert.match(read(join(root, "out", "governed.md")), /HAND EDIT/, "the hand-edit survives (nothing healed)");
    assert.equal(has(recipe(root, "newbie")), false, "nothing was imported");
    assert.equal(has(join(root, "_onboard-backup-" + TS)), false, "no backup dir for an aborted pre-flight");
  } finally { cleanup(root); }
});

test("review-fix: fm name ≠ basename → skip-name-mismatch (no recipe under a foreign name)", () => {
  const root = makeRoot({});
  write(join(root, "out", "legacy.md"), "---\nname: clean\ndescription: d.\n---\n# legacy\nbody\n");
  try {
    const r = onboard({ root, ts: TS, apply: true });
    const e = r.entries.find((x) => /legacy/.test(x.file));
    assert.equal(e.status, "skip-name-mismatch");
    assert.equal(has(recipe(root, "clean")), false, "no recipe minted under the fm name");
    assert.equal(has(recipe(root, "legacy")), false);
    assert.match(read(join(root, "out", "legacy.md")), /# legacy/, "original untouched");
  } finally { cleanup(root); }
});

test("review-fix: --from with a name whose out/<name>.md already exists → skip-collision", () => {
  const root = makeRoot({});
  write(join(root, "out", "foo.md"), "# hand-made foo living in out — must survive\n");
  write(join(root, "elsewhere", "foo.md"), "---\nname: foo\ndescription: d.\n---\n# external foo\n");
  try {
    const r = onboard({ root, ts: TS, apply: true, from: "elsewhere" });
    const e = r.entries.find((x) => /foo/.test(x.file));
    assert.equal(e.status, "skip-collision");
    assert.match(read(join(root, "out", "foo.md")), /must survive/, "the un-snapshotted target is never overwritten");
  } finally { cleanup(root); }
});

test("review-fix: BOM + frontmatter file imports with the fm intact (engine strips the BOM)", () => {
  const root = makeRoot({});
  mkdirSync(join(root, "out"), { recursive: true });
  writeFileSync(join(root, "out", "bommed.md"), Buffer.concat([
    Buffer.from([0xef, 0xbb, 0xbf]),
    Buffer.from("---\nname: bommed\ndescription: d.\n---\n# bommed\nbody\n"),
  ]));
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, true, r.msg);
    assert.match(read(recipe(root, "bommed")), /^---\nname: bommed/, "fm recognized (BOM stripped by import)");
    assert.equal(r.gate.find((g) => g.skill === "bommed")?.pass, true, "fidelity gate passes");
  } finally { cleanup(root); }
});

test("review-fix: absolute --from is refused with a clear message", () => {
  const root = makeRoot({});
  try {
    const r = onboard({ root, ts: TS, from: join(root, "somewhere") });
    assert.equal(r.ok, false);
    assert.match(r.msg, /relative to the project root/);
  } finally { cleanup(root); }
});

test("review-fix: symlink and unreadable entries get explicit dispositions (no crash)", { skip: process.platform === "win32" ? false : false }, () => {
  const root = makeRoot({});
  write(join(root, "out", "real.md"), "---\nname: real\ndescription: d.\n---\n# real\nbody\n");
  try {
    let linked = false;
    try { // symlink creation may need privileges on Windows — the disposition test is best-effort there
      const { symlinkSync } = require("node:fs");
    } catch {}
    const r = onboard({ root, ts: TS });
    assert.equal(r.ok, true, "scan never crashes");
    assert.equal(r.entries.find((e) => /real/.test(e.file)).status, "eligible");
  } finally { cleanup(root); }
});

test("review-fix: auto-enforce blocked by an un-governed file in a SECOND out dir", () => {
  const root = makeRoot({ config: { out: ["out", "second-out"] } });
  write(join(root, "out", "only.md"), "---\nname: only\ndescription: d.\n---\n# only\nbody\n");
  write(join(root, "second-out", "stray.md"), "# hand-made stray in out[1]\n");
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.enforced, false, "stray in out[1] blocks the auto-enable");
    assert.equal(loadConfig(root).enforceGenerated, false);
    assert.equal(run({ root, mode: "check" }).ok, true, "and check stays green (no orphan surprise)");
  } finally { cleanup(root); }
});

test("review-fix: banner AFTER a stray blank line is still detected as generated", () => {
  const root = makeRoot({});
  write(join(root, "out", "blanky.md"), "---\nname: blanky\ndescription: d.\n---\n\n<!-- GENERATED by nbp-skillforge from recipes/blanky.md — do not edit here. -->\n# blanky\n");
  try {
    const r = onboard({ root, ts: TS });
    assert.equal(r.entries.find((e) => /blanky/.test(e.file)).status, "excluded-generated");
  } finally { cleanup(root); }
});

test("review-fix: an import failure mid-batch rolls back every recipe the run created", () => {
  const root = makeRoot({});
  write(join(root, "out", "aaa.md"), "---\nname: aaa\ndescription: d.\n---\n# aaa\nbody\n");
  write(join(root, "out", "zzz.md"), "---\nname: zzz\ndescription: d.\n---\n# zzz\nbody\n");
  // sabotage: make the SECOND import fail by pre-creating recipes/zzz.md as a DIRECTORY
  mkdirSync(join(root, "recipes", "zzz.md"), { recursive: true });
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, false);
    assert.match(r.msg, /rolled back/);
    assert.equal(has(recipe(root, "aaa")), false, "aaa's recipe rolled back (atomic batch)");
    assert.match(read(join(root, "out", "aaa.md")), /# aaa/, "original untouched");
  } finally { cleanup(root); }
});

// ═══ F-31 Fase 4: mechanical factoring (--factor) — byte-identical only, self-reverting ═════
const SHARED = "### Working folder\n\nAt the start, create the run folder.\nWrite progress there as you go.\nNever skip this step.";

test("factor: an identical ### section in 2 skills → 1 brick, 2 includes, gate zero, check green", () => {
  const root = makeRoot({});
  write(join(root, "out", "alpha.md"), `---\nname: alpha\ndescription: d.\n---\n# alpha\n\n${SHARED}\n\n## Ending\n\nAlpha-only ending.\n`);
  write(join(root, "out", "beta.md"), `---\nname: beta\ndescription: d.\n---\n# beta\n\n${SHARED}\n\n## Ending\n\nBeta-only ending.\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.factoring.factored.length, 1, "exactly one shared brick");
    const brick = r.factoring.factored[0];
    assert.match(brick.brick, /^onboarded\/working-folder-[0-9a-f]{8}$/, "deterministic slug-hash name");
    assert.deepEqual(brick.usedBy.sort(), ["alpha", "beta"]);
    assert.equal(r.factoring.kept.length, 0);
    // recipes now carry the include; outputs still reproduce the ORIGINAL bytes (gate proven):
    assert.match(read(recipe(root, "alpha")), /<!-- include: onboarded\/working-folder-/);
    assert.match(read(outFile(root, "alpha")), /Never skip this step\./);
    assert.equal(run({ root, mode: "check" }).ok, true);
    // determinism: same content → same brick name on a fresh identical root
    const root2 = makeRoot({});
    write(join(root2, "out", "alpha.md"), `---\nname: alpha\ndescription: d.\n---\n# alpha\n\n${SHARED}\n\n## Ending\n\nAlpha-only ending.\n`);
    write(join(root2, "out", "beta.md"), `---\nname: beta\ndescription: d.\n---\n# beta\n\n${SHARED}\n\n## Ending\n\nBeta-only ending.\n`);
    const r2 = onboard({ root: root2, ts: TS, apply: true, factor: true });
    assert.equal(r2.factoring.factored[0].brick, brick.brick, "same input → same brick name");
    cleanup(root2);
  } finally { cleanup(root); }
});

test("factor: a block containing a literal {{param}} NEVER becomes a brick", () => {
  const root = makeRoot({});
  const P = "### Params\n\nUse {{skill}} here.\nAnd more lines.\nAnd more.";
  write(join(root, "out", "one.md"), `---\nname: one\ndescription: d.\n---\n# one\n\n${P}\n`);
  write(join(root, "out", "two.md"), `---\nname: two\ndescription: d.\n---\n# two\n\n${P}\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.factoring.factored.length, 0, "placeholder block stays in the residual body");
    assert.match(read(recipe(root, "one")), /\{\{skill\}\}/, "verbatim in the recipe");
    assert.equal(run({ root, mode: "check" }).ok, true, "and the build stays green");
  } finally { cleanup(root); }
});

test("factor: near-identical blocks (1 char apart) do NOT factor (byte-identical only)", () => {
  const root = makeRoot({});
  write(join(root, "out", "one.md"), `---\nname: one\ndescription: d.\n---\n# one\n\n### Step\n\nDo the thing.\nCarefully now.\nAlways.\n`);
  write(join(root, "out", "two.md"), `---\nname: two\ndescription: d.\n---\n# two\n\n### Step\n\nDo the thing.\nCarefully now!\nAlways.\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.factoring.factored.length, 0, "near-identical is Fase B's job, never automatic");
  } finally { cleanup(root); }
});

// F-34 flipped this case: pre-F-34, fenced shared content could never factor (the section pass
// only sees unfenced headings). The block pass now factors it via the F-33 bang (`include!:`) —
// the ONE directive form the engine expands inside a fence — with the same byte-identical gate.
test("factor F-34: a block shared only inside a code fence factors via include!:, round-trip byte-identical", () => {
  const root = makeRoot({});
  const F = "```\n### Fenced heading\nline\nline\nline\n```";
  const one = `---\nname: one\ndescription: d.\n---\n# one\n\nIntro one.\n\n${F}\n`;
  write(join(root, "out", "one.md"), one);
  write(join(root, "out", "two.md"), `---\nname: two\ndescription: d.\n---\n# two\n\nIntro two.\n\n${F}\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    // the fenced pseudo-heading never segments a SECTION of its own (Intro one vs two differ),
    // but the 4-line block inside the fence is byte-identical across both skills → block pass.
    assert.equal(r.factoring.factored.length, 1, "the fenced block factored");
    assert.match(r.factoring.factored[0].brick, /^onboarded\/fenced-heading-[0-9a-f]{8}$/);
    assert.equal(r.factoring.kept.length, 0);
    const rec = read(recipe(root, "one"));
    assert.match(rec, /<!-- include!: onboarded\/fenced-heading-/, "swap uses the bang form inside the fence");
    assert.ok(!rec.includes("<!-- include: "), "no bang-less directive was planted in the fence");
    // brick body is the block VERBATIM (fence markers stay in the recipe, never in the brick)
    assert.equal(read(join(root, "bricks", "onboarded", r.factoring.factored[0].brick.split("/")[1] + ".md")), "### Fenced heading\nline\nline\nline\n");
    // round trip byte-identical: output minus the injected banner === the original bytes
    const out = read(outFile(root, "one")).split("\n").filter((l) => !/^<!-- GENERATED by nbp-skillforge/.test(l)).join("\n");
    assert.equal(out, one, "byte-identical round trip through the fenced brick");
    assert.equal(run({ root, mode: "check" }).ok, true);
    // F-33 ref-count parity: a brick consumed ONLY via bang-in-fence is never a gc orphan
    assert.equal(gc(root, {}).orphans.length, 0);
  } finally { cleanup(root); }
});

test("factor: blocks shared by 3 skills ref-count 3; gc never flags the onboarded brick", () => {
  const root = makeRoot({});
  for (const n of ["um", "dois", "tres"])
    write(join(root, "out", `${n}.md`), `---\nname: ${n}\ndescription: d.\n---\n# ${n}\n\n${SHARED}\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.factoring.factored[0].usedBy.length, 3);
    const g = gc(root, {});
    assert.equal(g.orphans.length, 0, "a consumed onboarded brick is never an orphan");
  } finally { cleanup(root); }
});

// ═══ Fase 4 dual-review regression fixes ════════════════════════════════════════════════════
test("factor review-fix: the same bytes embedded in ANOTHER section never get factored in-place", () => {
  const root = makeRoot({});
  const CORE = "### Shared\n\nline one of shared.\nline two of shared.\nline three.";
  // skill 'host' contains CORE embedded INSIDE a bigger section (extra line before next heading)
  write(join(root, "out", "host.md"), `---\nname: host\ndescription: d.\n---\n# host\n\n${CORE}\nhost-extra line in the SAME section.\n\n## Tail\n\ntail.\n`);
  write(join(root, "out", "aaa.md"), `---\nname: aaa\ndescription: d.\n---\n# aaa\n\n${CORE}\n\n## Tail\n\naaa tail.\n`);
  write(join(root, "out", "bbb.md"), `---\nname: bbb\ndescription: d.\n---\n# bbb\n\n${CORE}\n\n## Tail\n\nbbb tail.\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    // aaa+bbb share the exact section → factored; host's SECTION is different (extra line) and
    // must stay VERBATIM — the shared bytes inside it are never swapped mid-section.
    assert.equal(r.factoring.factored.length, 1);
    assert.deepEqual(r.factoring.factored[0].usedBy, ["aaa", "bbb"]);
    assert.ok(!read(recipe(root, "host")).includes("<!-- include:"), "host recipe untouched by factoring");
    assert.match(read(recipe(root, "host")), /line three\.\nhost-extra/, "embedded bytes intact");
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("factor review-fix: a pre-existing brick at the computed path is never clobbered", () => {
  const root = makeRoot({});
  const SH = "### Working folder\n\nCreate the run dir.\nTrack progress there.\nNever skip.";
  write(join(root, "out", "one.md"), `---\nname: one\ndescription: d.\n---\n# one\n\n${SH}\n`);
  write(join(root, "out", "two.md"), `---\nname: two\ndescription: d.\n---\n# two\n\n${SH}\n`);
  // squat the deterministic path with DIFFERENT user content
  const sha8 = createHash("sha256").update(SH).digest("hex").slice(0, 8);
  write(join(root, "bricks", "onboarded", `working-folder-${sha8}.md`), "USER BRICK — do not clobber\n");
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    // The SECTION group is skipped (its path is taken by different content) and the squatted
    // brick survives byte-for-byte. F-34: the inner 3-line block still factors — at its OWN
    // deterministic path (slug of the block's first line + sha8 of the block), never the squat's.
    assert.equal(read(join(root, "bricks", "onboarded", `working-folder-${sha8}.md`)), "USER BRICK — do not clobber\n");
    assert.ok(r.factoring.factored.every((f) => f.brick !== `onboarded/working-folder-${sha8}`), "the squatted path is never reused");
    assert.equal(r.factoring.factored.length, 1, "the inner block factored at its own path (F-34)");
    assert.match(r.factoring.factored[0].brick, /^onboarded\/create-the-run-dir-[0-9a-f]{8}$/);
    assert.equal(run({ root, mode: "check" }).ok, true, "skills stay green");
  } finally { cleanup(root); }
});

test("factor review-fix: a DIRECTORY squatting the brick path degrades to verbatim (never throws)", () => {
  const root = makeRoot({});
  const SH = "### Working folder\n\nCreate the run dir.\nTrack progress there.\nNever skip.";
  write(join(root, "out", "one.md"), `---\nname: one\ndescription: d.\n---\n# one\n\n${SH}\n`);
  write(join(root, "out", "two.md"), `---\nname: two\ndescription: d.\n---\n# two\n\n${SH}\n`);
  const sha8 = createHash("sha256").update(SH).digest("hex").slice(0, 8);
  mkdirSync(join(root, "bricks", "onboarded", `working-folder-${sha8}.md`), { recursive: true });
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, "never throws — factoring degrades");
    // F-34: the SECTION group degrades (EISDIR on the squatted path → skip), but the inner
    // 3-line block still factors at its own, un-squatted path — degradation is per group.
    assert.ok(r.factoring.factored.every((f) => f.brick !== `onboarded/working-folder-${sha8}`), "squatted group skipped");
    assert.equal(r.factoring.factored.length, 1);
    assert.match(r.factoring.factored[0].brick, /^onboarded\/create-the-run-dir-/);
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("factor review-fix: --factor on a dry-run says it only takes effect with --apply", () => {
  const root = makeRoot({});
  write(join(root, "out", "x.md"), "---\nname: x\ndescription: d.\n---\n# x\nbody\n");
  try {
    const r = onboard({ root, ts: TS, factor: true }); // no apply
    assert.match(r.msg, /--factor takes effect together with --apply/);
  } finally { cleanup(root); }
});

test("factor review-fix: idempotent re-run reuses the identical brick (no dup, still consumed)", () => {
  const root = makeRoot({});
  const SH = "### Working folder\n\nCreate the run dir.\nTrack progress there.\nNever skip.";
  write(join(root, "out", "one.md"), `---\nname: one\ndescription: d.\n---\n# one\n\n${SH}\n`);
  write(join(root, "out", "two.md"), `---\nname: two\ndescription: d.\n---\n# two\n\n${SH}\n`);
  try {
    const r1 = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r1.factoring.factored.length, 1);
    // Release-readiness fix (2026-07-07): a FRESH extraction carries no "(reused)" clause — the
    // additive suffix must appear only when a pre-existing brick was actually re-matched.
    assert.match(r1.msg, /1 shared brick\(s\) extracted[,.]/, "fresh batch: plain 'extracted'");
    assert.doesNotMatch(r1.msg, /reused/, "fresh batch: no reused clause");
    // new skill arrives later with the same shared section; re-run factors it against the SAME brick
    write(join(root, "out", "three.md"), `---\nname: three\ndescription: d.\n---\n# three\n\n${SH}\n`);
    const r2 = onboard({ root, ts: TS + "-b", apply: true, factor: true });
    assert.equal(r2.ok, true, r2.msg);
    const f = r2.factoring.factored[0];
    assert.equal(f.reused, true, "pre-existing identical brick reused, not rewritten");
    assert.ok(f.usedBy.includes("three"));
    // Release-readiness fix (2026-07-07): a batch that only RE-USES must say so — the bare
    // "1 shared brick(s) extracted" read as a fresh write. Msg gains "(1 reused)" and the
    // report's factoring table marks the row.
    assert.match(r2.msg, /1 shared brick\(s\) extracted \(1 reused\)/, "reuse-only batch labeled in the msg");
    const report2 = read(join(root, `_onboard-backup-${TS}-b`, "onboard-report.md"));
    assert.ok(report2.includes(`| ${f.brick} (reused) |`), "report table marks the reused brick");
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

// ═══ F-34: block-granularity factoring + near-dup report (both under --factor) ══════════════
// Byte-fidelity helper: the generated output minus the injected banner must equal the ORIGINAL
// bytes (the semantic "git diff empty" the migration promises). Originals in these fixtures end
// with a single \n and no EOF whitespace, so the compare is exact, not normalized.
const sansBanner = (root, skill) =>
  read(outFile(root, skill)).split("\n").filter((l) => !/^<!-- GENERATED by nbp-skillforge/.test(l)).join("\n");

test("factor F-34: a byte-identical BLOCK under DIFFERENT headings factors (section pass alone would miss it)", () => {
  const root = makeRoot({});
  const BLOCK = "Create the working folder first.\nWrite progress notes as you go.\nNever skip the folder step.";
  const one = `---\nname: one\ndescription: d.\n---\n# one\n\n## Setup\n\n${BLOCK}\n\nOne-only tail line.\n`;
  const two = `---\nname: two\ndescription: d.\n---\n# two\n\n## Bootstrap\n\n${BLOCK}\n\nTwo-only tail line.\n`;
  write(join(root, "out", "one.md"), one);
  write(join(root, "out", "two.md"), two);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    // headings differ → the whole sections are NOT byte-identical → only the block pass can hit
    assert.equal(r.factoring.factored.length, 1, "exactly one shared block brick");
    const f = r.factoring.factored[0];
    assert.match(f.brick, /^onboarded\/create-the-working-folder-first-[0-9a-f]{8}$/, "slug = first line of the block");
    assert.deepEqual(f.usedBy, ["one", "two"]);
    assert.equal(r.factoring.kept.length, 0);
    assert.match(read(recipe(root, "one")), /^<!-- include: onboarded\/create-the-working-folder-first-[0-9a-f]{8} -->$/m, "plain directive outside a fence, no indent");
    assert.ok(!read(recipe(root, "one")).includes("include!:"), "no bang outside a fence");
    // round trip byte-identical for both skills (semantic git-diff-empty)
    assert.equal(sansBanner(root, "one"), one);
    assert.equal(sansBanner(root, "two"), two);
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("factor F-34: an INDENTED multi-line block round-trips byte-identically (indent on the directive line)", () => {
  const root = makeRoot({});
  const IB = "  - checklist item one\n  - checklist item two\n  - checklist item three";
  const one = `---\nname: one\ndescription: d.\n---\n# one\n\n## A-side\n\n${IB}\n\nOne tail.\n`;
  const two = `---\nname: two\ndescription: d.\n---\n# two\n\n## B-side\n\n${IB}\n\nTwo tail.\n`;
  write(join(root, "out", "one.md"), one);
  write(join(root, "out", "two.md"), two);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.factoring.factored.length, 1);
    const brick = r.factoring.factored[0].brick;
    // the recipe's directive line carries the block's first-line indent (compose emits b.trim())
    assert.match(read(recipe(root, "one")), new RegExp(`^  <!-- include: ${brick.replace("/", "\\/")} -->$`, "m"));
    // the brick body is VERBATIM, first-line indent included
    assert.equal(read(join(root, "bricks", brick + ".md")), IB + "\n");
    assert.equal(sansBanner(root, "one"), one, "indent preserved through the round trip");
    assert.equal(sansBanner(root, "two"), two);
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("factor F-34: a gate mismatch (trailing whitespace lost by b.trim()) self-reverts, run never fails", () => {
  const root = makeRoot({});
  // trailing spaces on the LAST block line: compose emits b.trim(), so the factored round trip
  // drops them → gate mismatch → both consumers revert to verbatim and the brick is dropped.
  const TR = "keep this line.\nand this line.\nlast line with trailing spaces.   ";
  const one = `---\nname: one\ndescription: d.\n---\n# one\n\n## H-one\n\n${TR}\n\nOne tail.\n`;
  const two = `---\nname: two\ndescription: d.\n---\n# two\n\n## H-two\n\n${TR}\n\nTwo tail.\n`;
  write(join(root, "out", "one.md"), one);
  write(join(root, "out", "two.md"), two);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, "factoring never fails the onboard");
    assert.equal(r.factoring.factored.length, 0, "no brick survives without a consumer");
    assert.deepEqual([...r.factoring.kept].sort(), ["one", "two"], "both skills reverted to verbatim");
    assert.ok(!read(recipe(root, "one")).includes("<!-- include"), "recipe back to verbatim");
    // the regenerated outputs reproduce the ORIGINAL bytes, trailing spaces intact (mid-file
    // trailing whitespace is only at risk inside a brick — verbatim recipes keep it)
    assert.equal(sansBanner(root, "one"), one);
    assert.equal(sansBanner(root, "two"), two);
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("factor F-34(b): near-duplicates (same first line, diverging body) are REPORTED, nothing written", () => {
  const root = makeRoot({});
  write(join(root, "out", "dois.md"), `---\nname: dois\ndescription: d.\n---\n# dois\n\nDeploy checklist for the run:\nTarget the PRODUCTION cluster.\nConfirm the version tag.\n`);
  write(join(root, "out", "um.md"), `---\nname: um\ndescription: d.\n---\n# um\n\nDeploy checklist for the run:\nTarget the STAGING cluster.\nConfirm the version tag.\n`);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.factoring.factored.length, 0, "diverging bodies never factor mechanically");
    // additive --json surface
    assert.equal(r.factoring.nearDups.length, 1);
    const nd = r.factoring.nearDups[0];
    assert.equal(nd.slug, "deploy-checklist-for-the-run");
    assert.equal(nd.firstLine, "Deploy checklist for the run:");
    assert.deepEqual(nd.skills, ["dois", "um"]);
    assert.equal(nd.variants.length, 2);
    // CLI msg carries the count
    assert.match(r.msg, /1 near-duplicate group\(s\) reported/);
    // report: section header, per-skill diff lines, mechanical {{param}} suggestion
    const report = read(join(root, "_onboard-backup-" + TS, "onboard-report.md"));
    assert.match(report, /## near-duplicates \(report-only — candidates for a \{\{param\}\} brick\)/);
    assert.match(report, /dois: `Target the PRODUCTION cluster\.`/);
    assert.match(report, /um: `Target the STAGING cluster\.`/);
    assert.match(report, /suggested `\{\{param1\}\}` line: `Target the \{\{param1\}\} cluster\.`/);
    // NOTHING written beyond the report: no brick, recipes stay verbatim
    assert.equal(has(join(root, "bricks", "onboarded")), false, "no brick dir created");
    assert.ok(!read(recipe(root, "um")).includes("<!-- include"), "recipe verbatim");
    assert.equal(sansBanner(root, "um").includes("Target the STAGING cluster."), true);
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("factor F-34: section pass and block pass compose in one run (no double-swap, both gates zero)", () => {
  const root = makeRoot({});
  const BLOCK = "Shared block line alpha.\nShared block line bravo.\nShared block line charlie.";
  const one = `---\nname: one\ndescription: d.\n---\n# one\n\n${SHARED}\n\n## A-only\n\n${BLOCK}\n\nOne tail.\n`;
  const two = `---\nname: two\ndescription: d.\n---\n# two\n\n${SHARED}\n\n## B-only\n\n${BLOCK}\n\nTwo tail.\n`;
  write(join(root, "out", "one.md"), one);
  write(join(root, "out", "two.md"), two);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    // the SHARED heading-section factors via the (untouched) section pass; the block under the
    // differing headings factors via the F-34 block pass — 2 bricks, no overlap, no double-swap.
    assert.equal(r.factoring.factored.length, 2);
    const bricks = r.factoring.factored.map((f) => f.brick).sort();
    assert.match(bricks[0], /^onboarded\/shared-block-line-alpha-[0-9a-f]{8}$/);
    assert.match(bricks[1], /^onboarded\/working-folder-[0-9a-f]{8}$/);
    assert.equal(r.factoring.kept.length, 0);
    assert.equal(r.factoring.nearDups.length, 0, "identical everywhere → not a near-dup");
    assert.equal(sansBanner(root, "one"), one);
    assert.equal(sansBanner(root, "two"), two);
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

// ═══ F-31 Fase 5: the forge-onboard agent skill (installSkill + ecosystem closure) ══════════
test("installSkill: materializes with the marker; idempotent; never clobbers an unmarked homonym", () => {
  const root = makeRoot({});
  try {
    const r1 = installSkill({ root });
    assert.equal(r1.ok, true, r1.msg);
    const dest = join(root, "out", "forge-onboard.md");
    assert.equal(has(dest), true);
    assert.match(read(dest), /forge-role: nbp-skillforge\/onboard/, "carries the marker");
    const r2 = installSkill({ root });
    assert.equal(r2.already, true, "byte-identical reinstall is a no-op");
    // a same-named USER file (no marker) is never clobbered
    writeFileSync(dest, "---\nname: forge-onboard\ndescription: user's own!\n---\nmine\n");
    const r3 = installSkill({ root });
    assert.equal(r3.ok, false);
    assert.match(r3.msg, /does NOT carry the forge-role marker/);
    assert.match(read(dest), /mine/, "user file intact");
  } finally { cleanup(root); }
});

test("installSkill → onboard scan: the installed skill is excluded-forge-role (never re-ingested)", () => {
  const root = makeRoot({});
  try {
    installSkill({ root });
    const r = onboard({ root, ts: TS });
    assert.equal(r.entries.find((e) => /forge-onboard/.test(e.file)).status, "excluded-forge-role");
  } finally { cleanup(root); }
});

test("auto-enforce (maintainer decision): the ephemeral tool is REMOVED in the same step strict mode turns on", () => {
  const root = makeRoot({});
  write(join(root, "out", "only.md"), "---\nname: only\ndescription: d.\n---\n# only\nbody\n");
  try {
    installSkill({ root });
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.enforced, true, "tool file does not block the 100% condition");
    assert.equal(has(join(root, "out", "forge-onboard.md")), false, "ephemeral tool removed with the enable");
    assert.equal(loadConfig(root).enforceGenerated, true);
    assert.equal(run({ root, mode: "check" }).ok, true, "strict mode green immediately");
    // and it comes back on demand
    assert.equal(installSkill({ root }).ok, true);
  } finally { cleanup(root); }
});

test("auto-enforce: with skips present the tool is NOT removed (no enable, no removal)", () => {
  const root = makeRoot({});
  write(join(root, "out", "only.md"), "---\nname: only\ndescription: d.\n---\n# only\nbody\n");
  write(join(root, "out", "Bad_Name.md"), "---\nname: Bad_Name\ndescription: d.\n---\nbad\n");
  try {
    installSkill({ root });
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.enforced, false);
    assert.equal(has(join(root, "out", "forge-onboard.md")), true, "tool stays when enable is blocked");
  } finally { cleanup(root); }
});

test("assets: the bundled spec + wrapper resolve from the package and agree on the marker", () => {
  const spec = readFileSync(new URL("../assets/onboard/ONBOARD-SPEC.md", import.meta.url), "utf8");
  const wrapper = readFileSync(new URL("../assets/onboard/claude-code/forge-onboard.md", import.meta.url), "utf8");
  assert.match(spec, /you propose|You propose/i);
  assert.match(spec, /forge-role: nbp-skillforge\/onboard/);
  assert.match(wrapper, /^---\nname: forge-onboard/m);
  assert.match(wrapper, /ONBOARD-SPEC/, "wrapper points at the embedded protocol (no file path — self-contained install)");
  assert.match(readFileSync(new URL("../package.json", import.meta.url), "utf8"), /"assets\/onboard\/"/); // URL direto: imune a %20 (dual-review)
});

// ═══ Fase 5 dual-review regression fixes ════════════════════════════════════════════════════
test("engine review-fix: an installed tool under PRE-EXISTING strict mode is never an orphan", () => {
  const root = makeRoot({ config: { enforceGenerated: true } });
  write(join(root, "recipes", "only.md"), "---\nname: only\ndescription: d.\n---\n# only\nbody\n");
  run({ root, mode: "build" });
  try {
    const r = installSkill({ root });
    assert.equal(r.ok, true, r.msg);
    const chk = run({ root, mode: "check" });
    assert.equal(chk.ok, true, "check green with the marked tool present under enforceGenerated");
    assert.equal(chk.orphans, 0);
  } finally { cleanup(root); }
});

test("review-fix: auto-enforce with --from still sees (and removes) a tool installed in the OUT dir", () => {
  const root = makeRoot({});
  installSkill({ root }); // tool sits in out/, but the scan will look at elsewhere/
  write(join(root, "elsewhere", "ext.md"), "---\nname: ext\ndescription: d.\n---\n# ext\nbody\n");
  try {
    const r = onboard({ root, ts: TS, apply: true, from: "elsewhere" });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.enforced, true, "the marked tool in out/ no longer blocks the enable");
    assert.equal(has(join(root, "out", "forge-onboard.md")), false, "tool removed from the governed out dir");
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("review-fix: a MARKED file in the --from source dir is never deleted (not an installation)", () => {
  const root = makeRoot({});
  write(join(root, "elsewhere", "ext.md"), "---\nname: ext\ndescription: d.\n---\n# ext\nbody\n");
  write(join(root, "elsewhere", "tool-copy.md"), "---\nname: tool-copy\ndescription: t.\nforge-role: nbp-skillforge/onboard\n---\nuser's template copy\n");
  try {
    const r = onboard({ root, ts: TS, apply: true, from: "elsewhere" });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.enforced, true);
    assert.equal(has(join(root, "elsewhere", "tool-copy.md")), true, "source-dir marked file untouched");
  } finally { cleanup(root); }
});

test("review-fix: --from escaping the project root via .. is refused", () => {
  const root = makeRoot({});
  try {
    const r = onboard({ root, ts: TS, from: join("..", "outside") });
    assert.equal(r.ok, false);
    assert.match(r.msg, /must stay inside the project root/);
  } finally { cleanup(root); }
});

test("review-fix: installSkill refuses a role-overlapping config before writing anything", () => {
  const root = makeRoot({ config: { out: "bricks" } });
  try {
    const r = installSkill({ root });
    assert.equal(r.ok, false);
    assert.match(r.msg, /must not be inside or equal to/);
    assert.equal(has(join(root, "bricks", "forge-onboard.md")), false, "nothing written");
  } finally { cleanup(root); }
});

test("review-fix: the installed skill is SELF-CONTAINED (protocol embedded, no package paths)", () => {
  const root = makeRoot({});
  try {
    installSkill({ root });
    const installed = read(join(root, "out", "forge-onboard.md"));
    assert.match(installed, /ONBOARD-SPEC\.md — embedded verbatim/, "spec inlined at install time");
    assert.match(installed, /Approval unit = the GROUP/, "the actual protocol body is present");
    assert.ok(!installed.includes("node_modules/nbp-skillforge"), "no package-path resolution instructions");
  } finally { cleanup(root); }
});

// ═══ Fable bug-hunt regression fixes (session 2026-07-06, post-0.7.0) ═══════════════════════
test("Fable B1: divergent same-named file in out[1] → skip-collision, its bytes SURVIVE", () => {
  const root = makeRoot({ config: { out: ["out", "second-out"] } });
  write(join(root, "out", "foo.md"), "---\nname: foo\ndescription: d.\n---\n# foo A-version\n");
  write(join(root, "second-out", "foo.md"), "PRECIOUS hand-made B content — must survive\n");
  write(join(root, "out", "bar.md"), "---\nname: bar\ndescription: d.\n---\n# bar\n");
  try {
    const r = onboard({ root, ts: TS, apply: true });
    const foo = r.entries.find((e) => /foo/.test(e.file));
    assert.equal(foo.status, "skip-collision", "divergent copy detected");
    assert.match(read(join(root, "second-out", "foo.md")), /PRECIOUS/, "out[1] bytes intact");
    assert.equal(r.enforced, false, "no false '100% migrated' announcement");
    // bar (no divergent copy) migrates normally
    assert.equal(has(recipe(root, "bar")), true);
  } finally { cleanup(root); }
});

test("Fable B1b: byte-IDENTICAL copy in out[1] is allowed (content is the snapshotted source)", () => {
  const root = makeRoot({ config: { out: ["out", "second-out"] } });
  const content = "---\nname: foo\ndescription: d.\n---\n# foo same everywhere\n";
  write(join(root, "out", "foo.md"), content);
  write(join(root, "second-out", "foo.md"), content);
  try {
    const r = onboard({ root, ts: TS, apply: true });
    assert.equal(r.entries.find((e) => /foo/.test(e.file)).status, "eligible");
    assert.equal(r.ok, true, r.msg);
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("Fable B6: --from equal to outs[0] spelled with backslashes is NOT a self-collision", () => {
  const root = makeRoot({ config: { out: "sub/cmd" } });
  write(join(root, "sub", "cmd", "x.md"), "---\nname: x\ndescription: d.\n---\n# x\n");
  try {
    const r = onboard({ root, ts: TS, from: "sub\\cmd" }); // backslash spelling of the same dir
    assert.equal(r.entries.find((e) => /x\.md/.test(e.file)).status, "eligible", "no self-collision");
  } finally { cleanup(root); }
});

test("Fable B6b: --from pointing at out[1] does not make its own files collide with themselves", () => {
  const root = makeRoot({ config: { out: ["out", "second-out"] } });
  write(join(root, "second-out", "y.md"), "---\nname: y\ndescription: d.\n---\n# y\n");
  try {
    const r = onboard({ root, ts: TS, from: "second-out" });
    assert.equal(r.entries.find((e) => /y\.md/.test(e.file)).status, "eligible");
  } finally { cleanup(root); }
});

test("Fable B10: import strips a GENERATED banner even after blank lines (no double-banner)", async () => {
  const { importFile } = await import("../src/lifecycle.mjs");
  const root = makeRoot({});
  const src = join(root, "external", "gappy.md");
  write(src, "---\nname: gappy\ndescription: d.\n---\n\n\n<!-- GENERATED by nbp-skillforge from recipes/gappy.md — do not edit here. -->\nreal body\n");
  try {
    const r = importFile(src, { root });
    assert.equal(r.ok, true, r.msg);
    assert.equal(run({ root, mode: "build" }).ok, true);
    const out = read(outFile(root, "gappy"));
    assert.equal((out.match(/GENERATED by nbp-skillforge/g) || []).length, 1, "exactly one banner");
  } finally { cleanup(root); }
});

test("Fable B9: --from pointing at a FILE is a clean user-facing error, not ENOTDIR", () => {
  const root = makeRoot({});
  write(join(root, "some.md"), "# a file\n");
  try {
    assert.throws(() => onboard({ root, ts: TS, from: "some.md" }),
      (e) => e.userFacing === true && /not a directory/.test(e.message));
  } finally { cleanup(root); }
});

// ═══ --variants: near-dup groups materialize as NAMED VARIANT FAMILIES (onboarded/<slug>_NN) ═
// Every version is kept VERBATIM (one brick per variant, fidelity gate per skill) — the family
// is a staging area for the human Fase B unification into ONE {{param}} brick, never a merge.
const DEP = (cluster) => `Deploy checklist for the run:\nTarget the ${cluster} cluster.\nConfirm the version tag.`;
const depSkill = (name, cluster) => `---\nname: ${name}\ndescription: d.\n---\n# ${name}\n\n${DEP(cluster)}\n`;
const VSLUG = "deploy-checklist-for-the-run";
const vBrick = (root, nn) => join(root, "bricks", "onboarded", `${VSLUG}_${nn}.md`);

test("variants: 3 divergent versions → bricks _01.._03 in report order, swaps + round-trip byte-identical", () => {
  const root = makeRoot({});
  const a = depSkill("aa", "ALPHA"), b = depSkill("bb", "BRAVO"), c = depSkill("cc", "CHARLIE");
  write(join(root, "out", "aa.md"), a);
  write(join(root, "out", "bb.md"), b);
  write(join(root, "out", "cc.md"), c);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true, variants: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(r.factoring.factored.length, 0, "nothing byte-identical — the identical passes stay empty");
    // --json additive surface: one group, three variant bricks, NN in the report's variant order
    assert.equal(r.factoring.variants.length, 1);
    const v = r.factoring.variants[0];
    assert.equal(v.group, VSLUG);
    assert.equal(v.firstLine, "Deploy checklist for the run:");
    assert.deepEqual(v.bricks.map((x) => x.brick), [`onboarded/${VSLUG}_01`, `onboarded/${VSLUG}_02`, `onboarded/${VSLUG}_03`]);
    assert.deepEqual(v.bricks.map((x) => x.skills), [["aa"], ["bb"], ["cc"]]);
    // brick = advisory fm (dropped at build) + the variant body VERBATIM
    assert.equal(read(vBrick(root, "01")),
      `---\npiece: ${VSLUG}_01\nvariant-group: ${VSLUG}\nsummary: variant 01 of a near-identical family — all variants kept verbatim; candidates for ONE {{param}} brick (see the onboard report / Fase B)\n---\n${DEP("ALPHA")}\n`);
    // each recipe carries the plain directive (outside a fence, no indent)
    assert.match(read(recipe(root, "aa")), new RegExp(`^<!-- include: onboarded/${VSLUG}_01 -->$`, "m"));
    assert.match(read(recipe(root, "cc")), new RegExp(`^<!-- include: onboarded/${VSLUG}_03 -->$`, "m"));
    // fidelity: round trip byte-identical for all three (git-diff-empty promise holds)
    assert.equal(sansBanner(root, "aa"), a);
    assert.equal(sansBanner(root, "bb"), b);
    assert.equal(sansBanner(root, "cc"), c);
    assert.equal(run({ root, mode: "check" }).ok, true);
    // report: the group gains its materialization line; the {{param}} suggestion still renders
    const report = read(join(root, "_onboard-backup-" + TS, "onboard-report.md"));
    assert.ok(report.includes(`- materialized as: ${VSLUG}_01 (aa), ${VSLUG}_02 (bb), ${VSLUG}_03 (cc) — unify into one {{param}} brick in Fase B (forge-onboard)`), "materialized line present");
    assert.match(report, /suggested `\{\{param1\}\}` line/);
    // CLI msg: the variant clause is appended only because N > 0 — and the near-dup clause must
    // not contradict it (review FIX 3: no "report-only" claim next to "materialized")
    assert.match(r.msg, /1 variant group\(s\) materialized \(3 variant brick\(s\)\)/);
    assert.match(r.msg, /1 near-duplicate group\(s\) found \(see the report\)/);
    assert.ok(!r.msg.includes("report-only"), "the report-only claim never coexists with a materialization");
  } finally { cleanup(root); }
});

test("variants: a variant SHARED by 2 skills → ONE brick with both consumers (never the sha8 path)", () => {
  const root = makeRoot({});
  write(join(root, "out", "p1.md"), depSkill("p1", "ALPHA"));
  write(join(root, "out", "p2.md"), depSkill("p2", "ALPHA"));
  write(join(root, "out", "p3.md"), depSkill("p3", "BRAVO"));
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true, variants: true });
    assert.equal(r.ok, true, r.msg);
    // the p1+p2 byte-identical pair belongs to the FAMILY, not to the identical block pass
    assert.equal(r.factoring.factored.length, 0, "the shared variant is claimed by the family, not sha8-factored");
    const v = r.factoring.variants[0];
    assert.deepEqual(v.bricks, [
      { brick: `onboarded/${VSLUG}_01`, skills: ["p1", "p2"] },
      { brick: `onboarded/${VSLUG}_02`, skills: ["p3"] },
    ]);
    // every brick on disk is a family member — no sha8-named brick was minted
    assert.ok(readdirSync(join(root, "bricks", "onboarded")).every((f) => /_\d{2}\.md$/.test(f)), "no sha8 brick");
    assert.equal(sansBanner(root, "p1"), depSkill("p1", "ALPHA"));
    assert.equal(sansBanner(root, "p3"), depSkill("p3", "BRAVO"));
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("variants regression: WITHOUT --variants nothing materializes and the report keeps today's shape", () => {
  const root = makeRoot({});
  write(join(root, "out", "aa.md"), depSkill("aa", "ALPHA"));
  write(join(root, "out", "bb.md"), depSkill("bb", "BRAVO"));
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true });
    assert.equal(r.ok, true, r.msg);
    assert.deepEqual(r.factoring.variants, [], "the --json key exists under --factor, empty without --variants");
    assert.equal(has(join(root, "bricks", "onboarded")), false, "no brick dir — nothing materialized");
    const report = read(join(root, "_onboard-backup-" + TS, "onboard-report.md"));
    assert.match(report, /## near-duplicates \(report-only — candidates for a \{\{param\}\} brick\)/, "pre-variants header intact");
    assert.match(report, /Nothing was written for these/, "pre-variants intro intact");
    assert.ok(!report.includes("materialized as:"), "no materialization line without the flag");
    assert.ok(!r.msg.includes("variant group(s) materialized"), "CLI msg untouched without the flag");
    // review FIX 3 regression: with nothing materialized the near-dup clause is byte-identical
    assert.ok(r.msg.includes("; 1 near-duplicate group(s) reported (report-only — see the report)"), "pre-variants clause intact");
  } finally { cleanup(root); }
});

test("variants: a family INSIDE a code fence materializes via include!:, round-trip byte-identical", () => {
  const root = makeRoot({});
  const F = (x) => "```\ndeploy sequence starts\nstep " + x + "\nfinish up\n```";
  const one = `---\nname: one\ndescription: d.\n---\n# one\n\nIntro one.\n\n${F("ALPHA")}\n`;
  const two = `---\nname: two\ndescription: d.\n---\n# two\n\nIntro two.\n\n${F("BRAVO")}\n`;
  write(join(root, "out", "one.md"), one);
  write(join(root, "out", "two.md"), two);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true, variants: true });
    assert.equal(r.ok, true, r.msg);
    const v = r.factoring.variants[0];
    assert.equal(v.group, "deploy-sequence-starts");
    // inside the fence only the F-33 bang form expands — the swap must use it
    assert.match(read(recipe(root, "one")), /^<!-- include!: onboarded\/deploy-sequence-starts_01 -->$/m);
    assert.ok(!read(recipe(root, "one")).includes("<!-- include: "), "no bang-less directive planted in the fence");
    // brick body verbatim (fence markers stay in the recipe, never in the brick)
    assert.ok(read(join(root, "bricks", "onboarded", "deploy-sequence-starts_01.md")).endsWith("---\ndeploy sequence starts\nstep ALPHA\nfinish up\n"));
    assert.equal(sansBanner(root, "one"), one, "byte-identical round trip through the fenced variant");
    assert.equal(sansBanner(root, "two"), two);
    assert.equal(run({ root, mode: "check" }).ok, true);
    assert.equal(gc(root, {}).orphans.length, 0, "bang-in-fence consumption keeps the family off the orphan list");
  } finally { cleanup(root); }
});

test("variants cross-batch: a later batch REUSES a byte-identical member; a divergent one extends the family", () => {
  const root = makeRoot({});
  write(join(root, "out", "aa.md"), depSkill("aa", "ALPHA"));
  write(join(root, "out", "bb.md"), depSkill("bb", "BRAVO"));
  try {
    const r1 = onboard({ root, ts: TS, apply: true, factor: true, variants: true });
    assert.equal(r1.ok, true, r1.msg);
    assert.equal(has(vBrick(root, "01")) && has(vBrick(root, "02")), true, "family seeded: _01 + _02");
    // batch 2: ONE new skill, byte-identical to the _01 variant — alone it could never form a
    // near-dup group; the on-disk family is what makes it a variant case (adoption + reuse).
    const cc = depSkill("cc", "ALPHA");
    write(join(root, "out", "cc.md"), cc);
    const r2 = onboard({ root, ts: TS + "-b", apply: true, factor: true, variants: true });
    assert.equal(r2.ok, true, r2.msg);
    assert.equal(r2.factoring.variants.length, 1);
    assert.deepEqual(r2.factoring.variants[0].bricks, [{ brick: `onboarded/${VSLUG}_01`, skills: ["aa", "cc"] }],
      "reused member reported with the WHOLE family membership (old consumer included)");
    assert.equal(has(vBrick(root, "03")), false, "no new member for a byte-identical variant");
    assert.match(read(recipe(root, "cc")), new RegExp(`^<!-- include: onboarded/${VSLUG}_01 -->$`, "m"));
    assert.equal(sansBanner(root, "cc"), cc);
    // the report surfaces the cross-batch join even though no in-batch near-dup group exists
    const report2 = read(join(root, `_onboard-backup-${TS}-b`, "onboard-report.md"));
    assert.match(report2, /cross-batch: joined an existing variant family/);
    assert.ok(report2.includes(`materialized as: ${VSLUG}_01 (aa, cc)`));
    // batch 3: a DIVERGENT variant grows the family at the next free NN
    const dd = depSkill("dd", "DELTA");
    write(join(root, "out", "dd.md"), dd);
    const r3 = onboard({ root, ts: TS + "-c", apply: true, factor: true, variants: true });
    assert.equal(r3.ok, true, r3.msg);
    assert.deepEqual(r3.factoring.variants[0].bricks, [{ brick: `onboarded/${VSLUG}_03`, skills: ["dd"] }]);
    assert.ok(read(vBrick(root, "03")).endsWith(`---\n${DEP("DELTA")}\n`), "new member is the divergent variant verbatim");
    assert.equal(sansBanner(root, "dd"), dd);
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

test("variants: --variants without --factor is a usage error; dry-run announces the --apply dependency", () => {
  const root = makeRoot({});
  write(join(root, "out", "x.md"), "---\nname: x\ndescription: d.\n---\n# x\nbody\n");
  try {
    const r = onboard({ root, ts: TS, apply: true, variants: true }); // no --factor
    assert.equal(r.ok, false);
    assert.match(r.msg, /--variants requires --factor/);
    assert.equal(has(join(root, "_onboard-backup-" + TS)), false, "usage error before any write");
    const dry = onboard({ root, ts: TS, factor: true, variants: true }); // no --apply
    assert.equal(dry.ok, true, dry.msg);
    assert.match(dry.msg, /--variants takes effect together with --apply/);
    assert.match(dry.msg, /--factor takes effect together with --apply/, "the --factor mention survives alongside");
  } finally { cleanup(root); }
});

test("variants: a gate mismatch reverts ONLY that skill; its consumer-less brick is dropped, run stays ok", () => {
  const root = makeRoot({});
  // trailing spaces on the LAST variant line + content after it: compose emits b.trim(), so the
  // factored round trip drops them mid-file → gate mismatch for `one` only; `two` stays factored.
  const one = `---\nname: one\ndescription: d.\n---\n# one\n\nshared first line here.\nvariant ONE middle.\nlast line.   \n\nOne tail.\n`;
  const two = `---\nname: two\ndescription: d.\n---\n# two\n\nshared first line here.\nvariant TWO middle.\nlast line.\n\nTwo tail.\n`;
  write(join(root, "out", "one.md"), one);
  write(join(root, "out", "two.md"), two);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true, variants: true });
    assert.equal(r.ok, true, "the variants pass never fails the onboard");
    assert.deepEqual(r.factoring.kept, ["one"], "the mismatching skill self-reverted");
    assert.ok(!read(recipe(root, "one")).includes("<!-- include"), "reverted recipe is verbatim again");
    assert.match(read(recipe(root, "two")), /^<!-- include: onboarded\/shared-first-line-here_02 -->$/m);
    assert.equal(has(join(root, "bricks", "onboarded", "shared-first-line-here_01.md")), false, "consumer-less variant brick dropped");
    assert.equal(has(join(root, "bricks", "onboarded", "shared-first-line-here_02.md")), true);
    assert.deepEqual(r.factoring.variants, [{
      group: "shared-first-line-here", firstLine: "shared first line here.",
      bricks: [{ brick: "onboarded/shared-first-line-here_02", skills: ["two"] }],
    }], "post-gate reality: only the surviving variant is reported");
    assert.match(r.msg, /1 variant group\(s\) materialized \(1 variant brick\(s\)\)/);
    assert.equal(sansBanner(root, "one"), one, "reverted skill reproduces its original bytes");
    assert.equal(sansBanner(root, "two"), two);
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

// ═══ --variants dual-review regression fixes (codex + agy, adjudicated by execution) ═════════
// FIX 1: a shared variant that is a WHOLE heading-section (no blank lines → byte-identical
// section core AND sub-block at once) used to be stolen by the section pass: the shared members
// landed at the sha8 path while the divergent one became <slug>_01 — a split family.
test("variants review-fix: a whole-section shared variant stays ONE family (section pass never splits it)", () => {
  const mk = (n, x) => `---\nname: ${n}\ndescription: d.\n---\n# ${n}\n\n### deploy\ndeploy sequence starts\nstep ${x}\nfinish up\n`;
  const root = makeRoot({});
  const one = mk("one", "ALPHA"), two = mk("two", "ALPHA"), three = mk("three", "BRAVO");
  write(join(root, "out", "one.md"), one);
  write(join(root, "out", "two.md"), two);
  write(join(root, "out", "three.md"), three);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true, variants: true });
    assert.equal(r.ok, true, r.msg);
    // the one+two byte-identical SECTION belongs to the family — never to the sha8 section pass
    assert.equal(r.factoring.factored.length, 0, "no sha8 brick steals the shared variant");
    assert.deepEqual(r.factoring.variants[0].bricks, [
      { brick: "onboarded/deploy_01", skills: ["one", "two"] },
      { brick: "onboarded/deploy_02", skills: ["three"] },
    ], "whole family together: _01 shared by one+two, _02 for the divergent three");
    assert.deepEqual(readdirSync(join(root, "bricks", "onboarded")).sort(), ["deploy_01.md", "deploy_02.md"], "family members only — no sha8 file on disk");
    assert.equal(sansBanner(root, "one"), one);
    assert.equal(sansBanner(root, "three"), three);
    assert.equal(run({ root, mode: "check" }).ok, true);
    // and WITHOUT --variants the identical section still factors at the sha8 path (regression):
    const root2 = makeRoot({});
    write(join(root2, "out", "one.md"), one);
    write(join(root2, "out", "two.md"), two);
    write(join(root2, "out", "three.md"), three);
    const r2 = onboard({ root: root2, ts: TS, apply: true, factor: true });
    assert.equal(r2.factoring.factored.length, 1, "sha8 section factoring intact without the flag");
    assert.match(r2.factoring.factored[0].brick, /^onboarded\/deploy-[0-9a-f]{8}$/);
    assert.deepEqual(r2.factoring.factored[0].usedBy, ["one", "two"]);
    cleanup(root2);
  } finally { cleanup(root); }
});

// FIX 2 fixtures: a 3-line block whose first line slugs to "deploy" — the family namespace the
// occupied-slot tests squat. (Divergent bodies → a near-dup group of two variants.)
const slotSkill = (n, x) => `---\nname: ${n}\ndescription: d.\n---\n# ${n}\n\ndeploy\nstep ${x}\nfinish up\n`;

test("variants review-fix: an occupied slot (same case, divergent body) is NEVER overwritten — family shifts to _02/_03", () => {
  const root = makeRoot({});
  write(join(root, "out", "one.md"), slotSkill("one", "ALPHA"));
  write(join(root, "out", "two.md"), slotSkill("two", "BRAVO"));
  const USER = "USER BRICK — do not clobber\n";
  write(join(root, "bricks", "onboarded", "deploy_01.md"), USER); // squat the first slot
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true, variants: true });
    assert.equal(r.ok, true, r.msg);
    assert.equal(read(join(root, "bricks", "onboarded", "deploy_01.md")), USER, "the user's brick survives byte-for-byte");
    assert.deepEqual(r.factoring.variants[0].bricks, [
      { brick: "onboarded/deploy_02", skills: ["one"] },
      { brick: "onboarded/deploy_03", skills: ["two"] },
    ], "the family allocates around the occupied slot");
    assert.equal(sansBanner(root, "one"), slotSkill("one", "ALPHA"));
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});

// FIX 2, the DESTRUCTIVE case (proven by execution on NTFS): a differently-cased occupant
// (Deploy_01.md) is invisible to the exact-case member parse, but on a case-insensitive
// filesystem writeFileSync(deploy_01.md) resolves to the SAME file — the old code overwrote it,
// the gate then failed on the engine's include case-match, and the consumer-less cleanup DELETED
// the user's file. The fix scans for a free slot with existsSync on the exact candidate path
// (which case-folds with the filesystem) and never reuses a member whose on-disk case diverges.
const CASE_INSENSITIVE_TMP = (() => {
  const d = makeRoot({});
  try {
    writeFileSync(join(d, "case-probe.txt"), "x");
    return existsSync(join(d, "CASE-PROBE.TXT"));
  } finally { cleanup(d); }
})();
test("variants review-fix: a differently-CASED occupant survives intact and is never reused (case-insensitive FS)", { skip: !CASE_INSENSITIVE_TMP }, () => {
  const root = makeRoot({});
  write(join(root, "out", "one.md"), slotSkill("one", "ALPHA"));
  write(join(root, "out", "two.md"), slotSkill("two", "BRAVO"));
  // body byte-identical to the ALPHA variant on purpose: even then it must NOT be reused (the
  // engine's include case-match would reject Deploy_01 for a deploy_01 directive at build).
  const USER = `---\nuser: brick\n---\ndeploy\nstep ALPHA\nfinish up\n`;
  write(join(root, "bricks", "onboarded", "Deploy_01.md"), USER);
  try {
    const r = onboard({ root, ts: TS, apply: true, factor: true, variants: true });
    assert.equal(r.ok, true, r.msg);
    // the user's file: same on-disk NAME (exact case) and same bytes — never overwritten/deleted
    const listing = readdirSync(join(root, "bricks", "onboarded")).sort();
    assert.deepEqual(listing, ["Deploy_01.md", "deploy_02.md", "deploy_03.md"], "occupant intact, family allocated around it");
    assert.equal(read(join(root, "bricks", "onboarded", "Deploy_01.md")), USER, "user bytes survive");
    assert.deepEqual(r.factoring.variants[0].bricks, [
      { brick: "onboarded/deploy_02", skills: ["one"] },
      { brick: "onboarded/deploy_03", skills: ["two"] },
    ], "the byte-identical but wrong-case occupant was not reused");
    assert.deepEqual(r.factoring.kept, [], "no gate casualty — every include case-matches its brick");
    assert.equal(sansBanner(root, "one"), slotSkill("one", "ALPHA"));
    assert.equal(sansBanner(root, "two"), slotSkill("two", "BRAVO"));
    assert.equal(run({ root, mode: "check" }).ok, true);
  } finally { cleanup(root); }
});
