// nbp-forge — composition engine. Builds SKILL.md/command files from recipes + bricks.
// Zero dependencies. Generalized from the engine it was extracted from (ADR 0036).
//
// Paths come from forge.config.json at the project root (or the defaults below):
//   { "bricks": "...", "recipes": "...", "out": "...", "enforceGenerated": false }
//
//   Include:  <!-- include: doc-checklist -->
//   Param:    <!-- include: run-dir | skill=fix; flags=--prefix fix --track -->  → {{skill}}/{{flags}}

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, realpathSync } from "node:fs";
import { join, dirname, basename, resolve, sep, isAbsolute, posix } from "node:path";

const DEFAULTS = {
  bricks: ".claude/forge/bricks",
  recipes: ".claude/forge/recipes",
  out: ".claude/commands",
  archive: ".claude/forge/_archive", // soft-delete target: recipe + exclusive bricks land here (versioned)
  enforceGenerated: false, // true = every generated file must have a recipe (forbids hand-made skills)
  deletePolicy: "soft",    // "soft" = move to archive (recoverable) · "hard" = delete permanently
  conformance: true,       // validate name/description against the SKILL.md standard when present
};

// agentskills SKILL.md spec: name is lowercase a-z/0-9 segments joined by single hyphens.
const NAME_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
// Minimal, zero-dep field reader: first matching line, value trimmed and unquoted. NOT a YAML
// parser — validates only single-line name/description (the standard's required scalar fields);
// block scalars (`|`/`>`) are out of scope. `fm` is already CRLF-normalized to LF by compose().
const unquote = (v) => (v.match(/^"(.*)"$/) || v.match(/^'(.*)'$/) || [, v])[1];
function validateConformance(skill, fm, errors) {
  const nameM = fm.match(/^name:[ \t]*(.*?)[ \t]*$/m);
  if (nameM) {
    const v = unquote(nameM[1]);
    if (!NAME_RE.test(v) || v.length > 64)
      errors.push(`conformance: [${skill}] name "${v}" must be lowercase a-z/0-9 in single-hyphen segments (no leading/trailing/doubled '-'), 1–64 chars`);
  }
  const descM = fm.match(/^description:[ \t]*(.*?)[ \t]*$/m);
  if (descM) {
    const v = unquote(descM[1]);
    if (v.length === 0) errors.push(`conformance: [${skill}] description must not be empty`);
    else if (v.length > 1024) errors.push(`conformance: [${skill}] description must be ≤1024 chars (got ${v.length})`);
  }
}

const INCLUDE = /<!--\s*include:\s*([^\s|]+)\s*(?:\|\s*([^]*?)\s*)?-->/g;
const BANNER = (name, recipes) =>
  `<!-- GENERATED by nbp-forge from ${recipes}/${name}.md — do not edit here; edit the recipe/brick and run \`npx nbp-forge build\`. -->`;
// Matches a leading GENERATED banner (with or without its trailing newline) — used by `import`
// to strip a previously-generated banner so a re-import never double-banners on the next build.
export const GENERATED_BANNER_RE = /^<!-- GENERATED by nbp-forge[\s\S]*?-->\n?/;

export function loadConfig(root) {
  const p = join(root, "forge.config.json");
  const user = existsSync(p) ? JSON.parse(readFileSync(p, "utf8")) : {};
  return { ...DEFAULTS, ...user };
}

// Brick paths included by a recipe's text (without .md). Basis for ref-counting. Backslashes are
// normalized to '/' so a `core\run` include keys the same as `core/run` (and as mdFiles on Windows).
export function includesOf(text) {
  // Canonicalize so `core\run`, `sub/../foo`, `./foo` all key the same as the real brick path
  // (and as mdFiles) — otherwise ref-counting (gc/remove) mismatches and could delete a used brick.
  return [...text.matchAll(INCLUDE)].map((m) => posix.normalize(m[1].trim().replace(/\\/g, "/")));
}

// Map brick-path → Set(skills) that include it, across the ACTIVE recipes.
export function brickConsumers(root, cfg = loadConfig(root)) {
  const recipesAbs = join(root, cfg.recipes);
  const map = {};
  if (!existsSync(recipesAbs)) return map;
  for (const f of readdirSync(recipesAbs).filter((f) => f.endsWith(".md"))) {
    const skill = basename(f, ".md");
    for (const b of includesOf(readFileSync(join(recipesAbs, f), "utf8"))) {
      (map[b] ??= new Set()).add(skill);
    }
  }
  return map;
}

export const splitFm = (txt) => {
  const m = txt.match(/^---[ \t]*\n([\s\S]*?)\n---[ \t]*\n?([\s\S]*)$/);
  return { fm: m ? m[1] : null, body: m ? m[2] : txt };
};
// Split on ';' separators, honoring backslash escapes so a value can hold a literal ';'.
// `\;` → literal ';' · `\\` → literal '\' · any other '\x' is left untouched.
const splitParams = (raw) => {
  const parts = [];
  let cur = "";
  for (let i = 0; i < raw.length; i++) {
    const c = raw[i];
    if (c === "\\" && (raw[i + 1] === ";" || raw[i + 1] === "\\")) cur += raw[++i]; // unescape
    else if (c === ";") { parts.push(cur); cur = ""; }
    else cur += c;
  }
  parts.push(cur);
  return parts;
};
const parseParams = (raw) => {
  const out = {};
  if (raw) for (const part of splitParams(raw)) {
    const s = part.trim(); if (!s) continue;
    const i = s.indexOf("=");
    out[i < 0 ? s : s.slice(0, i).trim()] = i < 0 ? "" : s.slice(i + 1).trim();
  }
  return out;
};

function compose(name, cfg, root, errors) {
  const bricksAbs = join(root, cfg.bricks);
  const raw = readFileSync(join(root, cfg.recipes, name + ".md"), "utf8").replace(/\r\n/g, "\n");
  const { fm, body } = splitFm(raw);
  if (cfg.conformance && fm !== null) validateConformance(name, fm, errors);
  const out = body.replace(INCLUDE, (_, p, rawP) => {
    const bp = posix.normalize(p.trim().replace(/\\/g, "/"));
    const file = join(bricksAbs, bp + ".md");
    // Keep includes inside the bricks root — an absolute or `../` (post-normalization) path must
    // not read (and inline) files outside bricks/, nor leave a path lifecycle code could move/delete.
    if (isAbsolute(bp) || bp === ".." || bp.startsWith("../") ||
        (resolve(file) !== resolve(bricksAbs) && !resolve(file).startsWith(resolve(bricksAbs) + sep))) {
      errors.push(`build error: [${name}] include path escapes bricks/: ${bp}`); return `‹UNSAFE INCLUDE: ${bp}›`;
    }
    if (!existsSync(file)) { errors.push(`build error: [${name}] include of missing brick: ${bp}`); return `‹MISSING BRICK: ${bp}›`; }
    const params = parseParams(rawP);
    let b = splitFm(readFileSync(file, "utf8").replace(/\r\n/g, "\n")).body;
    b = b.replace(/\{\{\s*([\w-]+)\s*\}\}/g, (_, k) => {
      if (!(k in params)) { errors.push(`build error: [${name}] brick ${bp} requires {{${k}}}, not provided by the recipe`); return `‹NO ${k}›`; }
      return params[k];
    });
    return b.trim();
  });
  const head = fm !== null ? `---\n${fm}\n---\n${BANNER(name, cfg.recipes)}\n` : `${BANNER(name, cfg.recipes)}\n`;
  return head + out.replace(/\s*$/, "") + "\n";
}

// mode: "build" | "check". dryRun (build only): compose + classify, write NOTHING.
// Returns { ok, drift, orphans, errors, count, written, unchanged, plan }.
// `plan` (build mode) is [{ name, status }] with status "create" | "change" | "same".
export function run({ root = process.cwd(), mode = "build", dryRun = false } = {}) {
  const cfg = loadConfig(root);
  const recipesAbs = join(root, cfg.recipes);
  const outAbs = join(root, cfg.out);
  const bricksAbs = join(root, cfg.bricks);
  const archiveAbs = join(root, cfg.archive);
  // The role dirs must be mutually non-nested: build writes into out, and gc scans bricks
  // recursively — so any overlap (equal, or one inside another) could clobber/delete source files.
  // Case-fold on case-insensitive filesystems (Windows/macOS) so `Bricks` and `bricks` overlap.
  const ci = process.platform === "win32" || process.platform === "darwin";
  // realpath resolves symlinks/junctions (so `out` symlinked at `recipes` is caught) and gives the
  // canonical case for existing dirs; fall back to resolve() for a role dir that doesn't exist yet.
  const norm = (p) => { let r; try { r = realpathSync.native(resolve(p)); } catch { r = resolve(p); } return ci ? r.toLowerCase() : r; };
  const R = Object.entries({ bricks: bricksAbs, recipes: recipesAbs, out: outAbs, archive: archiveAbs }).map(([k, v]) => [k, norm(v)]);
  for (const [ak, a] of R) for (const [bk, b] of R)
    if (ak !== bk && (a === b || b.startsWith(a + sep)))
      return { ok: false, errors: [`config error: '${bk}' must not be inside or equal to '${ak}' (build/gc would clobber source files)`], drift: 0, orphans: 0 };
  if (!existsSync(recipesAbs)) return { ok: false, errors: [`no recipes directory: ${cfg.recipes}`], drift: 0, orphans: 0 };

  const names = readdirSync(recipesAbs).filter((f) => f.endsWith(".md")).map((f) => basename(f, ".md"));
  const errors = [];
  const plan = []; // build mode: [{ name, dest, built, status }] — status drives skip-if-unchanged
  let drift = 0;

  for (const name of names) {
    const built = compose(name, cfg, root, errors); // always LF (compose normalizes its inputs)
    const dest = join(outAbs, name + ".md");
    const raw = existsSync(dest) ? readFileSync(dest, "utf8") : null;
    if (mode === "check") {
      // Drift-gate is CR-insensitive: a CRLF checkout (git autocrlf) is NOT a false positive.
      const cur = raw === null ? null : raw.replace(/\r\n/g, "\n");
      if (cur !== built) { drift++; errors.push(`drift: ${cfg.out}/${name}.md is out of sync with its recipe`); }
    } else {
      // Build compares RAW bytes so it stays the source of the "output is always LF" guarantee:
      // a CRLF-on-disk output differs from the LF `built`, so it is rewritten (healed), not skipped.
      // Only a byte-identical (LF) file is "same" → the skip-if-unchanged no-op.
      plan.push({ name, dest, built, status: raw === null ? "create" : raw !== built ? "change" : "same" });
    }
  }

  let orphans = 0;
  if (cfg.enforceGenerated && existsSync(outAbs)) {
    const recipeNames = new Set(names);
    for (const f of readdirSync(outAbs).filter((f) => f.endsWith(".md"))) {
      const n = basename(f, ".md");
      if (!recipeNames.has(n)) { orphans++; errors.push(`orphan: ${cfg.out}/${n}.md has no recipe (enforceGenerated)`); }
    }
  }

  // Blocking errors (missing brick/param, or a conformance violation) → write nothing
  // (never emit a corrupt or non-standard output). All-or-nothing, like the existing build.
  const blocking = errors.some((e) => e.startsWith("build error:") || e.startsWith("conformance:"));
  let written = 0;
  if (mode === "build" && !blocking && !dryRun) {
    // Skip-if-unchanged: only touch a file whose content actually differs. An identical re-build
    // leaves the working tree clean (no spurious mtime churn) and makes `written` an honest count.
    for (const { dest, built, status } of plan) {
      if (status === "same") continue;
      mkdirSync(dirname(dest), { recursive: true });
      writeFileSync(dest, built);
      written++;
    }
  }

  const unchanged = mode === "build" ? plan.filter((p) => p.status === "same").length : 0;
  return {
    ok: errors.length === 0, drift, orphans, errors, count: names.length, written, unchanged,
    plan: mode === "build" ? plan.map(({ name, status }) => ({ name, status })) : undefined,
  };
}
