// nbp-forge — motor de composição. Monta SKILL.md/commands a partir de recipes + bricks.
// Zero dependências. Portado e generalizado do engine de origem (athena-conecta, ADR 0036).
//
// Caminhos vêm de forge.config.json na raiz do projeto (ou defaults abaixo):
//   { "bricks": "...", "recipes": "...", "out": "...", "enforceGenerated": false }
//
//   Include:  <!-- include: doc-checklist -->
//   Param:    <!-- include: run-dir | skill=fix; flags=--prefix fix --track -->  → {{skill}}/{{flags}}

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname, basename } from "node:path";

const DEFAULTS = {
  bricks: ".claude/forge/bricks",
  recipes: ".claude/forge/recipes",
  out: ".claude/commands",
  archive: ".claude/forge/_archive", // soft-delete: recipe + bricks exclusivos vão pra cá (versionado)
  enforceGenerated: false, // true = todo arquivo gerado precisa de recipe (proíbe edição "na mão")
  deletePolicy: "soft",    // "soft" = move pro archive (recuperável) · "hard" = apaga de vez
};

const INCLUDE = /<!--\s*include:\s*([^\s|]+)\s*(?:\|\s*([^]*?)\s*)?-->/g;
const BANNER = (name, recipes) =>
  `<!-- GENERATED by nbp-forge from ${recipes}/${name}.md — do not edit here; edit the recipe/brick and run \`forge build\`. -->`;

export function loadConfig(root) {
  const p = join(root, "forge.config.json");
  const user = existsSync(p) ? JSON.parse(readFileSync(p, "utf8")) : {};
  return { ...DEFAULTS, ...user };
}

// Paths de brick incluídos por um texto de recipe (sem .md). Base do ref-count.
export function includesOf(text) {
  return [...text.matchAll(INCLUDE)].map((m) => m[1].trim());
}

// Mapa brick-path → Set(skills) que o incluem, sobre as recipes ATIVAS.
export function brickConsumers(root, cfg = loadConfig(root)) {
  const recipesAbs = join(root, cfg.recipes);
  const map = {};
  if (!existsSync(recipesAbs)) return map;
  for (const f of readdirSync(recipesAbs).filter((f) => f.endsWith(".md"))) {
    const skill = basename(f, ".md");
    for (const b of includesOf(readFileSync(join(recipesAbs, f), "utf8"))) {
      (map[b] ??= new Set()).add(skill);
    }
  }
  return map;
}

const splitFm = (txt) => {
  const m = txt.match(/^---[ \t]*\n([\s\S]*?)\n---[ \t]*\n?([\s\S]*)$/);
  return { fm: m ? m[1] : null, body: m ? m[2] : txt };
};
const parseParams = (raw) => {
  const out = {};
  if (raw) for (const part of raw.split(";")) {
    const s = part.trim(); if (!s) continue;
    const i = s.indexOf("=");
    out[i < 0 ? s : s.slice(0, i).trim()] = i < 0 ? "" : s.slice(i + 1).trim();
  }
  return out;
};

function compose(name, cfg, root, errors) {
  const bricksAbs = join(root, cfg.bricks);
  const raw = readFileSync(join(root, cfg.recipes, name + ".md"), "utf8").replace(/\r\n/g, "\n");
  const { fm, body } = splitFm(raw);
  const out = body.replace(INCLUDE, (_, p, rawP) => {
    const file = join(bricksAbs, p.trim() + ".md");
    if (!existsSync(file)) { errors.push(`[${name}] include de brick inexistente: ${p.trim()}`); return `‹MISSING BRICK: ${p.trim()}›`; }
    const params = parseParams(rawP);
    let b = splitFm(readFileSync(file, "utf8").replace(/\r\n/g, "\n")).body;
    b = b.replace(/\{\{\s*([\w-]+)\s*\}\}/g, (_, k) => {
      if (!(k in params)) { errors.push(`[${name}] brick ${p.trim()} requer {{${k}}} não fornecido pela recipe`); return `‹NO ${k}›`; }
      return params[k];
    });
    return b.trim();
  });
  const head = fm !== null ? `---\n${fm}\n---\n${BANNER(name, cfg.recipes)}\n` : `${BANNER(name, cfg.recipes)}\n`;
  return head + out.replace(/\s*$/, "") + "\n";
}

// mode: "build" | "check". Retorna { ok, drift, orphans, errors }.
export function run({ root = process.cwd(), mode = "build" } = {}) {
  const cfg = loadConfig(root);
  const recipesAbs = join(root, cfg.recipes);
  const outAbs = join(root, cfg.out);
  if (!existsSync(recipesAbs)) return { ok: false, errors: [`sem diretório de recipes: ${cfg.recipes}`], drift: 0, orphans: 0 };

  const names = readdirSync(recipesAbs).filter((f) => f.endsWith(".md")).map((f) => basename(f, ".md"));
  const errors = [];
  const toWrite = [];
  let drift = 0;

  for (const name of names) {
    const built = compose(name, cfg, root, errors);
    const dest = join(outAbs, name + ".md");
    if (mode === "check") {
      const cur = existsSync(dest) ? readFileSync(dest, "utf8").replace(/\r\n/g, "\n") : null;
      if (cur !== built) { drift++; errors.push(`DRIFT: ${cfg.out}/${name}.md fora de sincronia com a recipe`); }
    } else {
      toWrite.push([dest, built]);
    }
  }

  let orphans = 0;
  if (cfg.enforceGenerated && existsSync(outAbs)) {
    const recipeNames = new Set(names);
    for (const f of readdirSync(outAbs).filter((f) => f.endsWith(".md"))) {
      const n = basename(f, ".md");
      if (!recipeNames.has(n)) { orphans++; errors.push(`ORPHAN: ${cfg.out}/${n}.md sem recipe (enforceGenerated)`); }
    }
  }

  // Erro de composição → não grava nada (não deixa arquivo corrompido).
  const composeErrors = errors.some((e) => /MISSING BRICK|requer \{\{/.test(e));
  if (mode === "build" && !composeErrors) {
    for (const [dest, built] of toWrite) { mkdirSync(dirname(dest), { recursive: true }); writeFileSync(dest, built); }
  }

  return { ok: errors.length === 0, drift, orphans, errors, count: names.length, written: mode === "build" && !composeErrors ? toWrite.length : 0 };
}
